### ISSUE TITLE
Colour palette texture atlas for merged geometries

### ISSUE THREAD

**Issue by harrycollin** [ThatOpen/engine_components#104]
### Description 📝

Generate a simple colour palette texture to replace multiple materials in merged geometries. With some simple UV mapping you map entire sections of a merged geometry to single pixels on a texture. This results in a single draw call for that geometry instead of n draw calls for n colours.

This could also be applied to instanced items to keep the number of unique materials to one. Although the benefits become less noticeable.

### Suggested solution 💡

Based on the colours found in a merged geometry generate a small texture with a resolution of 1 x (unique colours) and UV map items to pixels in this texture. Additional pixel padding might be needed.

### Additional context ☝️

This approach can be found in many 2D games where a larger texture atlas is used for many sprites. Resulting in fewer draw calls. 

Example texture atlas:
![image](https://github.com/IFCjs/components/assets/10602138/8a8c6f25-a94b-480c-ac3e-d6ffd76051c8)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
This is a brilliant idea. I'm adding it to the next milestone!

**Comment by agviegas** [comment]
This is a great idea, but would also make the library more complex. Streaming should already give us decent performance, even with bigger models. We'll leave this for now and keep this in mind as a resort to come back to if draw calls become an issue in the future
