### ISSUE TITLE
Load Ifc with the new openbim-components library

### ISSUE THREAD

**Issue by nachovoss** [ThatOpen/engine_components#108]
I was wondering if there is a tutorial   or examples of how to load an IFC using the new components npm package?

**Comment by HoyosJuan** [comment]
Hi @nachovoss!

I've noticed you're already in [That Open People](https://people.thatopen.com/). I kindly suggest you go to [Ask the Community](https://people.thatopen.com/c/conversations/) for this type of question, you will get the whole community at your disposal to help while also keeping clean the issues list here in the repository. 😁

Hope don't get me wrong with this message. Thanks for participating in the project!

**Comment by nachovoss** [comment]
Yes thanks Juan! I posted this before you released the people.thatopen platform. I found all the info there! Thanks for this awesome project!!

**Comment by agviegas** [comment]
I'm closing this! You can find the step-by-step tutorial to load IFC with the latest version of our libraries [here](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader). Let us know if you face any issues. Cheers!
