### ISSUE TITLE
The text of the Group Buttons overlaps each other..

### ISSUE THREAD

**Issue by albim0420** [ThatOpen/engine_components#120]
### Describe the bug 📝

I have 2 ContextMenu of group buttons: Hide/Show and Measurement (as shown below).
When I click the Measurement button, the buttons of the Hide/Show group do not hide. Make the text overlap as shown.
I hope the “openbim-components” library will update and resolve this bug!
Thanks so much!

![image](https://github.com/IFCjs/components/assets/63024634/049ba98d-4a9b-4b45-9474-64072c211649)

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
This will be worked on during the development of UI Components 2.0

**Comment by HoyosJuan** [comment]
We will release UIComponents 2.0 as a complete separate library and get rid of everything regarding UI from this repo. The new UIComponents are being done from scratch using a different technology.

Will close this issue as it won't be valid since release 1.6.0!
