### ISSUE TITLE
Walkthrough feature same with Naviswork 

### ISSUE THREAD

**Issue by albim0420** [ThatOpen/engine_components#123]
### Description 📝

I would expect the walkthrough feature to have the same weight as Naviswork and the one here:

1. http://yomotsu.github.io/meshwalk/examples/7_all-together.html
2. https://yomotsu.github.io/meshwalk/examples/5_terrain.html

I'm grateful to the authors of IFCjs and look forward to this feature coming soon to new versions of openbim-components

![image](https://github.com/IFCjs/components/assets/63024634/bf39ee0b-0661-4468-b055-ce7f900d0c02)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by shahbaziparisa** [comment]
> ### Description 📝
> I would expect the walkthrough feature to have the same weight as Naviswork and the one here:
> 
> 1. http://yomotsu.github.io/meshwalk/examples/7_all-together.html
> 2. https://yomotsu.github.io/meshwalk/examples/5_terrain.html
> 
> I'm grateful to the authors of IFCjs and look forward to this feature coming soon to new versions of openbim-components
> 
> ![image](https://private-user-images.githubusercontent.com/63024634/271293207-bf39ee0b-0661-4468-b055-ce7f900d0c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzUzMDQsIm5iZiI6MTcxMzg3NTAwNCwicGF0aCI6Ii82MzAyNDYzNC8yNzEyOTMyMDctYmYzOWVlMGItMDY2MS00NDY4LWIwNTUtY2U3ZjkwMGQwYzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MWZkODFlZjc5MmZlMDEzYTYzOGNjYTdhNGJmNDBlNDFhMDc1MDMyYjc3Y2ZlYmJlZTI1OGNjYjU1OTJiN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yu_fn6eRo2JdcqBeBkwGUI__QN5M1X44xVsFN7q-4ng)
> 
> ### Suggested solution 💡
> _No response_
> 
> ### Alternative ⛕
> _No response_
> 
> ### Additional context ☝️
> _No response_
> 
> ### Validations ✅
> * [x]  Read the [docs](https://platform.thatopen.com/documentation).
> * [x]  Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

Hi
Did you find anyway to add fps control openbim project?

**Comment by agviegas** [comment]
Hey, we are trying to keep the libraries small and scoped, so that we can effectively maintain and improve them over time. This is a neat idea, can be easily done with our APIs and we might make a tutorial for this. In the meantime, you can look for three.js generic tutorials, as in the end we are just creating THREE.js Meshes, so you should be able to easily set this up yourself. Cheers!
