### ISSUE TITLE
IFCDIRECTION is Missing in the 'model' Properties

### ISSUE THREAD

**Issue by DaikiFujiwara22** [ThatOpen/engine_components#124]
### Describe the bug 📝

"Upon inspecting the 'model' properties, 
I noticed that IFCDIRECTION is missing, making it impossible to retrieve.
 While the IFC file does contain IFCDIRECTION,
 it does not appear in the properties section when checked."
 
    const fragmentIfcLoader = new OBC.FragmentIfcLoader(this.components);
    fragmentIfcLoader.settings.wasm = {
        path     : 'https://unpkg.com/web-ifc@0.0.43/',
        absolute : true
    };

    const file = await fetch(url);
    const data = await file.arrayBuffer();
    const buffer = new Uint8Array(data);
    const group = await fragmentIfcLoader.load(buffer, '');
    console.log(group.properties);
![image](https://github.com/IFCjs/components/assets/112066769/a9948b99-d106-40e5-bc73-7a634b0ae5cc)

![image (1)](https://github.com/IFCjs/components/assets/112066769/75fd8ae4-38a7-442b-b638-740283b93521)

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.83 GB / 15.71 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @DaikiFujiwara22 by default the generated fragment properties exclude the IFC items regarding geometry. Otherwise, properties would be much, much bigger, thus consuming much more memory (which can be critical for bigger models or more modest devices). For the short term, we could expose a method to show the items that are excluded, and allow you to edit that list yourself. Would that work for you?

For the medium term, we are planning to create backend components, so that properties will be able to be stored in a database, and this won't be a problem anymore, as you will be able to store as much data as you want in a DB, and only load it in frontend when you need it.

**Comment by agviegas** [comment]
Closing this, as the library already provides methods to get any property of a specific IFC, both through the [core](https://github.com/ThatOpen/engine_web-ifc) and through this library. If you need to get the properties including geometry properties, you can easily make your own IFC-JSON converter using the code of our [JSON exporter component](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/ifc/IfcJsonExporter/index.ts) as a reference (if you copy it and remove [these lines](https://github.com/ThatOpen/engine_components/blob/471e8f2f189e098c7026c621d3bebd176cb01063/packages/core/src/ifc/IfcJsonExporter/index.ts#L61), it should include them). Cheers!
