### ISSUE TITLE
Ifc File Information

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#129]
### Description 📝

it would be nice to see the file information such as:
Model Name
Identificaiton
IFC File Description
IFC File Name
IFC File Schema

see the image below:
![image](https://github.com/IFCjs/components/assets/137836321/8daec939-5e53-484d-9c9e-39672f0cacd2)
![image](https://github.com/IFCjs/components/assets/137836321/984eedc4-762a-4896-8fdc-4a0e8dda76c4)
![image](https://github.com/IFCjs/components/assets/137836321/9fbae5ad-1927-41a3-8e1e-5d7801b2ca2b)
![image](https://github.com/IFCjs/components/assets/137836321/0019c644-258d-44f8-9c8a-587dfad79477)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hi there @ThatMetaverseArchitect!

At the time being, when you upload an IFC file with the FragmentIfcLoader and it gets the converted to a FragmentsGroups, that class [already contain the information](https://github.com/IFCjs/fragment/blob/main/src/fragments-group.ts#L16) you're asking for. The name is also present in the name property of the group. 

What other information do you feel is missing, so we can take a look at it!

**Comment by agviegas** [comment]
@HoyosJuan I think he's referring to having a UI element that shows that information about the projects loaded.

**Comment by agviegas** [comment]
Solved! A menu with this information can now be easily coded using our IFC APIs together with [UI Components](https://docs.thatopen.com/api/@thatopen/ui/). We also provide a [pre-made UI model list component](https://docs.thatopen.com/Tutorials/UserInterface/OBC/ModelsList) that you can use right out of the box, or as a reference to implement your own.

**Comment by ThatMetaverseArchitect** [comment]
Thank you for solving the request! it looks great!
