### ISSUE TITLE
Control of pickable elements

### ISSUE THREAD

**Issue by unclean-power** [ThatOpen/engine_components#132]
### Description 📝

I want the user to be able to pick only some elements in my model, but all must be available for picking by id. Non-pickable elements shouldn't be defined by the raycaster.

Using the web-ifc-viewer for this, I replaced the model with two subsets, assigned a special material to one of them and added it to `ifcViewer.context.items.pickableIfcModels`.

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @unclean-power sounds easy to implement! I could add a property in the highlighter where you can define the elements you want to pick (e.g. by category, by floor or by expressID). Would that make it for you?

**Comment by agviegas** [comment]
With the latest API, now this is very easy to solve. Just make sure that the elements you don't want to pick are not available in `world.meshes`. You can also set up your own picking events like shown in [the tutorial](https://docs.thatopen.com/Tutorials/Components/Core/Raycasters). Cheers!
