### ISSUE TITLE
Snapper component

### ISSUE THREAD

**Issue by LukasKStavario** [ThatOpen/engine_components#137]
### Description 📝

Is there any completed snapper component? I have read this and I am sure it is exists.
![image](https://github.com/IFCjs/components/assets/112091369/91d56bd3-7653-4ab6-b3fb-294dc08cad5b)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @LukasKStavario some components have their own snapping system (e.g. dimensions). What do you need to snapping for? We could perhaps create a generic snapping component to be used by other components.

**Comment by LukasKStavario** [comment]
> Hey @LukasKStavario some components have their own snapping system (e.g. dimensions). What do you need to snapping for? We could perhaps create a generic snapping component to be used by other components.

I need to specify point coordinates, I have own measurement function (but I will use yours in the future) and so on. Thank you for your answers guys!

**Comment by agviegas** [comment]
Now our library provides 2 vertex pickers: [one just for getting vertices](https://docs.thatopen.com/api/@thatopen/components/classes/VertexPicker), and another that [includes a graphic marker on top of the found vertices](https://docs.thatopen.com/api/@thatopen/components-front/classes/GraphicVertexPicker). Both are fully documented. We use them in the measurement components. Let us know if you have any other questions!
