### ISSUE TITLE
SimpleScene documentation is outdated

### ISSUE THREAD

**Issue by Maozerhouni** [ThatOpen/engine_components#141]
Hi,

Exploring the different tutorials, it seems it is non-compliant with what should be done.
For example, Simple scene tutorial : 
`
const container = document.getElementById('container');

const components = new OBC.Components();
components.scene = new OBC.SimpleScene(components);
components.renderer = new OBC.SimpleRenderer(components, container);
components.camera = new OBC.SimpleCamera(components);
components.raycaster = new OBC.SimpleRaycaster(components);`
Wouldn't be enough. Scene shall be initialised. Code should be more like : 
`
const viewer = new OBC.Components()

const sceneComponent = new OBC.SimpleScene(viewer)
sceneComponent.setup()
viewer.scene = sceneComponent

const viewerContainer = document.getElementById("app") as HTMLDivElement
const rendererComponent = new OBC.SimpleRenderer(viewer, viewerContainer)
viewer.renderer = rendererComponent

const cameraComponent = new OBC.SimpleCamera(viewer)
viewer.camera = cameraComponent

const raycasterComponent = new OBC.SimpleRaycaster(viewer)
viewer.raycaster = raycasterComponent
`

**Comment by daniel-augusto** [comment]
Hi @Maozerhouni , I replicated this issue in IFCjs/docs project and submitted a Pull Request to update documentation.

See a similar question registered at https://github.com/IFCjs/components/issues/121

And PR: https://github.com/IFCjs/docs/pull/13/commits/aab53e6d02e2c1454cf16ae964b88b581247a2db

**Comment by agviegas** [comment]
Thanks a lot for the help @daniel-augusto! Small notice: the tutorials are written in JavaScript because they are directly written in the HTML of the example where they are executed, so things like type assertions are not possible. But we'll update it right away!

**Comment by agviegas** [comment]
Fixed! You can check it [here](https://docs.thatopen.com/Tutorials/Components/Core/Worlds).
