### ISSUE TITLE
PostProductionRender outline effect shows up

### ISSUE THREAD

**Issue by MiguelG97** [ThatOpen/engine_components#142]
### Describe the bug 📝

Hi everyone,

the navigation floorplan works fine when using 2 viewports. Indeed, when a new planview is selected, the 3d view only displays the elements that belong to that storey. The issue comes when enabling postproduction renderer, the outline effect from other storeys shows up. Is there anything it can be done to not show up the outline effect while keeping the postproduction enabled?

components.renderer.postproduction.enabled = true;

regards

![image](https://github.com/IFCjs/components/assets/78984964/e1ae6802-c323-470f-9fe6-4a4179bee8da)

### Steps to reproduce 🔢

use the floor navigation tool in a 3D viewport. You gotta make sure to enable postproduction on this second viewport. Then you will realize of the outline effect

### System Info 💻

```shell
next js
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @MiguelG97 are you using the same renderer for both viewports, or one renderer per viewport?

**Comment by MiguelG97** [comment]
Indeed, im using the same render for both viewports

**Comment by agviegas** [comment]
Hey, now the library works with [worlds](https://docs.thatopen.com/Tutorials/Components/Core/Worlds). That means that you can create an app with 2 worlds that share the same Scene. That solves this problem, as each world would have their own renderer. Let us know if you have any questions. Cheers!
