### ISSUE TITLE
When I add a mesh with transparency to the scene, the transparent parts are displayed.

### ISSUE THREAD

**Issue by DaikiFujiwara22** [ThatOpen/engine_components#144]
### Describe the bug 📝

I created a mesh using the following method and added it to a simpleScene. 
The mesh has a texture with transparent parts. 
The transparent parts are displayed like glass.

```
const imagePath = './annotation.png';
const textureLoader = new THREE.TextureLoader();
const texture = textureLoader.load(imagePath);

const material = new THREE.MeshBasicMaterial({
  map         : texture,
  side        : THREE.DoubleSide,
  transparent : false,
  alphaTest   : 1,
  color       : new THREE.Color(255, 0, 0,)
});

const geometry = new THREE.PlaneGeometry(10, 10);
const plane = new THREE.Mesh(geometry, material);

this.components.scene.get().add(plane);
```
![image](https://github.com/IFCjs/components/assets/112066769/1c758b58-96f7-433d-9f8e-0beadad47852)

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.30 GB / 15.71 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.46)
    Internet Explorer: 11.0.19041.3570
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @DaikiFujiwara22,

I assume that happens due to the postproduction renderer processing that image plane. You can exclude meshes to be processed by the postproduction renderer like this:

```ts
postproduction.customEffects.excludedMeshes.push(mesh);
```

Does this solve your issue?

**Comment by DaikiFujiwara22** [comment]
Hi.
Thank you for your response. 
I tried the method you mentioned. 
However, excluding the mesh causes the post-production's edge lines to appear in the foreground. 
Is there a way to prevent the edge lines from appearing in the foreground?
![image](https://github.com/IFCjs/components/assets/112066769/9cecd7ea-6ac7-410c-9cb0-213efc7831e0)

**Comment by agviegas** [comment]
Hum 🤔 I'll take a look and see if there's a way to circumvent this.

**Comment by agviegas** [comment]
I checked and looks like there's no way to achieve this effect with the current implementation of the postproduction renderer. A caveat around this is to make sure your mesh adapts to the transparent parts of the texture. You can either do this manually, or achieve this automatically by computing the outline of your texture, and then creating a mesh that adapts to that outline. That way, you'll achieve the effect you are looking for!
