### ISSUE TITLE
Problem with properties finder submenu position when overflow

### ISSUE THREAD

**Issue by agviegas** [ThatOpen/engine_components#146]
### Describe the bug 📝

When there's overflow in the properties finder, the submenu is not in the right position:

![image](https://github.com/IFCjs/components/assets/56475338/09070060-c078-40bd-8b72-6efa652481b6)

### Steps to reproduce 🔢

a

### System Info 💻

```shell
Windows, chrome
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
This will be worked on during the development of UI Components 2.0

**Comment by HoyosJuan** [comment]
We will release UIComponents 2.0 as a separate library and get rid of everything regarding UI from this one. Also, the new UI is being done from scratch using a different technology.

Will close this issue as it won't be valid since release 1.6.0!
