### ISSUE TITLE
Picking colums in FloorPlans views

### ISSUE THREAD

**Issue by RASRC** [ThatOpen/engine_components#148]
### Describe the bug 📝

I'm working in the Floor Plan viewer, and noticed that you cannot pick columns, even when I added the category using the classifier like in the documentation
![c0nlons3yjtdp0x9gv59hmzyiafa](https://github.com/IFCjs/components/assets/117295504/fba0f513-2fd0-4b25-8fe2-edd012682331)
 I can't select column elements by clicking. Instead, it selects the slab.
Otherwise, I have no problems selecting any wall element by clicking.
![72nva7rh953pqge1307imnes4a09](https://github.com/IFCjs/components/assets/117295504/3200d360-6bb4-42c5-bbc8-0328901c032d)
![jsfhuxwgczwra8hk8st018u83s2f](https://github.com/IFCjs/components/assets/117295504/5ede92c3-387c-4ac8-a4de-356da7da3d2c)
Thanks!

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RASRC** [comment]
Hi @Maozerhouni! Thanks for the comment.

I understand your point but I can pick Walls without problems, wherever they are placed in the floorplan. In line with your explanation, they couldn't be pickable...

**Comment by Maozerhouni** [comment]
Oh ok. You're right. That s a bit odd. For the sake of experimentation, have you tried to tag walls as columns and vice versa ? I find it very weird that category Plays any role in this.

**Comment by agviegas** [comment]
Indeed, this is something we haven't implemented yet, but shouldn't be hard. I can bind the faces of the Edges Clipper to the IFC items to which they belong, thus enabling to pick clipped elements from above. I'll take care of it!

**Comment by RASRC** [comment]
Hi @agviegas ! Did you can implement the picking columns functionality for the Floor Plan viewer?
Thanks.

**Comment by agviegas** [comment]
Hi! Not yet, sorry 😳 we are 3 people maintaining the whole thing plus also making the new features. I expect that next month we will have time to clean up the issues in this respository. Feel free to open a PR if it's an urgent matter.Thanks in advance for your patience! 🙏

**Comment by agviegas** [comment]
Done! Now we can select clipped elements. Available from `@thatopen/components-front@2.0.15`. Docs also updated, you can try it out in the [plan tutorial example](https://docs.thatopen.com/Tutorials/Components/Front/Plans#-wrap-up). Cheers!
