### ISSUE TITLE
FragmentIfcLoader.load  fails with Aborted(). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by PDB6912** [ThatOpen/engine_components#156]
### Describe the bug 📝

I can successfully retrieve the specified IFC file from a compressed folder using jszip, and it displays correctly in web-ifc-three and web-ifc-viewer. However, it doesn't work in openbim-components

### System Info 💻

```shell
Windows 10
Chrome 118.0.5993.118
openbim-components 1.1.5
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

web-ifc.wasm:0x8abc Uncaught (in promise) RuntimeError: memory access out of bounds
    at web-ifc.wasm:0x8abc
    at web-ifc.wasm:0x2cf5b
    at web-ifc.wasm:0x9cdcb
    at web-ifc.wasm:0xaa56e
    at Object.OpenModel (eval at newFunc (web-ifc-api.js:6114:31), <anonymous>:9:10)
    at IfcAPI2.OpenModel (web-ifc-api.js:64646:34)
    at _FragmentIfcLoader.readIfcFile (index.ts:158:18)
    at async _FragmentIfcLoader.load (index.ts:77:5)

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ldv-orbyta** [comment]
Same issue here
