### ISSUE TITLE
When displaying edge lines without using PostProduction, the display appears distorted.

### ISSUE THREAD

**Issue by DaikiFujiwara22** [ThatOpen/engine_components#165]
### Describe the bug 📝

I want to display edge lines without using PostProduction. 
I have written the following code. 

```
const fragmentIfcLoader = new OBC.FragmentIfcLoader(this.components);
fragmentIfcLoader.settings.wasm = {
  path     : 'https://unpkg.com/web-ifc@0.0.43/',
  absolute : true
};

const file = await fetch(url);
const data = await file.arrayBuffer();
const buffer = new Uint8Array(data);
const group = await fragmentIfcLoader.load(buffer, '');

this.scene.get().add(group);
this.highlighter.update();

for (let index = 0;index < group.items.length;index++) {
  const edges = new THREE.EdgesGeometry(group.items[index].mesh.geometry);
  const line = new THREE.LineSegments(edges, new THREE.LineBasicMaterial({ color : 0x000000 }));
  this.scene.get().add(line);
}
```

However, it results in a display like the one shown in the diagram below. (image1)
The edge lines are not displayed for each mesh as they are when displayed in BimVision.(image2)
![image1](https://github.com/IFCjs/components/assets/112066769/1b12567f-8678-4c61-a472-7a899dcb0ece)
![image2](https://github.com/IFCjs/components/assets/112066769/7aa01751-e197-4cb7-b3e9-8b2219f1f3d6)
[IFC.zip](https://github.com/IFCjs/components/files/13262716/IFC.zip)

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.09 GB / 15.71 GB
Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.44)
    Internet Explorer: 11.0.19041.3570
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Three.js supports edges without postprocessing, so you don't need to rely on our library to do this. For instance, check [this thread](https://discourse.threejs.org/t/use-edgesgeometry-in-an-instancedmesh/16723/6). Cheers!
