### ISSUE TITLE
Contextmenu jumps to screen top left when used on toolbar

### ISSUE THREAD

**Issue by pylgrym** [ThatOpen/engine_components#171]
### Describe the bug 📝

I am doing:
  - I am activating context menu while mouse is over a toolbar, with right mouse.
What I expect is:
  - The menu to pop up near mouse cursor, as it does in other cases.
What is actually happening is:
  - Instead, the menu pops up on top left of screen.
  It is so far top left, that part appears outside screen (tooltip).
  
  I would not expect it to behave like this, but I don’t know if it is intended.
  The bug may be CSS related (a blank/naive claim, since CSS affects positioning of UI elements..)

### Steps to reproduce 🔢

If right mouse activates context menu while mouse is over a toolbar,
the context menu is placed in top left corner, instead of near mouse.

Normally, the context menu appears under your mouse cursor, when right menu button activates it. But if your mouse is over a toolbar, it instead is placed on top left of screen.
  It is so far top left, that part appears outside screen (tooltip).

I would not expect it to behave like this, but I don’t know if it is intended.
Screenshot included: (mouse was over bottom toolbar when right mouse was clicked.)

### System Info 💻

```shell
Current Firefox browser, on Windows 10.
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
This will be worked on during the development of UI Components 2.0

**Comment by agviegas** [comment]
This is solved with the [new UI components library](https://github.com/ThatOpen/engine_ui-components). Let us know otherwise!
