### ISSUE TITLE
Source maps reference non-existent .ts files

### ISSUE THREAD

**Issue by StrandedKitty** [ThatOpen/engine_components#196]
### Describe the bug 📝

It seems like package building is broken, all .js.map files that are present in the package reference non-existent .ts files.

For example, see the screenshot below. `base-raycaster.js` has a source map `base-raycaster.js.map` which references `base-raycaster.ts`, but `base-raycaster.ts` is not present in the package at all.

![image](https://github.com/IFCjs/components/assets/48140945/81f8cda0-7917-4aba-b220-ecd6e4b9e753)

This issue leads to errors when using `source-map-loader` with Webpack in our project. Here's an example of such an error caused by broken source maps:

```
WARNING in ./node_modules/openbim-components/src/navigation/ShadowDropper/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/***/Projects/Shadowmap/node_modules/src/navigation/ShadowDropper/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/***/Projects/Shadowmap/node_modules/src/navigation/ShadowDropper/index.ts'
 @ ./node_modules/openbim-components/src/navigation/index.js 4:0-32 4:0-32
 @ ./node_modules/openbim-components/src/index.js 6:0-29 6:0-29
 @ ./src/js/main.ts 65:0-42 66:12-15
 ```

This issue is present in `openbim-components`, `openbim-clay`, and `bim-fragment` packages, I'm not going to duplicate it though.

To fix it you need to either disable source maps or fix them (make them inlined or add .ts files to the package). One option is to add `sourcemap: "inline"` to your `rollup.config.mjs`, see https://rollupjs.org/configuration-options/#output-sourcemap.

### System Info 💻

```shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 157.63 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    bun: 1.0.7 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Chrome Canary: 121.0.6155.0
    Safari: 17.1
  npmPackages:
    openbim-components: ^1.1.7 => 1.1.7
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This should be solved. Now we are bundling all our libraries, and it looks like this: 

![image](https://github.com/ThatOpen/engine_components/assets/56475338/337dfe1b-5c0e-47fb-b8d4-0a1af110860e)

If you are still facing issues with the latest version, let us know!
