### ISSUE TITLE
SimpleClipper component improvements

### ISSUE THREAD

**Issue by TristanLecallier** [ThatOpen/engine_components#203]
### Description 📝

Hi !

- Currently once one or several planes have been created using EdgesClipper (or SimpleClipper) component, by disabling the component with a custom button, planes already created are desactivated.
(this seems to be treated in https://github.com/IFCjs/components/issues/130#issuecomment-1836448032 issue)
- Currently, it is not possible to delete a plane when EdgeClipper is disabled : "delete" method of SimpleClipper component return "undefined" when disabled. (https://github.com/IFCjs/components/blob/a8472b228f955fd03a9c1e16d05d46106f496466/src/core/SimpleClipper/index.ts#L216)
- Consequently, if I want to delete all planes (with "deleteAll" method) when EdgeClipper is disabled, I get in an infinite loop (https://github.com/IFCjs/components/blob/a8472b228f955fd03a9c1e16d05d46106f496466/src/core/SimpleClipper/index.ts#L228).

### Suggested solution 💡

- When disabling the component, let the possibility to keep activated existing planes
- Let the possibility to delete an existing plane when the component is disabled

### Validations ✅

- [X] Read the [docs](https://platform.thatopen.com/documentation).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey Tristan!

You are right about the deletion logic. Fixed it.

As for the other problem, I think that the problem right now is that the `enabled` flag is doing 2 different things:

- It sets the `enabled` state of all planes.
- It allows to create/delete planes.

If we have to choose between using one or another, I'd say it makes more sense to stick with the first one for 2 reasons: 

- This way, we are consistent with the `visible` property, which sets the `visible` state of all planes. 
- It's easier to prevent creating/deleting planes if the component is not visible, than setting the global state of all planes. You just need to do the following:

```ts
    if (clipper.enabled) {
      clipper.delete(world);
    }
    
    if (clipper.enabled) {
      clipper.create(world);
    }
```

I'm implementing the first option. All this is available from version `@thatopen/components@2.0.15`, and the docs are also updated. Let me know if you encounter any issues. Cheers!
