### ISSUE TITLE
FragmentGroup.uuid should not be tied to projectGuid

### ISSUE THREAD

**Issue by vulevukusej** [ThatOpen/engine_components#209]
### Describe the bug 📝

It's common in larger projects to split up a project into smaller, seperate files.  These file all have the same IfcProject and thus the same projectGuid.  This causes an issue in components, since it seems the fragmentGroup uuid is taken from the project guid.

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @vulevukusej,

You're totally right! It was a decision we made at the time to set the IfcProject GUID as the FragmentsGroup.uuid without taking into account the splitting of one authoring model into several IFC files (in fact, I do it quite often).

Sadly, at the time being the IFC schema doesn't come with a GUID to identify the model as seen in https://github.com/buildingSMART/NextGen-IFC/issues/67. We basically had two options: 

1. Generate a GUID completely decoupled from the IFC file.
2. Use the GUID from some root level entity. We choose IfcProject.

Being that said, you think we should stick to the first option? It will surely help avoid issues in many of the library tools that identify the model using FragmentsGroup.uuid. Also, do you have any other suggestion for this?

Thank you so much!

**Comment by vulevukusej** [comment]
Hey @HoyosJuan - I'm not sure what the purpose of the FragmentsGroup.uuid is other than to uniquely identify amongst other fragments?  In that case, why do we need more complexity than the filename itself?  I modified the code to make the uuid = filename and I've found it to work perfectly.  If a user try's to import a model with the same filename this is rejected and the user is appropriately informed.  An IfcProject refers to the project conceptually and not the file which is why a guid there makes much more sense to me.  In any case, just my 2 cents :)

**Comment by NiklasPor** [comment]
I think it'd be nice if the UUID of the fragment group could be stable, when the same ifc file is opened again later. Currently we're using expressId + fragmentGroup.uuid to uniquely identify elements inside models. (For example to save selections and restore them later when the model is opened again). How could one achieve that, when the fragment group id would be dynamically generated?

**Comment by vulevukusej** [comment]
@NiklasPor why not just use the object guid from IFC for that?

**Comment by NiklasPor** [comment]
Actually a good idea. I'd just have to build up a Map when a new model is loaded, which maps the element guids to the data we currently fetch with expressId + fragmentGroup.uuid 👍

**Comment by vulevukusej** [comment]
@NiklasPor why not just use the object guid from IFC for that?yup that's what I do 👌

**Comment by agviegas** [comment]
In the latest versions we have decoupled the FragmentsGroup uuid from the project guid, so I'm closing this!
