### ISSUE TITLE
Big IFC civil files: TIETAR2-V1-Nat.ifc

### ISSUE THREAD

**Issue by ignaciogutierrezperez** [ThatOpen/engine_components#219]
We have found some problems when trying to upload the file TIETAR2-V1-Nat.ifc, already shared with @agviegas in a private message, in the right coordinates using the latest version of the app.

Please, review and provide with some feedback.

Thanks.

**Comment by agviegas** [comment]
With the latest version of our [streaming technology](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer), this model loads in under 1 second:

https://github.com/ThatOpen/engine_components/assets/56475338/2347f35e-0f7e-41bf-945b-0348c2140477
