### ISSUE TITLE
Extract source and target coordinate system

### ISSUE THREAD

**Issue by muta93srb** [ThatOpen/engine_components#223]
### Description 📝

I am creating web app for my final exam, and I need to extract source and target coordinate systems from IFC (IFCMAPCONVERSION, IFCPROJECTEDCRS, IFCGEOMETRICREPRESENTATIONCONTEXT) to do some geodesy stuff and try to translate all coordinates to their target values, is it possible to do it using this library?

### Suggested solution 💡

I am willing to put some work into it with guidance on what and where from maintainer.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
I think it's not possible for now, and have no plans to implement it! If you have other questions about our current APIs, please let us know. Cheers
