### ISSUE TITLE
Support for non-fullscreen canvas apps

### ISSUE THREAD

**Issue by NiklasPor** [ThatOpen/engine_components#227]
### Description 📝

I'm using openbim-components in a non-full-screen application (with HTML elements to the side) and many components break from this usage, because they refer to the window size for rendering, not to the canvas size.

### Suggested solution 💡

The fix for this is quite simple, in most cases replacing `window.innerHeight` with `canvas.clientHeight` and `window.innerWidth` with `canvas.innerHeight` does the trick. I'd be very happy to contribute these changes, if they're wanted.

Example fix for the simple camera. Current code:
https://github.com/IFCjs/components/blob/1e2695e38b07885d7168f83382e027189c5f6e56/src/core/SimpleCamera/index.ts#L103

Updated:
```ts
    const aspect = window.innerWidth / window.innerHeight;
```

### Additional context ☝️

FYI This is not a problem inside the documentation, because every viewer is a fullscreen iFrame there.

I already copy pasted many components into our project and edited them, to fix the issues. I'd be very happy to contribute back 👋 

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey Niklas! This can be done without any changes to the library. Take a look at the following screenshot:

![image](https://github.com/IFCjs/components/assets/84806689/b395d3a8-45bd-4865-be34-2c6fbcb5e011)

The only thing is you need to call `camera.updateAspect()` after the viewer has been initialized. Also, if you want to change the viewer size because your entire layout changes, you can use ResizeObserver for that. This is how I do it:

```ts
  const resizeObserver = new ResizeObserver(() => {
    viewer.renderer.resize()
    const camera = viewer.camera
    if (!(camera instanceof OBC.OrthoPerspectiveCamera)) {return}
    camera.updateAspect()
  })
  resizeObserver.observe(viewerContainer)
```

**Comment by NiklasPor** [comment]
Sure, that'll work and fix the issue I'm describing (I've got a working setup anyway). I'm more talking about the general scope in the library – is there any reason for keeping the window reference in the camera and in postproduction, if all of the update methods already refer to the canvas sizes?

**Comment by agviegas** [comment]
In the latest version this should be solved! Let us know otherwise. Cheers!
