### ISSUE TITLE
Shadows combined with postproduction custom effects show the shaded plane

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_components#231]
### Describe the bug 📝

This effect is shown on screen 1.
The reason is the shadow plane, I solved it this way(screen2), but maybe it should be solved better - automatically when turning on shadows in connection with postproduction.

![image](https://github.com/IFCjs/components/assets/87365468/61cb464f-3735-4c50-927f-b94e001960bd)
![image](https://github.com/IFCjs/components/assets/87365468/878b19e7-11a2-4c8d-9732-ce729d4db982)

### Steps to reproduce 🔢

1. Activate postproduction
   components.renderer.postproduction.enabled = true;
    components.renderer.postproduction.customEffects.outlineEnabled = true;
    components.renderer.postproduction.customEffects.glossEnabled = true;
    const postproduction = components.renderer.postproduction;
2. Render shadow

### System Info 💻

```shell
"openbim-components": "1.2.0"
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
You can solve this by excluding the shaded plane of the shadows from the postproduction, like we do [here](https://docs.thatopen.com/Tutorials/Components/Front/PostproductionRenderer#-turning-on-the-postproduction) with the grid. Cheers!
