### ISSUE TITLE
[FragmentIfcLoader] settings included categories

### ISSUE THREAD

**Issue by edgar-g-q** [ThatOpen/engine_components#232]
### Description 📝

Right now, FragmentIfcLoader settings allow you to set some "excludedCategories", for instance WEBIFC.IFCSPACE, WEBIFC.IFCFURNISHINGELEMENT, etc.
Would it be possible to have "includedCategories", so that only the given categories are included, and the rest are excluded?

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Miso-K** [comment]
+1 for this feature

**Comment by ajay-toobler** [comment]
This feature would be helpful. It would be great if we could load some groups of expressIDs as well.
