### ISSUE TITLE
Wrong y points of fragment plans when ifc length unit is in centimeters (too high)

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_components#233]
### Describe the bug 📝

I have some ifc projects in CENTI units (screen 2). I think this was not included in the algorithm in the IfcPropertiesUtils class in the getUnits method - there are METER and MILLI and missing CENTI and DECI

![image](https://github.com/IFCjs/components/assets/87365468/355527cf-bd80-4132-9626-307ba8e233b1)
![image](https://github.com/IFCjs/components/assets/87365468/6f577450-145e-4cd9-b7d5-a02c049315ef)
![image](https://github.com/IFCjs/components/assets/87365468/e8e12a22-7b6f-4b7b-8994-118d4a52b68c)

### Steps to reproduce 🔢

1. Load ifc with CENTI length units
2. Generate fragment plans

### System Info 💻

```shell
"openbim-components": "1.2.0"
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Solved from `2.0.23`. Let us know otherwise. Cheers!

![image](https://github.com/ThatOpen/engine_components/assets/56475338/7c86bfe0-156e-4956-b5e2-2acc1c0a80e2)
