### ISSUE TITLE
EdgesClipper and FragmentBoundingBox doesn't include fragments.baseCoordinationModel

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_components#234]
### Describe the bug 📝

Maybe I'm doing something wrong, but when I load two models offset from each other, I use the following code to make them fit relative to each other:
if (fragments.groups.length === 1) {//first
        fragments.baseCoordinationModel = model.uuid;
    } else if (fragments.groups.length > 1) {//next models
        fragments.coordinate([model]);
And this is ok, two models are in good place. 
But when I use styles to clipper, 
 const clipper = await components.tools.get(OBC.EdgesClipper);
 const styles = clipper.styles.get();
(and after that I add here all fragment meshes in loop)
... styles.projected.meshes.add(fragment.mesh);

some clipper edges are generated where the second model would be without the "fragments.coordinate([model]);", but the othrs seems to be in correct place:
![image](https://github.com/IFCjs/components/assets/87365468/1fd90a4f-43f1-4830-b5df-97d6b6bc6a4d)

models loaded without coordination - clipper edges are ok:
![image](https://github.com/IFCjs/components/assets/87365468/22d07d2c-c15a-483e-99da-d4000719ab3b)

The same problem I think is with a FragmentBoundingBox and a FragmentPlans

### Steps to reproduce 🔢

Described in the bug description

### System Info 💻

```shell
"openbim-components": "1.2.0"
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed in the latest version! Let us know otherwise
