### ISSUE TITLE
Lifecycle events on IFC loading

### ISSUE THREAD

**Issue by HoyosJuan** [ThatOpen/engine_components#240]
### Description 📝

As the title says, would be nice to add some lifecycle events in each important step of the IFC loading through the FragmentIfcLoader. Some events may involve:

- onBeforeLoading
- onFileRead
- onLocationsSaved (existing)
- onModelCreated
- onIfcLoaded

Better names could be assigned.

### Suggested solution 💡

Create the corresponding events in `FragmentIfcLoader.load`.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
I think this is partly solved, and it should be enough for the current state of the library. Closing this!
