### ISSUE TITLE
Collision detect between ifc elements

### ISSUE THREAD

**Issue by joselazcanor** [ThatOpen/engine_components#245]
### Description 📝

I'm looking for a tool to detect all the collisions present on the model like on Bim Collab.

Model without filter:
![image](https://github.com/IFCjs/components/assets/87159946/9550dff2-e2c5-41c3-977b-0c29feeb9721)

Model with filter:
![image](https://github.com/IFCjs/components/assets/87159946/665f3a94-d44e-4326-9764-eb2904e80f0f)

### Suggested solution 💡

Actually i use Mesh.geometry.boundsTree.intersectsGeometry to check if a object is colliding with another, but only works comparing the meshes 1 by 1
```javascript
const elementBase = parseInt(ifcItem.id);
const sub1 = getSubsetDataFromId(elementBase);
sub1.geometry.computeBoundsTree();

const sub2 = getSubsetDataFromIds(elementosIds);
const sub2Geometry = mesh2.geometry;
sub2Geometry.computeBoundsTree();

const transformMatrix = new Matrix4().copy(mesh1.matrixWorld).invert().multiply(mesh2.matrixWorld);
const hit = mesh1.geometry.boundsTree.intersectsGeometry(mesh2Geometry, transformMatrix);
``` 

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey, you should check this out with Garret, as he is the author of the [BVH library](https://github.com/gkjohnson). We are not planning to implement clash detection features in our library for now (although you can do it yourself using Garret's and Three's APIs), so this issue is out of our scope. Cheers!
