### ISSUE TITLE
Ifc Import floor plan navigation export to dxf

### ISSUE THREAD

**Issue by Isaina** [ThatOpen/engine_components#249]
### Description 📝

Hi is there example how to import ifc (not in 3d),and navigation floors in 2d and show 2d in svg and export to dxf

### Suggested solution 💡

Write few examples

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey, there's not an example, as far as I know. We are trying to keep the scope of the library small, as we are a small team and we are trying to keep it maintainable. We have no plans to implement an API inside the library for this for now. Cheers!
