### ISSUE TITLE
Multi-thread (multi-worker for ifcparser)

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#259]
### Description 📝

Usually when we parse a model, the process will take place in 2 parts, one is the geometry parser and the property parser (like link https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcLoader/index.ts#L135-L141 , line 135 and line 141). That means the time to parser is the total time of those two processes. Now I try a solution: these two processes take place in parallel, when one of the two processes ends, we use threejs to generate geometry. Let's say the geometry parser takes 80s, and the property parser takes 60s, so the total time is 140s. Now we divide it into 2 parallel processes, it only takes us 80 seconds.

### Suggested solution 💡

To speed up the process and prevent the browser from crashing I use workers. I created 2 workers. 1 are IfcGeometryWorker and IfcPropertyWorker. You can test to see the results. Below is the repo I use. https://github.com/RyugaRyuzaki/multi-worker_openbim-components.I know this method has been used in the past, but as @agviegas explains, it will take longer to load on the website, because a worker file can be up to 5MB.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by RyugaRyuzaki** [comment]
Yes I saw it, and of course we can use multiple threads in server side.

**Comment by agviegas** [comment]
We are not planning to implement multithreading for now, as the current streaming features already solve scalability issues for big models, and we don't have technical capacity to investigate multithreading now. Closing this!
