### ISSUE TITLE
FragmentHider with FragmentClassifier.byModel ignore certain elements

### ISSUE THREAD

**Issue by Manriss** [ThatOpen/engine_components#261]
### Describe the bug 📝

If the model is classified using the FragmentClassifier.byModel() method, and an attempt is made to hide the entire model through FragmentHider.Set() using the resulting classification, certain elements are ignored.
this code is executed after the model is classified:
```        
     const hider=viewer.tools.get(OBC.FragmentHider)
         for (const model in classifier.get()['model']){
            const modelFragmentsFromClassifier=classifier.get()['model'][model]
            console.log(modelFragmentsFromClassifier)
            hider.set(false,modelFragmentsFromClassifier)
           // hider.set(false) //this works ok
         }
```

elements ignored:
![image](https://github.com/IFCjs/components/assets/75563153/80965275-b213-4cf3-aa01-1b5b7d68ce36)
It looks like Fragments from model and classifier are different:
From the FragmentGroup:
![image](https://github.com/IFCjs/components/assets/75563153/3c600a50-c062-4d7c-886e-e200502538e8)
From classifier:
![image](https://github.com/IFCjs/components/assets/75563153/db6c79a4-18d8-423f-b8d7-3f37df4ebaad)
the IFC file is the one named: 
NAV-IPI-ET1_E07-ZZZ-M3D-EST.ifc from the master BIM software developer
If I try to hide one of those elements using the id from the highligther event nothing happens:

```
highlighter.events.select.onHighlight.add((fragmentMap) => {
          const expID = [...Object.values(fragmentMap)[0]][0];
          const hider=viewer.tools.get(OBC.FragmentHider)
         const selectedFragmentMap= model.getFragmentMap([Number(expID)])
         const selectedFragmentIdMap=map2IDMap(selectedFragmentMap)
       // hider.isolate(selectedFragmentIdMap) //This works OK
         hider.set(false,selectedFragmentIdMap)
        });
        highlighter.events.select.onClear.add(() => {
          setSelectedProperties(null)
        })
      } catch (error) {
        console.warn(error);
      }
    }
```

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12850HX
    Memory: 45.93 GB / 63.69 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    openbim-components: 1.2.0 => 1.2.0
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This should be solved with the latest version of the library. let us know otherwise!
