### ISSUE TITLE
Consider alternative use cases

### ISSUE THREAD

**Issue by janruo** [ThatOpen/engine_components#264]
### Description 📝

This library seems to be very focused on making an opinionated 3D viewer application with a UI, camera controls, render loop, etc. Everything is already included and bundled together with an easy-to-use API, *if that's exactly what you want to build*.

However, if that's *not exactly* what you want to build, things get a bit complicated.

For example, consider the following use case:
- I need to load IFC files into ThreeJS models and export/import fragments
- I need to render the models to a canvas
   - Just a static image with no animation loop at all
   - I need to programmatically control when the canvas is re-rendered, by calling `renderer.render()`
- I don't need any UI
- I don't need any user camera controls

One would think that due to the modular nature of this library, one could easily just use the `FragmentIfcLoader` component to achieve the loading part, ignore most other components of this library and handle the rest manually. However:
- `FragmentIfcLoader` (and all other components) depend on the `Components` class
   - The `Components` class has a hard-coded render loop
   - The `Components` class requires a scene, camera and a renderer (which is understandable, to be fair)
      - But the default `SimpleCamera` has a hard-coded dependency on `CameraControls`
   - The `Components` class requires a raycaster, which is weird because that shouldn't be essential
      - The raycaster can be left uninitialized, but then [dispose will throw](https://github.com/IFCjs/components/blob/5bff295d3aecedcdcdac76b651c0cc1f3bd91d37/src/core/Components/index.ts#L194)
   - The `Components` class has a hard-coded dependency on `UIManager`, which is weird because that shouldn't be essential
      - UI can be [disabled](https://github.com/IFCjs/components/blob/5bff295d3aecedcdcdac76b651c0cc1f3bd91d37/src/core/Components/index.ts#L151-L154), but then [dispose will throw](https://github.com/IFCjs/components/blob/5bff295d3aecedcdcdac76b651c0cc1f3bd91d37/src/core/Components/index.ts#L178)

So basically I have write some hacky code to undo things in this library:

```ts
const nothing = document.createElement("div");

export class NullUIManager extends UIManager {

    override enabled = false;

    override get viewerContainer() {
        return nothing;
    }
}

export class MyComponents extends Components {

    private _nullUI: NullUIManager;

    override uiEnabled = false;

    constructor() {
        super();
        this._nullUI = new NullUIManager(this);
    }

    override get ui(): UIManager {
        return this._nullUI;
    }

    override async init() {
        // Don't init
    }
}

export class MyCamera extends Component<OrthographicCamera> implements Disposable {

    override enabled = true;

    readonly onDisposed = new Event<undefined>();

    private camera: OrthographicCamera;

    constructor(components: Components) {
        super(components);
        this.camera = new OrthographicCamera();
    }

    override get = () => {
        return this.camera;
    };

    dispose = async () => {
        this.camera.removeFromParent();
        await this.onDisposed.trigger();
        this.onDisposed.reset();
    };
}
```

And only then I can load IFCs and control the scene, camera and renderer manually without this library interfering with that. And whenever I decide to update this library, I have to check the source code to see whether my hacks are still valid.

### Suggested solution 💡

Please consider making less assumptions about the types of applications devs want to write, so that they don't have to actively fight against the library to create something the authors didn't necessarily think of.

It's good to include helpful defaults, but making them mandatory or difficult to overwrite can be counter-productive in many cases.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by vulevukusej** [comment]
Great issue @janruo - I also find myself doing the same. Allowing the library to be use-case agnostic would be a real quality-of-life improvement.  Having said that, I think the "batteries included" approach has its merits. Perhaps two repos?

**Comment by lcorreiaIC** [comment]
Well... @janruo your comment basically **exactly** sums up my experience as well.
The library is really powerful and I'm very happy using it, the performance has shocked me! It's good.
However, I have two use cases, one were the user interacts with the model, does measurements etc. and for that I am using "components" to its fullest extent. But my second use case has little interaction in 3D but more with other information on the page, so react three fiber is a better fit, and the way this library is built atm forces me to reverse engineer everything to get it to work in "not so good" react ways.
A simple ifc loader function decoupled from all the "components" class and so on would greatly simplify this.

**Comment by janruo** [comment]
Closing this issue, seems like most of the problems have been resolved in the current version

- UI is no longer forcibly baked into everything
- No need to neuter the `Components` class any more
- A renderer component is no longer mandatory
- A raycaster component is no longer mandatory
- Easier to replace the `Simple...` classes with custom ones using the `Base...` classes

Awesome, thank you 👍
