### ISSUE TITLE
1.3.1 (patch) release included breaking changes (auto-injecting css)

### ISSUE THREAD

**Issue by NiklasPor** [ThatOpen/engine_components#274]
### Describe the bug 📝

Hey all, the 1.3.1 patch version (marked as latest) included a breaking change, which should not be the case, as it's just minor not a major release.

This is the release commit, which is title `1.3.0` but the npm package version is `1.3.1`: https://github.com/IFCjs/components/commit/5bff295d3aecedcdcdac76b651c0cc1f3bd91d37

The auto-inject of styles broke our app, by simply applying global styles automatically (we had manual stylings which were scoped before). For example all scroll bars in our app now look purple.

This is the PR which added the auto-injection of styles (which is a good idea, although it should be toggleable): https://github.com/IFCjs/components/pull/218

But this should not happen during a **patch** release, as those are expected to be only bugfixes and not any major changes which requires migration by the consumers of the packages.

I'd vote to revert those changes and wait for the next major release. Until the major release we can make the styles injectable by calling a method explicitly (like `injectStyles`). Then, with the next major release, inject them as a default and make it possible to disable that behaviour.

### System Info 💻

```shell
System:
    OS: macOS 14.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 92.34 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/Library/pnpm/node
    npm: 10.2.3 - ~/Library/pnpm/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.1
  npmPackages:
    openbim-components: 1.3.1 => 1.3.1 
```
```


### Used Package Manager 📦

pnpm

### Error Trace/Logs 📃

_No response_

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by janruo** [comment]
Not only is the library casually polluting global `:root`, `*`, `::before`, `::after`, `html`, `.container`, scrollbars etc, but the way the stylesheet is loaded is also pretty crazy:

```ts
    const fetchResponse = await fetch(
      "https://raw.githubusercontent.com/IFCjs/components/main/resources/styles.css"
    );
```

So `resources/styles.css` can never be renamed or deleted from the repository, or existing installations will suddenly just lose their styles. Also good luck trying to even maintain that file when all changes to it will also affect previous versions 👍

**Comment by HoyosJuan** [comment]
Hi @NiklasPor!

Are you using the built-in UI from components?

**Comment by NiklasPor** [comment]
Actually not, but some components throw errors if the UI isn't enabled, so I still have it enabled (but I'm not rendering anything with components).

**Comment by NiklasPor** [comment]
Awesome, all of this sounds good. I'd obviously disagree on the breaking change part, as the update broke the styles of our app.

For the uiEnabled issue, acrtually I don't have it anymore. Might've been in an older version (I didn't check if this still appears every upgrade).

Thanks for all the hard work 👏

**Comment by NiklasPor** [comment]
@HoyosJuan actually I still get one error when I disable the ui, the `components.dispose()` call throws:
![image](https://github.com/IFCjs/components/assets/13211347/8dfc055a-ee1c-4a0c-a429-f602dc766835)

Should I open a separate issue?

**Comment by cytostatic** [comment]
I have another suggestion to the auto injected styles. It would be nice to have the compiled styles and also the "Material Icons" font in the npm package to load it manually. Loading google fonts from their website is especially in the EU kind of critical because of GDPR.

**Comment by agviegas** [comment]
The auto-injected CSS issue should be solved in the latest version of the libraries, as we have decoupled all the UI-related logic to [a separate library](https://github.com/ThatOpen/engine_ui-components). As for the breaking changes - sorry. We are a small team advancing fast, but from now on, all patch versions should be non-breaking. If that's not the case in the future, let us know! Cheers
