### ISSUE TITLE
Build in angular is failing

### ISSUE THREAD

**Issue by armadinho** [ThatOpen/engine_components#276]
### Describe the bug 📝

I am using the components in angular 14.2.0 with typescript 4.7.2 and I cannot build the app.

The error i get is in 2 files:
1. In file node_modules\openbim-components\src\navigation\PostproductionRenderer\src\postproduction.d.ts

Error: node_modules/openbim-components/src/navigation/PostproductionRenderer/src/postproduction.d.ts:15:39 - error TS2344: Type 'Event<string, unknown>' does not satisfy the constraint 'Object3DEventMap'.
  Type 'Event<string, unknown>' is missing the following properties from type 'Object3DEventMap': added, removed

15     excludedItems: Set<THREE.Object3D<THREE.Event>>;

2. In file node_modules\openbim-components\src\core\SimpleRaycaster\index.d.ts

Error: node_modules/openbim-components/src/core/SimpleRaycaster/index.d.ts:33:216 - error TS2344: Type 'Event<string, unknown>' does not satisfy the constraint 'Object3DEventMap'.
  Type 'Event<string, unknown>' is missing the following properties from type 'Object3DEventMap': added, removed

33     castRayFromVector(origin: THREE.Vector3, direction: THREE.Vector3, items?: THREE.Mesh<THREE.BufferGeometry<THREE.NormalBufferAttributes>, THREE.Material | THREE.Material[]>[]): THREE.Intersection<THREE.Object3D<THREE.Event>> | null;

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
    Memory: 18.18 GB / 31.89 GB
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    openbim-components: ^1.3.1 => 1.3.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Which version of three and @types/three are you using?

**Comment by HoyosJuan** [comment]
Hi @armadinho! Following up this issue, were you able to solve it?

**Comment by agviegas** [comment]
This should be solved with the latest version of the libraries. Closing this!
