### ISSUE TITLE
Unable to init the FragmentTree without the UIManager

### ISSUE THREAD

**Issue by tb-viktor** [ThatOpen/engine_components#278]
### Describe the bug 📝

Hi,

I'm working on a custom implementation of the FragmentTree that would use external UI components to render a nested list. I have `components.uiEnabled = false` declared to not render the library UI, and would like to access the FragmentTree (hopefully) in an object format to render it myself using the `.get()` method.

I am running into an error where it is still trying to access the `UIManager` when running `.init()`:

![image](https://github.com/IFCjs/components/assets/96176911/7b04ef3e-b1e6-4d88-910d-1a471ea60491)

I have a feeling it is a bug, because in the source code I see that it should skip this part if the UI is disabled, but it doesn't seem to.

Any ideas?

### Steps to reproduce 🔢
```
newComponents.uiEnabled = false;

...

const classifier = new OBC.FragmentClassifier(newComponents);
classifier.byStorey(model);
classifier.byEntity(model);

const modelTree = new OBC.FragmentTree(newComponents);
modelTree.init();
modelTree.update(['storeys', 'entities']);
```
### System Info 💻

```shell
Binaries:
    Node: 20.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    openbim-components: ^1.3.2 => 1.3.2
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nicoarellano** [comment]
I have the same issue

**Comment by tb-viktor** [comment]
@HoyosJuan any updates on this particular issue? 🙂 it would be nice if we could build our own object tree separate from the library UI.

**Comment by HoyosJuan** [comment]
Hey @tb-viktor!

We're working on UIComponents 2.0. Basically, we will get rid of everything about UIComponents from this repo and going to create a dedicated one, using a much simpler approach than the one use here. That should make things easier. 

My point is, we're focused on creating those new components and not so in solving existing UI problems, because all of them are going to be gone when UIComponents 2.0 launches. According to the [roadmap](https://people.thatopen.com/c/roadmap/), that's going to happen in may.

Is it ok for you? 🙏

**Comment by tb-viktor** [comment]
> Hey @tb-viktor!
> 
> We're working on UIComponents 2.0. Basically, we will get rid of everything about UIComponents from this repo and going to create a dedicated one, using a much simpler approach than the one use here. That should make things easier.
> 
> My point is, we're focused on creating those new components and not so in solving existing UI problems, because all of them are going to be gone when UIComponents 2.0 launches. According to the [roadmap](https://people.thatopen.com/c/roadmap/), that's going to happen in may.
> 
> Is it ok for you? 🙏

I think you are making the right decision by decoupling these two things 👍

For our use-case it would really help us if after the split this project had convenient functions to get resolved object properties (and sub-object via `expressId`) and an easy way to work with the object tree without having to traverse the IFC file ourself. This code already exists internally in the library since you use it for the pre-built UI, but it's quite an effort to get to the end result to plug it into our own UI.

**Comment by HoyosJuan** [comment]
@tb-viktor agree! We're always on making things easier to work. For example, we hope in the next release to decouple core logic with visual logic, so components can be used in backend 🙂

Do you mind opening a feature issue about the request you mentioned? In case it doesn't exist already, of course. I will close this!
