### ISSUE TITLE
Import export dotbim

### ISSUE THREAD

**Issue by Isaina** [ThatOpen/engine_components#290]
### Description 📝

There is Import for web ifc in js for dot bim but not export (usdz to ifc workflow)

### Suggested solution 💡

Import export implementation in web ifc and JavaScript dot bim file format https://dotbim.net/

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by RyugaRyuzaki** [comment]
@Isaina you can check this https://github.com/RyugaRyuzaki/DotBimConvert/tree/main/Ifc

**Comment by agviegas** [comment]
We are trying to keep the scope of the library as small as possible to be able to maintain it and keep improving it with our small team. We are turning this off for now, but you are free to write your own importer / exporter and show it around in the community! Cheers
