### ISSUE TITLE
Areameasurement class throws a bug if activated before adding second point

### ISSUE THREAD

**Issue by Adeniyi-Bella** [ThatOpen/engine_components#292]
### Describe the bug 📝

There could be a bug when using the AreaMeasurement class. When a user selects the first point and in the process of adding the second point, the user presses the enter keypad. You get what is in the picture below. So the logic works only after the second point has been added. Before that, it throws this error and you get this behavior as shown in the picture. 

![image](https://github.com/IFCjs/components/assets/37347588/4cecab16-e5b6-463b-9e3c-4170dba78104)

### Steps to reproduce 🔢

1. go to this link https://docs.thatopen.com/Tutorials/AreaMeasurement
2. Scroll down to where the scene is create
3. add a point to the mesh
4. press the enter keypad
5. move your cursor around

### System Info 💻

```shell
chrome browser
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components-front@2.1.4`! Also updated [the docs](https://docs.thatopen.com/Tutorials/Components/Front/AreaMeasurement). Cheers!
