### ISSUE TITLE
Concatenation of treeModels

### ISSUE THREAD

**Issue by MarcGM15** [ThatOpen/engine_components#293]
### Description 📝

When I work with the viewer and upload different files ifc to do a federation, i want to have all the Model trees of each file in only one window, concatenated between them

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey Marc! The latest version of our libraries provides a premade simple tree for most use cases, but also allow to create your own custom tree. If you need help creating yours, let me know!
