### ISSUE TITLE
Wrong link in docs

### ISSUE THREAD

**Issue by lilithgrigoryan** [ThatOpen/engine_components#298]
Hi! Thanks for the awesome project!

In [Tutorial paths](https://docs.thatopen.com/components/tutorial-paths) section of the docs [Create some clipping planes](https://docs.thatopen.com/Tutorials/SimpleRaycaster) subsection leads to the [SimpleRaycaster](https://docs.thatopen.com/Tutorials/SimpleRaycaster) example instead of [SimpleClipper](https://docs.thatopen.com/Tutorials/SimpleClipper).

**Comment by agviegas** [comment]
Fixed! Thanks
