### ISSUE TITLE
Measurements: dimensions.create() gets assigned onClick event when passing false to the enabled property

### ISSUE THREAD

**Issue by MiguelG97** [ThatOpen/engine_components#302]
### Describe the bug 📝

the docs uses this setup:
`dimensions.enabled = true;`
however, when set to false the the double click event gets ignored for dimension creation. Somehow, it's enough pressing 1 click to place a dimensions

### Reproduction ▶️

https://docs.thatopen.com/components/getting-started

### Steps to reproduce 🔢

const dimensions = new OBC.LengthMeasurement(
      viewer
    );
    //settings
    dimensions.enabled = false;

    dimensions.snapDistance = 1;

    //events
    viewerContainer.ondblclick = () => {
      dimensions.create();
      console.log("double click");
    };
    viewerContainer.onclick = () => {
      console.log("1 click");
    };
    window.onkeydown = (event: KeyboardEvent) => {
      console.log(event.code);
      if (
        event.code === "Delete" ||
        event.code === "Backspace"
      ) {
        // dimensions.deleteAll();
        dimensions.delete();
      }
    };
    viewer.ui.toolbars[0].addChild(
      dimensions.uiElement.get("main")
    );

### System Info 💻

```shell
windows os
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Solved in the latest version of the libraries!
