### ISSUE TITLE
Custom GeometryScreenCuller

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#304]
### Description 📝

Normally, when using any class, I just need new OBC.MYCOmponent. But now the OBC.GeometryCullerRenderer class is not exported.https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcStreamer/src/geometry-culler-renderer.ts

### Suggested solution 💡

Is it possible to export it below this line so that the user can customize it?https://github.com/IFCjs/components/blob/main/src/fragments/FragmentIfcStreamer/src/index.ts#L5

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Done. Available from `@thatopen/components-frong@2.0.17`.
