### ISSUE TITLE
FragmentTree: Update mehod does not work

### ISSUE THREAD

**Issue by K1vs** [ThatOpen/engine_components#307]
### Describe the bug 📝

I work with several IFС models that are loaded upon user request.
After loading the first model, everything works well.
But after loading the second model, FragmentTree becomes empty.

It seems to me that the problem is here. Since the UI is associated with the old root node.
<img width="445" alt="image" src="https://github.com/ThatOpen/engine_components/assets/11088116/b9c12f59-8bb2-42fd-a714-702182f69f5e">

The bug is in the display, not in the data structure. Everything is fine with data, but the new tree root is not associated with UI

### Steps to reproduce 🔢

1) Setup components with FragmentClassifier, FragmentTree and FragmentIfcLoader
2) Load first IFC file and check FragmentTree - everything goes well
3) Load second IFC file and check FragmentTree - BUG, tree is empty.

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 16.04 GB / 31.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    openbim-components: ^1.4.4 => 1.4.4
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This is solved in the [latest version of our tree](https://docs.thatopen.com/Tutorials/UserInterface/OBC/RelationsTree). Let us know if you face any issues!
