### ISSUE TITLE
HighlightMaterial selected do not work when fragmentPlan is not implemented

### ISSUE THREAD

**Issue by MiguelG97** [ThatOpen/engine_components#310]
### Describe the bug 📝

I realized that when the navigation floorplan is not integrated, the highlight material on selected is not working

This is what happens when fragmentPlan is not integrated
![image](https://github.com/ThatOpen/engine_components/assets/78984964/bacb64a0-99c0-44c8-9cac-7782e7f15766)

this is the other way:
![image](https://github.com/ThatOpen/engine_components/assets/78984964/df34ad95-10bd-457b-8ecf-18830ef71f9f)

I noticed this piece of code make the difference in the fragmentplan file. However when copyied to the highlight feature without implementing fragment plan is not making it work.
```
    const canvas =
      viewer.renderer.get().domElement;
    canvas.addEventListener("click", () =>
      highlighter.clear("default")
    );
    highlighter.updateHighlight();
```

### System Info 💻

```shell
"three": "^0.160.1",
    "web-ifc": "^0.0.51"
    "bim-fragment": "^1.4.0",
    "openbim-components": "^1.4.2",
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @MiguelG97 this should be solved in the latest version of the libraries. Let us know otherwise. 

PD: We've temporarily disabled the outline effect we had before when highlighting items because the highlighting logic changed a lot (now it's much more performant). We plan to add it again in the future.
