### ISSUE TITLE
FragmentPlans - Can't select all visible elements from the view plan.

### ISSUE THREAD

**Issue by bnares** [ThatOpen/engine_components#312]
### Describe the bug 📝

When I create a FragmentPlan, it is impossible to freely pick elements from the floor plan. Some elements, even though they are visible on the floor plan, can't be selected.

### System Info 💻

```shell
"three": "0.152.2",
    "web-ifc": "^0.0.44"
    "bim-fragment": "1.0.22",
    "openbim-components": "1.1.5",
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Same as https://github.com/ThatOpen/engine_components/issues/148
