### ISSUE TITLE
IfcFragmentLoader throws `Data not found` if excludedCategories contains certain types

### ISSUE THREAD

**Issue by wlinna** [ThatOpen/engine_components#314]
### Describe the bug 📝

I tried to import `small.ifc` from `FragmentIfcLoader/index.html` example. That works. However, after adding `WEBIFC.IFCFURNISHINGELEMENT` to the `excludedCategories`, the import no longer works. It fails with `Data not found` error.

This used to work fine with the version 1.2 of `components`.

### Steps to reproduce 🔢

1. Clone ThatOpen/engine_components repository
2. Install dependencies with `npm i`
3. Open src/fragments/FragmentIfcLoader/index.html
4. Add `WEBIFC.IFCFURNISHINGELEMENT` to `excludedCats` (line 144)
5. Run engine_components with a web server (such as python3 -m http.server)
6. Open `http://localhost:8000/src/fragments/FragmentIfcLoader/`
7. Press Import fragments

### System Info 💻

```shell
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 17.34 GB / 31.19 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/bin/node
    npm: 10.2.4 - /usr/bin/npm
  Browsers:
    Chromium: 122.0.6261.94
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

<details>
<summary>Browser console logs. Click to expand</summary>

```shell
Uncaught (in promise) Error: Data not found!
    getMesh http://localhost:8000/resources/openbim-components.js:101661
    getAllGeometries http://localhost:8000/resources/openbim-components.js:101604
    __emval_call http://localhost:8000/resources/openbim-components.js:33888
    StreamAllMeshes http://localhost:8000/resources/openbim-components.js line 33147 > Function:9
    StreamAllMeshes http://localhost:8000/resources/openbim-components.js:99805
    getAllGeometries http://localhost:8000/resources/openbim-components.js:101603
    load http://localhost:8000/resources/openbim-components.js:101518
    loadIfcAsFragments http://localhost:8000/src/fragments/FragmentIfcLoader/:203
    loadFragments http://localhost:8000/src/fragments/FragmentIfcLoader/:285
    h https://unpkg.com/three@0.160.1/examples/jsm/libs/lil-gui.module.min.js:8
    h https://unpkg.com/three@0.160.1/examples/jsm/libs/lil-gui.module.min.js:8
    add https://unpkg.com/three@0.160.1/examples/jsm/libs/lil-gui.module.min.js:8
    <anonymous> http://localhost:8000/src/fragments/FragmentIfcLoader/:292
openbim-components.js:101661:23

```
</details>

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey, can you try 1.4.12?

**Comment by wlinna** [comment]
Thank you, import seems to work now.

I still get `Data not found` errors in `highlight` function of `FragmentHighlighter`. This seems to be related, because the error does not appear when I omit excludes.

**Comment by agviegas** [comment]
Oh, I see. What do you mean by "omit excludes"? 🤔

**Comment by wlinna** [comment]
Sorry, I used 'exclude' as a noun (even though it's not grammatical :D), meaning a category added to `excludedCategories`.
To put it another way, the error does not appear when I don't add anything to `excludedCategories`

**Comment by agviegas** [comment]
Can you try `1.4.13`?

**Comment by wlinna** [comment]
Phew, 1.4.13 broke much of the logic, but with this 1.4.14 I'm not running into this error anymore. This bug is probably fixed now.

But regarding metadata and highlighting, I'd like to bring another bug to your attention that should be very easy to fix:
https://github.com/ThatOpen/engine_components/issues/313
