### ISSUE TITLE
broken link to documentation

### ISSUE THREAD

**Issue by jgaardsted** [ThatOpen/engine_components#317]
### Describe the bug 📝

On page https://people.thatopen.com/c/the-structure-of-the-aecosystem/

I think there is a broken link; the link says 
https://platform.thatopen.com/documentation
which gives 404, 
I suspect it should be instead 
https://docs.thatopen.com/intro

The TL;DR is, I think the link ‘documentation’ should be more easily discoverable from the front page, and not lead to a 404 :-).

### System Info 💻

```shell
Windows with Firefox
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hi! 

This was already solved by the same comment in the community. No need to publish in both places, with just one of them us completely fine 🙂 this in particular was better in the community.

Thanks a lot!
