### ISSUE TITLE
Outside Fetches to resources that could easily be bundled into components

### ISSUE THREAD

**Issue by quasarchimaere** [ThatOpen/engine_components#322]
### Describe the bug 📝

By accident i found out that you somehow fetch `styles.css` from this url `https://raw.githubusercontent.com/ThatOpen/engine_components/main/resources/styles.css`.

First of all, this could easily be bundled into the dependency itself (if you even need it)
Second of all (idk how many requests other than this one) are happening, but it basically means that you could run analytics on the usage of obc, and also (without really mentioning it - or at least i haven't found it) make people who use obc prone to run into gdpr related issues to say the least, i don't know if you are aware of it but with this you are (possibly) blocking usage of obc in some corporate cases based on their company guidelines

### Steps to reproduce 🔢

run any software using obc 0.0.51 out of the box and see the fetches in your browser network log

### System Info 💻

```shell
any system that uses a software using obc 0.0.51 (at least)
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by quasarchimaere** [comment]
additionally this "feature" would also make it very hard for developers to create offline applications with web-ifc also.

**Comment by HoyosJuan** [comment]
Hi,

We're updating the library and getting rid of everything about UI. All the UI has been done entirely from scratch and is going to live in its own repository, so people will be able to choose whether to use it or not. This will happen in release 1.6.0 coming up in mid-May. From that point forward, all issues related with UI in this repository won't be valid anymore.

I'm closing this issue based on the said above.
