### ISSUE TITLE
Automatic snapping of points with lengthMeasurement doesn't work

### ISSUE THREAD

**Issue by namelaise** [ThatOpen/engine_components#326]
### Describe the bug 📝

Automatic snapping of points works well with figures manually created with Three.geometry. However, when using fragmentIfcLoader to load an IFC model, it no longer works. 

It also doesn't work for all the others class who use automatic snapping point (LineIntersectionPicker, VertexPicker, etc)

### Steps to reproduce 🔢

1. Use fragmentIfcLoader to load an Ifc Model
2. Use LengthMeasurement 

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 6.50 GB / 31.73 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MiguelG97** [comment]
Happen the same to me!

**Comment by shahbaziparisa** [comment]
How did you use LengthMeasurement?

**Comment by agviegas** [comment]
Fixed in the latest version! Let me know otherwise 😊 Cheers
