### ISSUE TITLE
No colors on some IFC models in the viewer

### ISSUE THREAD

**Issue by BimonoApp** [ThatOpen/engine_components#328]
### Describe the bug 📝

I have an issue on some models. The colors not loading correctly and the model is full black in the scene. On other software, no problem with that. [Manitou MT 1335.ifc.zip](https://github.com/ThatOpen/engine_components/files/14668498/Manitou.MT.1335.ifc.zip)

### Steps to reproduce 🔢

1) Load the model in a BIM Viewer, and see the color Red on the model
2) Load the model with the OBC package viewer, and see that the model if full black

### System Info 💻

```shell
MAC OS, Google Chrome, openbim-components, npm
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hi @BimonoApp!

Have you setup lights in your scene?

**Comment by agviegas** [comment]
Solved. You can try it [here](https://thatopen.github.io/engine_web-ifc/demo/).

![image](https://github.com/ThatOpen/engine_components/assets/56475338/488e0eff-5472-4115-9027-2124e22540f8)
