### ISSUE TITLE
Is is possible to change mouse event?

### ISSUE THREAD

**Issue by is0263rf** [ThatOpen/engine_components#331]
### Description 📝

The current implementation uses the "mousemove" event, but is it possible to change it to the "pointermove" event? "touchmove" or "pointermove" will work on mobile devices! "mousemove" doesn't work on mobile devices.

https://github.com/ThatOpen/engine_components/blob/3ed5533675afba2c2cf5c4294022c3687b898e69/src/base-types/mouse.ts#L52-L59

### Suggested solution 💡

change "mousemove" to "pointermove".

```js
this.dom.addEventListener("pointermove", this.updateMouseInfo); 
```

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Fixed! Available from `@thatopen/components@2.0.16` and `@thatopen/components-front@2.0.16`.
