### ISSUE TITLE
Fragment Highlighter stops working when isolating elements with Fragment Hider

### ISSUE THREAD

**Issue by RASRC** [ThatOpen/engine_components#332]
### Describe the bug 📝

When I use the FragmentHider to isolate elements, some of them can’t be highlighted in the viewer, even when they are selected or hovered.

Thanks for the support!

### Steps to reproduce 🔢

1) Defining a FragmentIdMap with certain elements
2) Isolating those elements with the hider.isolate(FragmentIdMap) method
3) Then some of the elements isolated cannot be selected, hovered or change their appearance with the highlighter

### System Info 💻

```shell
Windows 11
Google Chrome
npm
openbim-components
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

N/A

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey, this should be solved from `@thatopen/components@2.0.17`. See:

https://github.com/ThatOpen/engine_components/assets/56475338/fb926834-c81e-47fb-a4e7-a0593de36026

Let us know if you have any issues. Cheers!

**Comment by agonzalezesteve** [comment]
I'm using @thatopen/components@2.1.18 and I can't select an isolated model.

**Comment by agviegas** [comment]
@agonzalezesteve using the latest version, and adding the following code to the end of the [highlighter tutorial](https://docs.thatopen.com/Tutorials/Components/Front/Highlighter):

```ts
const hider = components.get(OBC.Hider);
const classifier = components.get(OBC.Classifier);
classifier.byEntity(model);
const walls = classifier.find({ entities: ["IFCWALLSTANDARDCASE"] });

window.addEventListener("keydown", () => {
  hider.isolate(walls);
});
```

This is the result:


https://github.com/user-attachments/assets/af4f7b93-c77d-4a8c-abea-f30f9c2a49e4

If this doesn't work for you, or you are doing something else that doesn't work, please let us know and we'll take a look. Keep in mind that you also need to have the corresponding [fragments](https://github.com/ThatOpen/engine_fragment/) version installed for this to work.
