### ISSUE TITLE
CubeMap Improvements

### ISSUE THREAD

**Issue by JFRichters** [ThatOpen/engine_components#335]
### Description 📝

The CubeMap is quite cool not very open for adaptation.
Please add ids to the cube faces, other that the front face, so that it is possible to style them.

### Suggested solution 💡

// #region Cube faces
    const frontFace = document.createElement("div");
    frontFace.id = "cube-map-front";
    frontFace.className = `${this._cubeFaceClass} ${this._cyan}`;
    frontFace.style.transform = "rotateX(180deg) translateZ(-30px)";
    frontFace.style.transition = "all 0.2s";
    frontFace.onclick = () => this.orientToFace("front");

    const topFace = document.createElement("div");
    topFace .id = "cube-map-top";
    topFace.className = `${this._cubeFaceClass} ${this._pink}`;
    topFace.style.transform = "rotateX(90deg) translateZ(-30px)";
    topFace.style.transition = "all 0.2s";
    topFace.onclick = () => this.orientToFace("top");

    const bottomFace = document.createElement("div");
    bottomFace .id = "cube-map-bottom";
    bottomFace.className = `${this._cubeFaceClass} ${this._pink}`;
    bottomFace.style.transform = "rotateX(270deg) translateZ(-30px)";
    bottomFace.style.transition = "all 0.2s";
    bottomFace.onclick = () => this.orientToFace("bottom");

    const rightFace = document.createElement("div");
    rightFace.id = "cube-map-right";
    rightFace.className = `${this._cubeFaceClass} ${this._blue}`;
    rightFace.style.transform =
      "rotateY(-270deg) rotateX(180deg) translateZ(-30px)";
    rightFace.style.transition = "all 0.2s";
    rightFace.onclick = () => this.orientToFace("right");

    const leftFace = document.createElement("div");
    leftFace .id = "cube-map-left";
    leftFace.className = `${this._cubeFaceClass} ${this._blue}`;
    leftFace.style.transform =
      "rotateY(-90deg) rotateX(180deg) translateZ(-30px)";
    leftFace.style.transition = "all 0.2s";
    leftFace.onclick = () => this.orientToFace("left");

    const backFace = document.createElement("div");
    backFace .id = "cube-map-back";
    backFace.className = `${this._cubeFaceClass} ${this._cyan}`;
    backFace.style.transform = "translateZ(-30px) rotateZ(180deg)";
    backFace.style.transition = "all 0.2s";
    backFace.onclick = () => this.orientToFace("back");
    // #endregion

### Additional context ☝️

One way I use the id is to add the "F' letter to the front face:

`
::ng-deep #cube-map-front:before { content: "F"; }
`

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey! The ViewCube you know is now decoupled of components and it's now in [UIComponents library](https://github.com/ThatOpen/engine_ui-components/tree/main/packages/obc/src/core/ViewCube). They use Web Components, and to change the colors you can do it by using the following CSS variables:

`--bim-view-cube_x--bgc`
`--bim-view-cube_y--bgc`
`--bim-view-cube_z--bgc`

`bgc` stands from background color.

Closing this issue. Thanks!
