### ISSUE TITLE
AreaMeasurement hasn't visible on/off property like LengthMeasurement

### ISSUE THREAD

**Issue by tptspe** [ThatOpen/engine_components#337]
### Description 📝

Sometimes users want to hide area measurement lines when the tool is off.
So the code may like this.
areaMeasurementDimensions.visible = areaMeasurementDimensions.enabled;

But areaMeasurement doesn't have `visible`.

### Suggested solution 💡

Can you add  Hideable as extension to AreaMeasurement class like LengthMeasurement?

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Available from `@thatopen/components-front@2.1.16`!
