### ISSUE TITLE
Set maximum size exceeded in FragmentPropsStreamConverter

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#341]
### Describe the bug 📝

- When I load a model ~1.3 GB, the program will throw an error about Set at this line https://github.com/ThatOpen/engine_components/blob/main/src/fragments/FragmentIfcStreamer/src/fragment-props-stream-converter.ts#L121

- That reminds me of the problem above https://stackoverflow.com/questions/72809513/how-do-i-know-what-is-the-size-limit-for-constructing-a-set-in-javascript

### Steps to reproduce 🔢

If instead of using Set, can we replace it with an array, I know this makes the filtering process difficult. An idea might be GeometryTypes:{[id:number]:number} instead of Set<number>

### System Info 💻

```shell
/////
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

/////

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kitsunekyo** [comment]
there currently seems to be a size limit to what the props stream converter can handle. i was told it is being worked on.
