### ISSUE TITLE
[feat] a CONTRIBUTING.md

### ISSUE THREAD

**Issue by davidgtl** [ThatOpen/engine_components#344]
### Description 📝

To contribute effectively, it would be useful to know:
- What is the general file structure/architecture and how various pieces fit together (e.g. engine_fragment, three.js, BIM Tiles, etc.)
- What is the develoment cycle for a feature/bugfix which includes:
  - how to clone & setup a local environment e.g. [github's guide](https://docs.github.com/en/contributing/setting-up-your-environment-to-work-on-github-docs/creating-a-local-environment)
  - how to build & test the code against the examples (e.g. via a local `python3 -m http.server 8000`)
  - formatting & code style
  - commit message format e.g. [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
 
The entrypoint for all this pieces of info is expected to be a CONTRIBUTING.md file

### Suggested solution 💡

A detailed CONTRIBUTING.md file in the project root containing the above information

There is some information about getting started e.g. https://docs.thatopen.com/components/getting-started, but it's not geared towards working on this codebase

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Thanks a lot @davidgtl! We will keep this in mind to do it asap.

**Comment by agviegas** [comment]
We have created a [contributing page](https://docs.thatopen.com/contributing) in our docs. I think it includes all the points you mentioned, but let us know otherwise. Cheers!
