### ISSUE TITLE
EdgeClipper - Keeping Arrows and Planes Intact

### ISSUE THREAD

**Issue by Petran97** [ThatOpen/engine_components#347]
### Description 📝

Greetings,

I am currently encountering an issue within my project involving openbim-components, specifically regarding the utilization of EdgeClipper to implement two cutting planes.

The issue arises when one plane is moved over the other, resulting in the clipping of both the arrow and the plane of the other one, rendering them invisible.

Despite dedicating considerable time to troubleshooting, I have yet to find a satisfactory solution. My attempts to address this by setting clippingPlanes to null in the materials have proven unsuccessful.

To provide visual clarity, I have attached two images illustrating the problematic scenario.

Your guidance or assistance in resolving this matter would be immensely appreciated.

Thank you for your attention and support.

### Additional context ☝️

![image](https://github.com/ThatOpen/engine_components/assets/87848383/b3499240-f2cc-4c0c-b80c-46333c5aa19c)
![image](https://github.com/ThatOpen/engine_components/assets/87848383/91451eb6-86a3-4e6b-9382-83cc8935d096)

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hi @Petran97! Unfortunately this happens because clipping planes must be global in order to affect the postproduction renderer. So, as far as I know, there's no way to circumvent this using three.js. I'm sorry! If anyone has any idea about this, we're all ears. Closing this for now.

**Comment by Rocha442** [comment]
Hi there! I'm currently trying to implement a Scope Box feature in my app and i'm facing this same issue, specifically the loss of the control arrow, which considerably limits the user interaction with the 6 different clipping planes of the Scope Box. Is there a way to replace the current TransformControls with another approach? Perhaps just clicking and dragging anywhere on the plane could move it on its normal vector?

**Comment by agviegas** [comment]
Hey @Rocha442 you can make the planes `visible=false` and that will disable the current TransformControls. Then you can implement your Scope Box and use it to control the position of 6 invisible clipping planes. That should easily work on your case as long as you make sure that there's a small offset from the planes to the faces of your box, so that they never clip it out
