### ISSUE TITLE
Changing the alpha value of a stream loaded geometry doesn't work

### ISSUE THREAD

**Issue by MadsHolten** [ThatOpen/engine_components#360]
### Describe the bug 📝

Setting a low alpha value for some objects is useful since it allows dimming non-relevant objects in a model view. Therefore I tried manipulating some objects in the geometry definition for the tiles streamer with the method below:

```javascript
function makeAllTransparent(geometryData){
        geometryData.assets = geometryData.assets.map(item => {
          item.geometries = item.geometries.map(g => {
            g.color[3] = 0.001;
            return g;
          });
          return item;
        });
 }
```

As you can see in the demo, however, this results in some objects not being shown.

[Try demo](https://qaecy.github.io/demos/obc_1.4.21/dist/issue-transparency.html)

[Source code](https://github.com/qaecy/demos/blob/main/obc_1.4.21/issue-transparency.html)

[Sample tiles found here](https://github.com/qaecy/sample-models/tree/main/duplex)

### Reproduction ▶️

https://qaecy.github.io/demos/obc_1.4.21/dist/issue-transparency.html

### System Info 💻

```shell
Tiles created with web-ifc version 0.0.51 and openbim-components 1.4.15.

Loader uses openbim-components 1.4.21 (same problem with 1.4.15)
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MadsHolten** [comment]
Same results in 1.5.0

**Comment by MadsHolten** [comment]
Same results in 2.0.1. An alternative could be the new setColor()-method on the fragments, but this doesn't support transparency either.

**Comment by eng-luciano-julien** [comment]
I am interested in this feature too.
As a temporary solution I am using the highlight function.

**Comment by agviegas** [comment]
IMO the JSON containing the information of the geometries shouldn't be edited, as it could greatly increase the number of edge cases. So let's see if we can make this happen without doing that.

With the current API, and using the [streamer tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer) as a starting point, I've changed the load function to this:

```ts
async function loadModel(geometryURL: string, propertiesURL?: string) {
  const rawGeometryData = await fetch(geometryURL);
  const geometryData = await rawGeometryData.json();
  let propertiesData;
  if (propertiesURL) {
    const rawPropertiesData = await fetch(propertiesURL);
    propertiesData = await rawPropertiesData.json();
  }

  const model = await loader.load(geometryData, true, propertiesData);
  console.log(model);

  const classifier = components.get(OBC.Classifier);
  classifier.byEntity(model);
  const found = classifier.find({ entities: ["IFCWALLSTANDARDCASE"] });
  const fragKeys = new Set(Object.keys(found));

  const transpMaterial = new THREE.MeshLambertMaterial({
    transparent: true,
    opacity: 0.2,
  });

  loader.onFragmentsLoaded.add((frags) => {
    for (const frag of frags) {
      if (fragKeys.has(frag.id)) {
        frag.mesh.material = [transpMaterial];
      }
    }
  });
}
```

This is the result:

https://github.com/user-attachments/assets/e9fe62d9-58e1-40e4-8a1a-97e8f54b3fc1

As you can see, streaming doesn't support visibility through transparent objects, as it would increase its complexity by an order of magnitude. This is also the case for fragments that were already transparent in the original BIM model.

If you want to make the whole model transparent and force that some objects are displayed, IMO the best way would be to add a list of fragments to the streamer that should always be visible and present in memory, regardless of the streaming visibility test. I'm likely going to do it for [this issue](https://github.com/ThatOpen/engine_components/issues/435), so if this is what you need, we can continue the discussion there.

For now, I'm closing this, as changing the alpha value of streamed elements works. Cheers!

**Comment by MadsHolten** [comment]
Thanks for sharing this approach + your idea on how to force load some fragments @agviegas. Of course, if it complicates things unnecessarily, this is the way to go. But I hope you understand the purpose. In some cases you need a full BIM authoring tools. In other cases you just need a visual representation of your data, and in this case a simple 3D view of the model, where colors/transparency are manipulated to reflect your specific message, is what you want.

I will follow the issue you are linking to.

**Comment by MadsHolten** [comment]
Actually, I was just looking at your code and this does indeed work in the case where you want to highlight all walls. However, it will not work if I want to highlight only one wall in that fragment.

**Comment by agviegas** [comment]
@MadsHolten I know! Right now, partial transparency is not possible due to the Three.js limitations mentioned above. 

But I plan to implement fragment cloning these days. So with that, you should be able to create a clone of the fragment you want to make "partially transparent". Then make 1 clone fully opaque and 1 clone fully transparent, and use the hide functions to choose what items get opaque/transparent.

Maybe worth making a component to do this with ease?
