### ISSUE TITLE
IFC file wall and windows glitchs

### ISSUE THREAD

**Issue by acommeau** [ThatOpen/engine_components#371]
### Describe the bug 📝

I have a little IFC file comming from Solibri, when i open it with FragmentIfcLoader in my react app, i have strange glitch.
(latest version of open component lib)

Usually, the blue lines are windows and there is a window on the roof.

[DharmaOrchidIFC.zip](https://github.com/ThatOpen/engine_components/files/15063926/DharmaOrchidIFC.zip)

![image](https://github.com/ThatOpen/engine_components/assets/116647659/20eacb34-d591-4019-b82f-16bdb7e0bb7a)

### Steps to reproduce 🔢

1. Opening the file with latest open component lib version
2. Use FragmentIfcLoader and load the model in scene

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 633.81 MB / 15.70 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.3.1 - ~\AppData\Roaming\npm\pnpm.CMD
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Weird, this loads correctly in the [core demo](https://thatopen.github.io/engine_web-ifc/demo/). Let me check and get back to you!

**Comment by agviegas** [comment]
Solved in the latest version of the libraries. Keep in mind that this model has both IFCSPACE and IFCOPENINGSTANDARDCASE elements, which might occlude the rest of your model. In the video below I'm loading this model in the [hider tutorial](https://docs.thatopen.com/Tutorials/Components/Core/Hider) and you can see it.

Cheers!

https://github.com/user-attachments/assets/55f99a91-a6f8-411a-83a9-dcd47c6c0c9d
