### ISSUE TITLE
Can I get rid of fetch()?

### ISSUE THREAD

**Issue by is0263rf** [ThatOpen/engine_components#373]
Why does this source code do `fetch()` to fetch fonts and css? I want to eliminate `fetch()` so that it can be used in offline mobile apps.

https://github.com/ThatOpen/engine_components/blob/fc953a6fce8e2160b690a58333a65144a9ac1914/src/ui/UIManager/index.ts#L150-L163

**Comment by orazio1234** [comment]
> Why does this source code do fetch() to fetch fonts and css?

It's used to style the UI.

> I want to eliminate fetch() so that it can be used in offline mobile apps.

You could use https://www.npmjs.com/package/patch-package to load fonts and css from a local file, or better should be included in the repo.

**Comment by agviegas** [comment]
Fixed!
