### ISSUE TITLE
Add new IFC element at specific co-ordinate in the loaded 3D view

### ISSUE THREAD

**Issue by vishalpatil3390** [ThatOpen/engine_components#375]
### Description 📝

Is it possible to add new Add new IFC element (ex.chair / Device) at specific co-ordinate in the loaded 3D view

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
If you mean adding an element like in a modelling app like Revit or Archicad, not yet, and not in this library. 

This is a library just for IFC visualization. But after the summer we'll get into [modelling](https://github.com/ThatOpen/engine_clay) as well, so it will be possible to edit and create IFC models from scratch directly in the browser.

Cheers!
