### ISSUE TITLE
Inquire about the LOD related matters of IFC

### ISSUE THREAD

**Issue by jingyangking** [ThatOpen/engine_components#379]
### Description 📝

Hello developer, I would like to inquire if there is a tool that can automatically grade IFC models without the need for format conversion， just like the image below, but what I need is to do the overall reduction.
![image](https://github.com/ThatOpen/engine_components/assets/112468121/e382f4c4-4459-4af5-878d-cb75c5ca84c8)

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey! We don't have anything like that, but maybe you can [investigate this](https://threejs.org/examples/#webgl_modifier_simplifier). Cheers!
