### ISSUE TITLE
IFC Model Alignment Issue

### ISSUE THREAD

**Issue by Issa369** [ThatOpen/engine_components#382]
### Describe the bug 📝

I'm currently encountering an issue while streaming some IFC files. I was testing a 1.2 GB file and noticed that some walls were not being rendered due to their vertex arrays being empty, which results in a null bounding box. Interestingly, a very similar wall works perfectly. I found a related issue [here ](https://github.com/ThatOpen/engine_web-ifc/issues/590)with someone else's file, tested their fix by updating web-ifc along with the wasm files, and it resolved the issue for that file. However, when I applied the same update to my file, it unfortunately didn't work.

Additionally, I thought that updating openbim-components and web-ifc along with their respective modules might help, but while this update did resolve the issue, it caused the elements in my model to misalign, even though other models work perfectly with these updates. 

Any insights or suggestions would be greatly appreciated!

### Steps to reproduce 🔢

![Capture](https://github.com/ThatOpen/engine_components/assets/114977591/4c0a4f4b-8cca-4866-9113-8ad8c832b904)

### System Info 💻

```shell
windows 10 64x, google chrome
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This was happening due to the deduplication of extrusions, which we removed from the latest version of the libraries. So this is now solved. You can check out the tutorial [here](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer). Let us know otherwise!
