### ISSUE TITLE
Avoid using generic css variable names that conflict with popular framework

### ISSUE THREAD

**Issue by IvanoAlvino** [ThatOpen/engine_components#383]
### Describe the bug 📝

I can see that in this commit some css variables have been introduced.

The issue with the chosen name is that it conflicts with popular frameworks, like angular material: in fact when updating to openbim-components 1.5.0 we noticed changes in our colors, coming from the following definitions:

```
:root {
  --primary-color: #BCF124;
  --secondary-color: #6528D7;
  /* TODO: Probably this needs to be called background-color */
  --secondary-color-100: #000000bb;
  --secondary-color-120: #1a2128;
}
```

This definitions end up in the `head` section of the html page
![image](https://github.com/ThatOpen/engine_components/assets/6837936/512d0ff2-3863-40d6-b4fd-eee90a7dfe5c)
and as a result start affecting the entire page.

I would suggest to find more specific, unique names, especially when creating variables in such a broad scope as `:root`

### System Info 💻

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
    npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 124.0.6367.201
    Safari: 17.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey!

Since version 2.0 of the library, we have decided to get rid of everything about UI. Instead, we created a Web Components [library](https://github.com/ThatOpen/engine_ui-components) to keep logic and user interface separated.

In the new UI library, all styles are encapsulated as they are using the Shadow DOM (that's how Web Components work). Also, global styles are scoped with `--bim-ui_` so it shouldn't have any conflict with existing popular names.

Closing this issue!
