### ISSUE TITLE
Unable to zoom back in after zooming out with an OrthoPerspectiveCamera

### ISSUE THREAD

**Issue by Haval** [ThatOpen/engine_components#388]
### Describe the bug 📝

If I zoom out to a far distance using an OrthoPerspectiveCamera and then when I attempt to zoom back in the camera does not zoom back in correctly and instead remains far away from the object in view.

This can also be seen in the documentation tutorial https://docs.thatopen.com/Tutorials/OrthoPerspectiveCamera

### Reproduction ▶️

https://docs.thatopen.com/Tutorials/OrthoPerspectiveCamera

### System Info 💻

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 27.22 GB / 31.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  npmPackages:
    openbim-components: ^1.3.4 => 1.3.4

Browsers: Chrome
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zhangjc20** [comment]
I have a similar problem too, if i zoom out to a far distance then i can't zoom out further, but if i zooming in is still possible, it seems that the further you zoom out, the less sensitive

**Comment by agviegas** [comment]
Hey, for the camera we just use [yomotsu's camera controls](https://github.com/yomotsu/camera-controls). They are available in the `controls` property of all our cameras. We just use those controls without doing anything else, so there's not much we can do 🤔 maybe you can report that error in their library? Alternatively, you can provide a feature to zoom back to the origin, like shown [in this tutorial](https://docs.thatopen.com/Tutorials/Components/Core/BoundingBoxer). If there's something else we can do, please let us know! Closing this issue for now, as it seems something related to yomotsu's library. Cheers!
