### ISSUE TITLE
top-tool-package-reader license is not set

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#390]
### Describe the bug 📝

It appears no license has been specified for the dependency(top-tool-package-reader) that is used across component library dependencies. https://www.npmjs.com/package/top-tool-package-reader

Unfortunately I could not find the source code on github as well. But it appears it is coming from the same development team. I wonder, was that intentional? Any plans to specify a license for that soon? It brings questions to use the library as the no license declaration actually means [default copyright rules apply](https://docs.github.com/articles/licensing-a-repository#:~:text=You're%20under%20no%20obligation,derivative%20works%20from%20your%20work.). 

### System Info 💻

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 47.02 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 124.0.6367.208
    Edge: 124.0.2478.105
    Safari: 17.2.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by onderilkesever** [comment]
If that is fine to remove 'getPlatformComponent' altogether, i can create a pr for it.

**Comment by agviegas** [comment]
That package was part of something that wasn't released in the end! We have removed all the dependencies for that package alltogether 🙏🏻 Let me know otherwise!

**Comment by onderilkesever** [comment]
I can confirm it is not part of the dependencies anymore. This particular issue was huge for us, thanks a lot for addressing it so promptly. Best regards.
