### ISSUE TITLE
IFC displaced  unaligned geometries

### ISSUE THREAD

**Issue by MohamedAbdelkrim-coder** [ThatOpen/engine_components#397]
### Describe the bug 📝

while i am loading IFC file i got noticed displaced or unaligned geometries and i have checked it also using tutorial viewer and i got same result but i checked my ifc file with web-ifc  Viewer and it looks fine and every geometry is in its place 
so i have checked it with streamer and IFCfragment loader and tutorial viewer and for all gave me displaced geometries
![Snipaste_2024-05-24_01-14-25](https://github.com/ThatOpen/engine_components/assets/131366494/adb89f78-a08b-4b50-832b-1f373611fcd4)

![image](https://github.com/ThatOpen/engine_components/assets/131366494/dff4b608-a335-41c0-85e3-3063c0b62d2b)

### System Info 💻

```shell
"dependencies": {
    "bim-fragment": "^1.4.0",
    "camera-controls": "^2.7.4",
    "openbim-components": "^1.4.21",
    "stats": "^1.0.0",
    "three": "0.160.1",
    "web-ifc": "^0.0.53"
  }
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @MohamedAbdelkrim-coder we would need to have the IFC to solve it. Can you share it privately with antonio@thatopen.com? Thanks!

**Comment by agviegas** [comment]
File privately shared [here](https://drive.google.com/file/d/1kld48C8HqMMor9tF7UeMleqqLU-s9oaw/view?usp=drive_link).

**Comment by HoyosJuan** [comment]
Hey @MohamedAbdelkrim-coder! 

This has been already solved in web-ifc and pushed to @thatopen/components@2.0.20 and @thatopen/components-front@2.0.19. Please, check out!

![image](https://github.com/ThatOpen/engine_components/assets/84806689/0de75a4e-c6fa-40b8-b40e-43437a4732e8)

I will close the issue now. Feel free to leave any messages here if you have further concerns.

Thanks!
