### ISSUE TITLE
full example where?

### ISSUE THREAD

**Issue by cesarbenjamindotnet** [ThatOpen/engine_components#398]
### Describe the bug 📝

hello, i'm reading the readme file where it says:

> 
> Usage
> You need to be familiar with [Three.js API](https://github.com/mrdoob/three.js/) to be able to use this library effectively. In the following example, we will create a cube in a 3D scene that can be navigated with the mouse or touch events. You can see the full example [here](https://github.com/ThatOpen/engine_components/blob/main/src/core/SimpleScene/index.html) and the deployed app [here](https://thatopen.github.io/engine_components/src/core/SimpleScene/index.html).

but the "full example"  [here](https://github.com/ThatOpen/engine_components/blob/main/src/core/SimpleScene/index.html)  it don't exists... can you fix it please? would be great to see the sample active on line.

### Steps to reproduce 🔢

click on "here" link on readme

 [here](https://github.com/ThatOpen/engine_components/blob/main/src/core/SimpleScene/index.html) 

### System Info 💻

```shell
any
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed!

**Comment by nijiiffy** [comment]
"...You can see the full example [here](https://github.com/ThatOpen/engine_components/blob/main/src/core/Worlds/index.html)" points to [](https://github.com/ThatOpen/engine_components/blob/main/src/core/Worlds/index.html) which don't exists yet... and the "deployed here" only downloads a ts file.

**Comment by agviegas** [comment]
My bad! Can you try again! It should be working now. Thanks!
