### ISSUE TITLE
EdgesClipper.deleteAll() results in infinite loop

### ISSUE THREAD

**Issue by GlitchedCode** [ThatOpen/engine_components#399]
### Describe the bug 📝

I am writing a BIM application that makes use of the EdgesClipper component and a few UI elements that interact with it. I noticed that if i try to use the `deleteAll` method while the component is disabled the application goes into an unresponsive endless loop. Upon inspecting the code for EdgesClipper it seems that trying to delete a plane while the component is disabled results in no deletion occurring at all, and a loop checking for the amount of active planes never exits.
I worked around this issue by enabling and disabling the component again, but it's kind of annoying and counterintuitive.

### Steps to reproduce 🔢

1. follow the tutorial for the EdgesClipper component
2. add a few clipping planes
3. disable the component
4. call `deleteAll` on the component

### System Info 💻

```shell
System:
    OS: Linux 6.8 Arch Linux
    CPU: (2) x64 AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G
    Memory: 1.33 GB / 7.16 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.0.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
  Browsers:
    Chromium: 124.0.6367.201
  npmPackages:
    openbim-components: ^1.5.0 => 1.5.0
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components@2.0.15`!
