### ISSUE TITLE
WebXR Camera issue

### ISSUE THREAD

**Issue by ThisIsMonta** [ThatOpen/engine_components#401]
### Describe the bug 📝

Since openbim-components uses [camera-controls](https://github.com/yomotsu/camera-controls) package, enabling xr makes the camera gray.

Normal camera with FirstPerson mode enabled : 

![image](https://github.com/ThatOpen/engine_components/assets/47502752/8565a6fc-59b1-4fb2-83d4-76464c612042)

WebXR camera enabled:

![image](https://github.com/ThatOpen/engine_components/assets/47502752/13c0f030-7bc2-4080-ae50-7fbf3abc930b)

Also after some research, i found out that i have to make a separate camera to enable WebXR for camera-controls package [Issue#109](https://github.com/yomotsu/camera-controls/issues/109#issuecomment-656945711).

So is there a way to add a [Default threejs camera](https://threejs.org/docs/#api/en/cameras/PerspectiveCamera) to the world.camera ?

### System Info 💻

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
  Memory: 6.75 GB / 15.94 GB
Binaries:
  Node: 20.11.0 - C:\Program Files\nodejs\node.EXE       
  npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: 125.0.6422.113
  Edge: Chromium (123.0.2420.97)
  Internet Explorer: 11.0.19041.4355
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @ThisIsMonta! You can create your own custom camera and [add it to the world](https://docs.thatopen.com/Tutorials/Components/Core/Worlds). The only requirement is that it extends the [BaseCamera](https://docs.thatopen.com/api/@thatopen/components/classes/BaseCamera) abstract class. If you have any issues with this, let us know! Closing this for now, as this should allow you to create a camera that fulfill your needs.
