### ISSUE TITLE
How to ByPass loading screen to load always the same model ?

### ISSUE THREAD

**Issue by amapic** [ThatOpen/engine_components#402]
Hi,
Thanks for this amazing job. Everything about that project is exceptionally well-done. How I can easily directly load a model on page load ? I will do it anyway but if you have a few tips, it would help. Have a good day.

**Comment by agviegas** [comment]
Hey, thank you very much for your kind words! You can just follow the [IfcLoader](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) tutorial. Cheers
