### ISSUE TITLE
Classifier - Last model is replacing old list values using the OBC.Classifier

### ISSUE THREAD

**Issue by YannMermin** [ThatOpen/engine_components#403]
### Describe the bug 📝

I am generating the model trees for all the models added into my scene. Using the classifier, I want to get the following lists : 
- byModel
- byEntity
- bySpatialStructure

For the first model loaded, no problem, it works fine and the lists are OK.
But for all next models added into the scene, it will completly replace the previous classifier lists, and I can only access the last model's lists.

Here is the part of my code where I am getting the lists (call for all the models loaded)

`const classifier = components.get(OBC.Classifier);
    await classifier.dispose();

    classifier.byModel(model.uuid, model);
    classifier.byEntity(model);
    await classifier.bySpatialStructure(model);`

### Steps to reproduce 🔢

1. Install the @thatopen/components package
2. Load multiple models into a scene
3. For each models, use the OBC.Classifier with the following functions : 
- byModel
- byEntity
- bySpatialStructure
4.Check the values in the classifier.list, it will be only the last model loaded values.

### System Info 💻

```shell
@thatopen/components - Google Chrome - React JS
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi Yann! This happens because you are calling `dispose()`, which should be called only when your user walks away from your BIM viewer in your app to get rid of memory. If you remove that line, and only use it when you need to destroy the viewer, the issue should be solved. Let us know otherwise!
