### ISSUE TITLE
IfcStreamer GeometryCullerRenderer does not respect coordinate when loading models.

### ISSUE THREAD

**Issue by SimonSchneider** [ThatOpen/engine_components#405]
### Describe the bug 📝

When using the IFCStreamer the model is getting culled according to its "centered position".
When loading multiple models they are placed in the world correctly when using `components.get(CustomIfcStreamer).load(data, true)`.
But the culler is not respecting this and seems to cull as if the models where loaded using `components.get(CustomIfcStreamer).load(data, false)`.

Objects that are hidden by other models in the centered position are being culled and it's impossible to get them to be visible.

### Steps to reproduce 🔢

-

### System Info 💻

```shell
-
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

-

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Solved! Let us know otherwise :)
