### ISSUE TITLE
TypeError: this.wasmModule is undefined

### ISSUE THREAD

**Issue by antoniocolagreco** [ThatOpen/engine_components#407]
### Describe the bug 📝

Hi there,

I have started using this library to display IFC files in a Next.js project. It is blazing fast. The model loads without any problems, but I am getting this "TypeError: this.wasmModule is undefined" error on Firefox after the model is displayed in the viewport.
On Chrome, the error is "TypeError: Cannot read properties of undefined (reading 'OpenModel')."

I followed the tutorial, read the docs, and tried to find if anyone had the same problem but to no avail. Perhaps it is just me doing something wrong. I also tried to load `IfcLoader` dynamically, but the outcome is the same.

```
        const fragmentIfcLoader = components.get(IfcLoader)

        fragmentIfcLoader.settings.wasm = {
            absolute: false,
            path: `/`,
        }
```

I am using web-ifc wasm files 0.0.53 with:
```
        "three": "^0.160.1",
        "@thatopen/components": "^2.0.6",
        
```

Any idea on how to get rid of this error? Thank you

### System Info 💻

```shell
Windows 11, Firefox and Chrome
```

### Used Package Manager 📦

pnpm

### Error Trace/Logs 📃

![error](https://github.com/ThatOpen/engine_components/assets/92807691/36063912-4f4e-423a-b9b6-06f4bf69925b)

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi, it's a bit hard to debug this without additional info. In the [IFCLoader tutorial](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) you have the full source, and it works. You can check it in the [example below](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader#-wrap-up). If you can provide a minimal example that we can test, we'll check it out. Otherwise, we'll close this, as it seems like the library is working and expected and . Cheers!

**Comment by antoniocolagreco** [comment]
I'm encountering this error only in the dev, it doesn't occur in production, so I can live wit it. I opened this issue to see if more experienced developers working with Next.js have faced the same problem in order to find a quick and easy solution. Probably your library is not the culprit, i should check better on the framework side. I will investigate and fix it by myself when I will have more spare time. Thank you for your response and for creating these libraries.
