### ISSUE TITLE
Classifier - find doesn't work on byIfcRel

### ISSUE THREAD

**Issue by lemoinet** [ThatOpen/engine_components#408]
### Describe the bug 📝

When you want to classify your model via byIfcRel and you want to find elements in the classification afterwards, the following error  message is shown: Classification storeys does not exist.

```
 const classifier = this.components.get(OBC.Classifier);
classifier.byIfcRel(model, WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE, "storeys");

const storeys = classifier.find({
          storeys: ["000 Rez-de-Chaussée", "570 NI Deuxième étage"]
        });
```

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 2.16 GB / 15.65 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 2.4.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @thatopen/components: ^2.0.8 => 2.0.8
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @lemoinet! As mentioned in the community, byIfcRel is asynchronous. If you want to do something immediatley after its calculated, you need to wait for the result of the ready `await classifier.byIfcRel(model, WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE, "storeys");`
