### ISSUE TITLE
Culler | Plans component not work correctly | How to use latest version?

### ISSUE THREAD

**Issue by shahbaziparisa** [ThatOpen/engine_components#409]
### Describe the bug 📝

![Screenshot 2024-06-07 at 2 54 31 PM](https://github.com/ThatOpen/engine_components/assets/70272544/cb89c530-480c-4e9f-9e81-49896405cea6)
I want to use a Plan view like this

https://docs.thatopen.com/Tutorials/Components/Front/Plans

but the first part causes the model not to load completely as before

cullers = components1.get(OBC1.Cullers);
        culler = cullers.create(world);

        world.camera.controls.addEventListener("sleep", () => {
            culler.needsUpdate = true;
        });
 for (const fragment of model.items) {
                    culler.add(fragment.mesh);
                }

                culler.needsUpdate = true;

result: Especially when I rotate the camera at first everything shows incorrect and after some seconds loads 80 percent of details
![Screenshot 2024-06-07 at 2 51 47 PM](https://github.com/ThatOpen/engine_components/assets/70272544/f058531f-62bf-4ad2-8b70-45cd5c05d3f9)
![Screenshot 2024-06-07 at 2 51 36 PM](https://github.com/ThatOpen/engine_components/assets/70272544/b08a2c72-c7b3-4905-9a06-93c87efcf201)
![Screenshot 2024-06-07 at 2 50 45 PM](https://github.com/ThatOpen/engine_components/assets/70272544/a4d070e7-714c-4007-806b-1736f41f552f)

And about plan view it is not from top for me:
![Screenshot 2024-06-07 at 2 54 16 PM](https://github.com/ThatOpen/engine_components/assets/70272544/cd07ccc5-cf96-46f1-b15d-5c6d91347433)

Finally, I wanted to add the latest version but:
 No matching version found for @thatopen/components@^2.1.0.

### System Info 💻

```shell
mac book
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

![Screenshot 2024-06-09 at 10 04 16 AM](https://github.com/ThatOpen/engine_components/assets/70272544/56cd8659-8855-4100-9766-0ee78ebbf4ed)

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi! Please, from now own, create a separate issue per problem / question.

1. This is how the culler works. It takes a bit to load all the geometry because it needs to process the visibility of all items. If you want the culler to be faster when navigating the model, you can update it each X seconds with setInterval or bind it to another events of the camera controls.

2. This is solved in the last version.
3. This is solved in the last version.

Cheers!
