### ISSUE TITLE
Deselect fragments when using multiselect

### ISSUE THREAD

**Issue by pstowasser01** [ThatOpen/engine_components#410]
### Description 📝

Like the title says it would be nice to be able to deselect fragments when they are already selected when using the multiselect feature.

### Suggested solution 💡

I would assume the best solution would be to add a check in the highlight() method inside the highlighter class, where you use the selected fragment from the raycaster and search for it inside the highlighter.selection.select set... If found, you can remove it from the set.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by pstowasser01** [comment]
In addition to that, it would be nice that clicking on no element (void) while having multiselect active (removePrevious false) results in keeping the highlighter.selection.select set instead of loosing it as it is right now (tested on the thatopen/components-front version 2.0.9)

**Comment by agviegas** [comment]
Available from `@thatopen/components-front@2.1.17`!


https://github.com/user-attachments/assets/00102ce5-7136-4ce4-af34-b018ee829117
