### ISSUE TITLE
Allow for control of decimal places shown on SimpleDimensionLine label.

### ISSUE THREAD

**Issue by ITIDanZero** [ThatOpen/engine_components#412]
### Description 📝

We were wanting to set the `units` property of `SimpleDimensionLine` to feet, and change the `scale` property accordingly so the numbers were correct.  However, the code that generates the label text will almost always show a large number of decimal places after it does the appropriate conversion.

### Suggested solution 💡

I was thinking maybe introduce another static property like `rounding` to allow a specification for the number of decimal places for the label, then change `getTextContext` to be something like
```
private getTextContent() {
    const calced_value = this._length / SimpleDimensionLine.scale
    const rounded_value = calced_value.toFixed(SimpleDimensionLine.rounding)
    return `${rounded_value} ${SimpleDimensionLine.units}`;
  }
```

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Available from `@thatopen/components-front@2.1.18`!
