### ISSUE TITLE
IFCSPACE elements are not classified properly in spatial relations (storeys)

### ISSUE THREAD

**Issue by maidi29** [ThatOpen/engine_components#414]
### Describe the bug 📝

I have an ifc model that contains IFCSPACEs inside IFCSTOREYs. The classifier does not properly classify them to a storey, they are not part of any storey what is good visible in the exploder.
The interesting thing is that the exact same models work in the example platform https://platform.thatopen.com/app 

How I classify:

```
fragments.onFragmentsLoaded.add(async (model) => {
        if (model.hasProperties) {
          await classifier.byIfcRel(
            model,
            WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE,
            'storeys',
          );
        }

        for (const fragment of model.items) {
          world.meshes.add(fragment.mesh);
        }

        world.scene.three.add(model);
        }
```

### Steps to reproduce 🔢

1. use an ifc model with storeys and spaces inside a storey
2. classify it by IFCRELCONTAINEDINSPATIALSTRUCTURE
3. use the exploder fragment and set it to active

### System Info 💻

```shell
Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.61
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by maidi29** [comment]
Update:
One difference is that the spaces are in their own collection, compared to the other elements that are correctly classified.
<img width="301" alt="image" src="https://github.com/ThatOpen/engine_components/assets/8269208/3c8daa2b-1f03-42b9-a790-f7c194a747c9">

It looks like the problem is inside the indexer. 
`const rels = indexer.getEntityRelations(model, expressID, 'ContainsElements'); ` I checked for the rels and the spaces are not contained.
But why are the then correctly handled by the example app https://platform.thatopen.com/app and also correctly assigned to the storey in the model tree?
Would be really nice to get the code of the example app or any other help :)

**Comment by maidi29** [comment]
Additionally, it is not possible to highlight/hover an ifc space with the highlighter. It looks like the spaces are not correctly processed?

**Comment by maidi29** [comment]
I realized that the spaces are not in relation IFCRELCONTAINEDINSPATIALSTRUCTURE but IFCRELAGGREGATES. So to get all elements including spaces I needed to to the following:

```
await classifier.byIfcRel(
      model,
      [WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE, WEBIFC.IFCRELAGGREGATES],
      'storeys',
    );
    
    async byIfcRel(group: FRAGS.FragmentsGroup, ifcRels: number[], systemName: string) {
    if (ifcRels.some((rel) => !IfcPropertiesUtils.isRel(rel))) return;
    ifcRels.forEach(async (rel) => {
      await IfcPropertiesUtils.getRelationMap(group, rel, async (relatingID, relatedIDs) => {
        const { name: relatingName } = await IfcPropertiesUtils.getEntityName(group, relatingID);
        for (const expressID of relatedIDs) {
          this.saveItem(group, systemName, relatingName ?? 'NO REL NAME', expressID);
        }
      });
    });
  }
```

**Comment by maidi29** [comment]
I realized that the spaces are not in relation IFCRELCONTAINEDINSPATIALSTRUCTURE but IFCRELAGGREGATES. So to get all elements including spaces I needed to to the following:

```
await classifier.byIfcRel(
      model,
      [WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE, WEBIFC.IFCRELAGGREGATES],
      'storeys',
    );
    
    async byIfcRel(group: FRAGS.FragmentsGroup, ifcRels: number[], systemName: string) {
    if (ifcRels.some((rel) => !IfcPropertiesUtils.isRel(rel))) return;
    ifcRels.forEach(async (rel) => {
      await IfcPropertiesUtils.getRelationMap(group, rel, async (relatingID, relatedIDs) => {
        const { name: relatingName } = await IfcPropertiesUtils.getEntityName(group, relatingID);
        for (const expressID of relatedIDs) {
          this.saveItem(group, systemName, relatingName ?? 'NO REL NAME', expressID);
        }
      });
    });
  }
```

**Comment by HoyosJuan** [comment]
Hey @maidi29! 

Just use [Classifier.spatialStructure](https://docs.thatopen.com/api/@thatopen/components/classes/Classifier#byspatialstructure) which takes care of that. It uses the [IfcRelationsIndexer ](https://docs.thatopen.com/Tutorials/Components/Core/IfcRelationsIndexer)under the hood.

**Comment by maidi29** [comment]
> Just use [Classifier.spatialStructure](https://docs.thatopen.com/api/@thatopen/components/classes/Classifier#byspatialstructure) which takes care of that. It uses the [IfcRelationsIndexer ](https://docs.thatopen.com/Tutorials/Components/Core/IfcRelationsIndexer)under the hood.

Thanks for your reply @HoyosJuan.
This did not work for me as the spaces are not in spatial relation but in IFCRELAGGREGATES. I don't know if this is a standard or just the case for the ifc models that I used so far but I came up with the above solution to add them to the storeys  and closed the issue 👍
