### ISSUE TITLE
Delete measurement remains red small rectangles

### ISSUE THREAD

**Issue by shahbaziparisa** [ThatOpen/engine_components#415]
### Describe the bug 📝

Hi
I use different measurements . When I use deleteall or delete for removing measurements It has some problem.
a red rectangle that was used for snapping to corners remains in the scene.
![Screenshot 2024-06-09 at 12 23 40 PM](https://github.com/ThatOpen/engine_components/assets/70272544/d3a803a5-dd14-4b8a-ae1c-58248f66a8a2)

### Steps to reproduce 🔢

....

### System Info 💻

```shell
...
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

...

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from 2.1.1. If not, feel free to comment a minimal reproducible example that we can use to see remaining issues. Cheers!

https://github.com/ThatOpen/engine_components/assets/56475338/653e3212-94ec-4b51-a182-87c6afd72c8e
