### ISSUE TITLE
Calling edges.update(true) while ClippingPlane (EdgesPlane) breaks the edges styles

### ISSUE THREAD

**Issue by maidi29** [ThatOpen/engine_components#419]
### Describe the bug 📝

I am entering the plans view by `plans.goTo(...)`. It sets a clipping plane to display the current storey plan.
When I call edges.update now all the styles are still stored properly but the view gets destroyed.

```
plans.goTo(planId, true);
      setTimeout(() => {
        edges.update(true);
      }, 100);
```

What I am actually trying to do is to highlight an object that has a clipping style active --> the mesh color is not updated because the mesh of the edges.style is blocking(?) this.

The expected behaviour is that the displayed styles are updated with the current displayed styles

### Reproduction ▶️

https://docs.thatopen.com/Tutorials/Components/Front/ClipEdges

### Steps to reproduce 🔢

1. checkout [the demo for plans component with edges style](https://docs.thatopen.com/Tutorials/Components/Front/ClipEdges)
2. go into plans view
3. call `edges.update(true)` (you don't even have to make changes in the style - the colors break immediately)

### System Info 💻

```shell
Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.62
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components-front@2.1.7`. Cheers!
