### ISSUE TITLE
[Bug]: `IfcAPI` is memory leaking

### ISSUE THREAD

**Issue by shota-hamamatsu** [ThatOpen/engine_components#424]
### What happened?
- `IfcAPI` is not disposing memory properly.
- This can be seen in the official demo.
  (https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader#-cleaning-memory)

### Reproduction scenario
1. Click the `Load IFC` button.
2. Click the `Dispose flagments` button
- You can see that the memory graph in the upper left corner is not decreasing.
3. Click the `Load IFC` button.
- You can see that the memory graph in the upper left corner is increasing.

### Version

0.0.54

### What browsers are you seeing the problem on?

Chrome

**Comment by agviegas** [comment]
@beachtom is that method exposed in web-ifc 0.0.55? I can't find it

![image](https://github.com/user-attachments/assets/b9dada0d-aac5-48ea-b90d-2f87703cfed9)

**Comment by beachtom** [comment]
Ah - no - I just create 0.0.56 which has it

**Comment by agviegas** [comment]
Solved from version `@thatopen/components@2.1.3` and `@thatopen/components-front@2.1.4`. I'll publish later today. Let me know otherwise!
