### ISSUE TITLE
Camera in not working fine, while zoom in it gets slow

### ISSUE THREAD

**Issue by smirallas** [ThatOpen/engine_components#425]
### Describe the bug 📝

I load a large model and while moving arround the camera stops working fine

### Reproduction ▶️

https://youtu.be/s6CLeKk-2e8

### Steps to reproduce 🔢

Just load a model and zoom in

### System Info 💻

```shell
-
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey, we use [yomotu's camera controls](https://github.com/yomotsu/camera-controls) to control the camera. So you have 3 options:

- To configure the controls to have [infinity dolly](https://yomotsu.github.io/camera-controls/examples/infinity-dolly.html) and adjust its speed / sensitivity to your needs.
- To use the [civil navigation tools](https://docs.thatopen.com/Tutorials/Components/Front/Civil3DNavigator) that we provide to allow your user to go through your road.
- To control the camera yourself to adjust it to your needs.

Hope this helps!
