### ISSUE TITLE
OBCF.Highlighter just recolor, but not highlight

### ISSUE THREAD

**Issue by VictorTrumpel** [ThatOpen/engine_components#426]
### Describe the bug 📝

Why does the highlighter not highlight, but simply recolor?
If I highlight a chair, it won't be visible throw the walls the way it worked before.

Example from docks:
https://thatopen.github.io/engine_components/examples/Highlighter/
https://docs.thatopen.com/Tutorials/Components/Front/Highlighter

How to make it so that the backlight not only recolors, but also shines through?

### Reproduction ▶️

https://thatopen.github.io/engine_components/examples/Highlighter/

### Steps to reproduce 🔢

https://thatopen.github.io/engine_components/examples/Highlighter/

### System Info 💻

```shell
https://thatopen.github.io/engine_components/examples/Highlighter/
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
You are right! We temporarily removed the highlight feature for the new refactor, as the way the highlight works has changed drastically. This is not a but. But don't worry, we'll put it back the next milestone. I'll remove the `bug` flag and add a `feature` flag instead

**Comment by vishal-eartheon** [comment]
Hi @agviegas any update on this issue/feature? I noticed this as well in my recent migration to the new refactor.

**Comment by agviegas** [comment]
I'll do it asap. We have few hands. Hopefully these weeks, I'll post any updates here

**Comment by vishal-eartheon** [comment]
Thanks for the update @agviegas 

Shall I take it up and create a pull request once done? I would like to contribute if possible.

**Comment by VictorTrumpel** [comment]
For temporary solution I use this code. Maybe It will helpful for somebody
```typescript
const highlightMats = {
  default: new MeshBasicMaterial({
    color: '#674db3',
    depthTest: false,
    opacity: 0.8,
    transparent: true,
  }),
};

const highlightFragment = (fragmentMap: FragmentIdMap) => {
  const components = new Components();
  const fragmentsManager = components.get(OBC.FragmentsManager);
  for (const fragID in fragmentMap) {
    const fragment = fragmentsManager.list.get(fragID);
    if (!fragment) continue;
    fragment.mesh.material = [highlightMats.default];
  }
};
```

It looks like this
<img width="559" alt="скрин 3" src="https://github.com/user-attachments/assets/efbb9f61-fb63-419a-89da-b77ff0eb99aa">

![скрин 1](https://github.com/user-attachments/assets/694b59ea-e8f1-41ea-aa49-68d2f349950f)
![скрин 2](https://github.com/user-attachments/assets/1f86edf3-5824-40b0-8b42-e039ab4528c1)

**Comment by vishal-eartheon** [comment]
Yeah, this workaround is good.

But, one extra thing it probably needs is to make a copy of the mesh and highlight **the copy** so that the original mesh retains it materials once the highlight is disabled. The copy can be deleted on highlight removal.
