### ISSUE TITLE
Can't manually set version of serializer

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#430]
### Describe the bug 📝

I'm looking for a version that runs most stably without conflicts.

1. @thatopen/fragments

-    Normally I declare a variable as follows 
```
 private _groupSerializer = new FRAGS.Serializer();
this._groupSerializer.version = 1;
```
When i do 
```
const buffer = this._groupSerializer.export(group);
```
It thrown error 
![image](https://github.com/ThatOpen/engine_components/assets/89787521/178c72db-1157-4e65-83cd-dd8d478390aa)
2. I use the [templates](https://github.com/ThatOpen/engine_templates/tree/main/templates/vanilla).
```
"dependencies": {
    "@preact/signals-react": "^2.0.2",
    "@thatopen/components": "^2.0.19",
    "@thatopen/components-front": "^2.0.19",
    "@thatopen/fragments": "^2.0.7",
    "@thatopen/ui": "^2.0.8",
    "@thatopen/ui-obc": "^2.0.12",
    "jszip": "3.10.1",
    "three": "0.160.1",
    "web-ifc": "0.0.55"
  }
```
I did something for tiler
```
  private wasm = {
    path: "https://unpkg.com/web-ifc@0.0.55/",
    absolute: true,
    logLevel: WEBIFC.LogLevel.LOG_LEVEL_OFF as WEBIFC.LogLevel | undefined,
  } as const;

  private excludedCategories = new Set([
    WEBIFC.IFCSPACE,
    WEBIFC.IFCREINFORCINGBAR,
    WEBIFC.IFCOPENINGELEMENT,
  ]);
async streamIfc(buffer: Uint8Array) {
    /* ==========  IfcGeometryTiler  ========== */
    const tiler = this.components.get(OBC.IfcGeometryTiler);
    tiler.settings.wasm = this.wasm;
    tiler.settings.autoSetWasm = false;
    tiler.settings.webIfc = this.webIfc;
    tiler.settings.excludedCategories = this.excludedCategories;
    tiler.settings.minGeometrySize = 10;
    tiler.settings.minAssetsSize = 1000;
    tiler.onAssetStreamed.reset();
    tiler.onGeometryStreamed.reset();
    tiler.onIfcLoaded.reset();

    let assets: OBC.StreamedAsset[] = [];
    let geometries: OBC.StreamedGeometries;
    let groupBuffer: Uint8Array;
    let geometryFilesCount = 0;
    const onSuccess = async () => {
      const customIfcStreamer = this.components.get(CustomIfcStreamer);
      if (!customIfcStreamer) return;

      if (
        assets.length === 0 ||
        geometries === undefined ||
        groupBuffer === undefined
      )
        return;
      const settings = {assets, geometries} as OBF.StreamLoaderSettings;
      await customIfcStreamer.load(settings, groupBuffer, true);
    };

    const streamGeometry = (
      data: OBC.StreamedGeometries,
      buffer: Uint8Array
    ) => {
      const geometryFile = `small.ifc-processed-geometries-${geometryFilesCount}`;
      if (geometries === undefined) geometries = {};
      if (!this.streamedBufferFiles) this.streamedBufferFiles = {};
      for (const id in data) {
        if (!geometries[id]) geometries[id] = {...data[id], geometryFile};
      }
      if (!this.streamedBufferFiles[geometryFile])
        this.streamedBufferFiles[geometryFile] = buffer;
      geometryFilesCount++;
    };

    tiler.onAssetStreamed.add(async (assetItems: OBC.StreamedAsset[]) => {
      assets = [...assets, ...assetItems];
      await onSuccess();
    });

    tiler.onGeometryStreamed.add(
      async ({
        data,
        buffer,
      }: {
        data: OBC.StreamedGeometries;
        buffer: Uint8Array;
      }) => {
        streamGeometry(data, buffer);
        await onSuccess();
      }
    );

    tiler.onIfcLoaded.add(async (group: Uint8Array) => {
      groupBuffer = group;
      await onSuccess();
    });
    await tiler.streamFromBuffer(buffer);
  }
```
Then i customized [this class](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/fragments/IfcStreamer/index.ts). and load 
```
/**
   * Loads a new fragment group into the scene using streaming.
   *
   * @param settings - The settings for the new fragment group.
   * @param coordinate - Whether to federate this model with the rest.
   * @param properties - Optional properties for the new fragment group.
   * @returns The newly loaded fragment group.
   */
  async load(
    settings: OBF.StreamLoaderSettings,
    groupBuffer: Uint8Array,
    coordinate: boolean
  ) {
    const {assets, geometries} = settings;
    const fragments = this.components.get(OBC.FragmentsManager);
    const group = fragments.load(groupBuffer, {coordinate});
    this.world.scene.three.add(group);
    const {opaque, transparent} = group.geometryIDs;
    for (const [geometryID, key] of opaque) {
      const fragID = group.keyFragments.get(key);
      if (fragID === undefined) {
        throw new Error("Malformed fragments group!");
      }
      this.fragIDData.set(fragID, [group, geometryID, new Set()]);
    }
    for (const [geometryID, key] of transparent) {
      const fragID = group.keyFragments.get(key);
      if (fragID === undefined) {
        throw new Error("Malformed fragments group!");
      }
      this.fragIDData.set(fragID, [group, Math.abs(geometryID), new Set()]);
    }
....
```
It did not work. So i try to debug at 
```
const {opaque, transparent} = group.geometryIDs;
console.log(group.geometryIDs);
```
This is result 
![image](https://github.com/ThatOpen/engine_components/assets/89787521/4013cecb-074a-4f76-aa0c-65d57773094e)
Then i tried to customized [this class](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/fragments/IfcGeometryTiler/index.ts) (i mean i copied exactly). and debug [at this](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/fragments/IfcGeometryTiler/index.ts#L265-L270). 
And this is result :
![image](https://github.com/ThatOpen/engine_components/assets/89787521/0b0e0344-61d4-44c2-8f85-7d4a59cd9759)

After that i tried to change for wasmmodule url :
```
  private wasm = {
    path: "https://unpkg.com/web-ifc@0.0.53/",
    absolute: true,
    logLevel: WEBIFC.LogLevel.LOG_LEVEL_OFF as WEBIFC.LogLevel | undefined,
  } as const;
```
this result for web-ifc@0.0.53 
![image](https://github.com/ThatOpen/engine_components/assets/89787521/9d6a1941-0fcc-407b-90ee-8c9fdfddebd3)
this result for web-ifc@0.0.54 
![image](https://github.com/ThatOpen/engine_components/assets/89787521/737e8438-8544-4ee1-aa10-7ac235d1204b)
this result for web-ifc@0.0.55
![image](https://github.com/ThatOpen/engine_components/assets/89787521/a925091e-7a6d-4a29-ae3a-fdb7f6689921)
3. openbim-components@1.5.0
 So i downgrated to older version
```
 "openbim-components": "^1.5.0",
  "bim-fragment": "^1.5.0",
  "web-ifc": "^0.0.53" 
```
Every thing worked. [this file for testing](https://drive.google.com/file/d/175L2PuXtxXX4Nit35hM6QT8rrGrYc43i/view?usp=sharing).

### System Info 💻

```shell
Chrome
Win10
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
@RyugaRyuzaki I think you are mixing things up. The original bug (changing the version of the serializer) is the problem. I'll change the name of the issue.

**Comment by RyugaRyuzaki** [comment]
> @RyugaRyuzaki I think you are mixing things up. The original bug (changing the version of the serializer) is the problem. I'll change the name of the issue.

@agviegas i also mean when we change @web-ifc version the output also change as i show the results.

**Comment by agviegas** [comment]
@RyugaRyuzaki you have to create one issue per problem. Otherwise it's really hard to track things down. I've solved the serializer error in `@thatopen/fragments@2.0.8`. If you have an issue with web-ifc versioning in the libraries, please create a separate issue.
