### ISSUE TITLE
enable customLocateFileHandler function for webIfc in IfcLoader

### ISSUE THREAD

**Issue by cytostatic** [ThatOpen/engine_components#431]
### Description 📝

There is already an option in ifc-fragment-settings class to provide a custom file handler function for the WASM module (customLocateFileHandler).
This setting should be used in readIfcFile method.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components@2.1.20`!

**Comment by cytostatic** [comment]
Thank you very much
