### ISSUE TITLE
Hider not saving original colors for some elements

### ISSUE THREAD

**Issue by MadsHolten** [ThatOpen/engine_components#434]
### Describe the bug 📝

I'm using the Hider along with the Highlighter in a tiled model. When I reset the hider I have the problem that for some elements, the original color was  not saved. Typically for windows that consist of multiple fragments/materials. The error originates from the [Fragment class](https://github.com/ThatOpen/engine_fragment/blob/32f087ec3b6248963c8cc93e36f383a317d7fe6d/packages/fragments/src/fragment.ts#L493), but I suspect it is closer related to the tile loading.

If I ignore the thrown error, the result is that the hidden element re-appears, but with the highlight color.

### Steps to reproduce 🔢

1. Load model using IfcStreamer
2. Select element using Highlighter
3. Hide or isolate selected element using Hider
4. Unhide all using set(true) on Hider
5. Sometimes succeeds, sometimes fails

### System Info 💻

```shell
MacBook Pro M3
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @MadsHolten this might be already solved in the latest version. The reason might be that that trying to set the visibility of a fragment passing IDs that it doesn't have returned an error before. Now it just skips them. 

So I can't reproduce it anymore adding the following code to the [streamer tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer):

```ts

const highlighter = components.get(OBCF.Highlighter);
highlighter.add("example", new THREE.Color(1, 0, 0));
const hider = components.get(OBC.Hider);

loader.onFragmentsLoaded.add((frags) => {
  const fragments = components.get(OBC.FragmentsManager);
  const model = Array.from(fragments.groups.values())[0];
  const map = model.getFragmentMap([186]);
  const keys = new Set(Object.keys(map));
  let found = false;
  for (const frag of frags) {
    if (keys.has(frag.id)) {
      found = true;
    }
  }

  if (found) {
    highlighter.highlightByID("example", map);
  }

  hider.isolate(map);
  hider.set(true);
});
```

This is the result:

https://github.com/user-attachments/assets/6b806cd5-737f-4dea-931f-253ed9a6588d

Now, just FYI, if you want to hide elements using streaming, there is a [specific setVisibility method ](https://docs.thatopen.com/api/@thatopen/components-front/classes/IfcStreamer#setvisibility) that makes it simpler, and also avoids streaming fragments that are fully invisible. We could add an `isolate` method in the future if that's useful.

As for highlighting, I'm going to take care of [this feature](https://github.com/ThatOpen/engine_components/issues/435) by adding a `staticFragments` property to the streamer that are forced to be streamed and never unloaded from memory until removed from that list. That should make it easier, as you won't have to update the highlighter in the `onFragmentsLoaded` event, and all highlighted elements will be forced to be visible. That will probably also help you.

Let me know if the issue persists on your end. Cheers!

**Comment by MadsHolten** [comment]
Sorry for late reply. I can confirm that the problem seems to be solved in the latest version.

And thanks for the hint on the setVisibility method. This solved another issue I had with elements behind a hidden element [not being loaded from the culler](https://people.thatopen.com/c/ask-the-community/culler-hider#comment_wrapper_40811461).

I am looking forward to the staticFragments property of the streamer since this will solve many problems I'm facing when trying to control styling of the streamed scene! This is also needed when isolating objects in the scene. I tried to achieve that with the setVisibility (1. use hider to hide all, 2. use setVisibility to make specific elements visible) but it only works until you pan the scene and new elements become visible..
