### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'LOG_LEVEL_OFF')

### ISSUE THREAD

**Issue by suryakumara** [ThatOpen/engine_components#437]
### Describe the bug 📝

I followed the entire series of IFC loading schemes but got an error like this.

```sh
import * as THREE from 'three';

import * as OBC from '@thatopen/components';

class IFCDevAgent {
  ifcModelData: Array<{
    position: { x: number; y: number; z: number };
    rotation: { heading: number; pitch: number; roll: number };
    scale: number;
  }>;

  originOffset: { x: number; y: number; z: number } = { x: 0, y: 0, z: 0 };

  scene: OBC.SimpleScene;

  world: OBC.SimpleWorld<OBC.SimpleScene, OBC.SimpleCamera, OBC.SimpleRenderer>;

  components: OBC.Components;

  fragments: OBC.FragmentsManager;

  fragmentIfcLoader: OBC.IfcLoader;

  onProgress?: (progress: number) => void;

  constructor(
    world: OBC.SimpleWorld<
      OBC.SimpleScene,
      OBC.SimpleCamera,
      OBC.SimpleRenderer
    >,
    loadingManager: THREE.LoadingManager,
    components: OBC.Components,
    config?: { originOffset?: { x: number; y: number; z: number } },
    onProgress?: (progress: number) => void,
  ) {
    this.ifcModelData = [];
    this.scene = world.scene;
    this.world = world;
    this.components = components;
    this.originOffset = config?.originOffset ?? { x: 0, y: 0, z: 0 };

    this.fragmentIfcLoader = this.components.get(OBC.IfcLoader);
    this.fragments = this.components.get(OBC.FragmentsManager);

    this.onProgress = onProgress;
  }

  setOriginOffset(x: number, y: number, z: number) {
    this.originOffset = { x, y, z };
  }

  async setup() {
    await this.fragmentIfcLoader.setup();
    const excludedCats = [
      WEBIFC.IFCTENDONANCHOR,
      WEBIFC.IFCREINFORCINGBAR,
      WEBIFC.IFCREINFORCINGELEMENT,
    ];

    for (const cat of excludedCats) {
      this.fragmentIfcLoader.settings.excludedCategories.add(cat);
    }
    this.fragmentIfcLoader.settings.webIfc.COORDINATE_TO_ORIGIN = true;
  }

}

export default IFCDevAgent;

```

### Steps to reproduce 🔢

1. npm install 

### System Info 💻

```shell
Browser : Chrome
```

### Used Package Manager 📦

pnpm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @suryakumara this was fixed in the latest version of the libraries. You can find a [step-by-step tutorial here](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader) and the [full source here](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/fragments/IfcLoader/example.ts). Let us know if the issue persists. Don't forget to also update web-ifc to the version [specified by the peer dependency](https://github.com/ThatOpen/engine_components/blob/main/packages/core/package.json). Cheers!
