### ISSUE TITLE
Creating new Pset in IFC4X3_ADD2

### ISSUE THREAD

**Issue by Can-Gr** [ThatOpen/engine_components#438]
### Describe the bug 📝

I am creating new pset in IFC4X3_ADD2 file but it gives me error of **_Cannot read properties of undefined (reading 'IfcGloballyUniqueId')_**.

`const { pset } = await propertiesManager.newPset(model, "New Field");`

I tried the same code to create pset in IFC4, it works as expected and creates a new pset.

### System Info 💻

```shell
Browser : Chrome

Packages 
@thatopen/components: ^2.0.20,
@thatopen/components-front": ^2.0.19,
@thatopen/ui: ^2.0.8,
@thatopen/ui-obc": ^2.0.12,
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @Can-Gr! This was already solved in @thatopen/components@2.1.5. Closing this!

**Comment by Can-Gr** [comment]
Thank you very much @HoyosJuan ! It's working!

**Comment by Can-Gr** [comment]
After the library updated to its latest version, adding **Pset** doesn’t work anymore.

It gives no error when code runs but when I download the model I can’t see the new **Pset** or I can’t even download the file in some versions (IFC4X3_ADD2) it gives me error of :
**Download failed: TypeError: Cannot read properties of undefined (reading 'IfcRelDefinesByProperties')**

Old versions of library are :   
    "@thatopen/components": "^2.1.21",
    "@thatopen/components-front": "^2.1.23",
    "@thatopen/ui": "^2.1.3",
    "@thatopen/ui-obc": "^2.1.6",

**Comment by HoyosJuan** [comment]
Hey @Can-Gr! I'm testing this right now with a IFC4X3_ADD2 model and have created (and downloaded) the pset in the model successfully. 🤔 How are you creating the pset?

**Comment by HoyosJuan** [comment]
I've just realized the pset and the properties gets created... but they are not assigned to the elements. Is that the same behavior you have?

**Comment by Can-Gr** [comment]
Hey @HoyosJuan! I can create new pset, it's property and value to that property and assign it to the element successfully. Because when I check pset properties with model.getProperties of selected element, after I get the psets of that element with indexer.getEntityRelations, I can see everything. 

And then I download the new model with a button. This works in every version(so far) except IFC4X3_ADD2.

**Comment by HoyosJuan** [comment]
Got i! Discovered the problem. Is solved now and it's already available in `@thatopen/components@2.3.14`. Let me know! Will close this.

**Comment by Can-Gr** [comment]
Hey @HoyosJuan, thank you, now I can create pset and download it and new pset is visible in the right element with right value.

However.. In any version of IFC, when I create a new pset and then delete it (which deletes successfully in the model) and then download it, I receive error of :

**Download failed: RuntimeError: memory access out of bounds
    at web-ifc.wasm:0xcb64c
    at web-ifc.wasm:0xca2a2
    at Object.RemoveLine (eval at newFunc (web-ifc-api.js:6010:1), <anonymous>:9:1)
    at IfcAPI2.DeleteLine (web-ifc-api.js:72239:1)
    at me.saveToIfc (index.mjs:11363:1)
    at async downloadFile** 
    
When I delete any existing pset, which comes with the model, and then download it, there's no error. 

I've tested it with different versions and sizes.

**Comment by HoyosJuan** [comment]
Hey @Can-Gr! Seems to be a different problem than the one from this issue. May you create another different issue with this, please? Thanks!

**Comment by Can-Gr** [comment]
Hi @HoyosJuan, alright I've opened it.
