### ISSUE TITLE
Customizable Vertex Picker for AngleMeasurement, AreaMeasurement, and LengthMeasurement Tools

### ISSUE THREAD

**Issue by Ajaylalwani01** [ThatOpen/engine_components#443]
### Description 📝

Enable to change Vertex Picker style from red box to circle and also enable customization for its color and size.

### Suggested solution 💡

Increased flexibility and user control over the measurement process.
Enhanced user experience for various workflows and also aligned with the selected custom theme.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
The vertex picker preview is just an HTML element that can be controlled with CSS. Now you can add the following CSS class to your app to control the picker: `.default-vertex-picker`. You have to use the `!important` flag for this to work. For example:

https://github.com/user-attachments/assets/f929ef68-25d7-4192-a957-64419ae10eb9

Available from `@thatopen/components-front@2.1.20`.
