### ISSUE TITLE
Chrome 2GB arrayBuffer limit

### ISSUE THREAD

**Issue by vishal-eartheon** [ThatOpen/engine_components#445]
### Describe the bug 📝

I encountered something when trying to parse huge IFC files. I have a IFC file with size bigger than 2.5GB and was not able to upload it and process the file. 

Chrome spit out an error with the message "The requested file could not be read, typically due to permission problems after a reference to a file was acquired".

I searched for similar issues online and came across a still unsolved Chromium issue from 3 years back: https://issues.chromium.org/issues/40055619

Is this something we can solve by splitting the IFC file into multiple array buffers and feeding it to the "IfcLoader", or is there any other way that I have missed?

### Steps to reproduce 🔢

1. Setup a project as usual.
2. Try uploading a IFC file bigger than 2.15 GB.

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (28) x64 Intel(R) Core(TM) i7-14700K
    Memory: 23.45 GB / 31.77 GB
Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Local\pnpm\pnpm.EXE
Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

pnpm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @vishal-eartheon ! For bigger IFC files we strongly recommend using the [streamer](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer) workflow. Did you check it out?

Even if you manage to make the IfcLoader to read your file, the waiting time will be considerable. The streamer is specifically designed to handle these kind of files with ease. Cheers!

**Comment by vishal-eartheon** [comment]
Ah okay, thanks @agviegas ! I understand the streaming workflow now.

But, I still have one doubt with this workflow. Sorry if it has already been solved. I have been combing through the docs trying to find the answer for this. 😅 

Let's say I have a web app that converts a IFC file to streaming tiles, and let's say that the file the user uploads is bigger than 2.5 GB. From what I understood of the [Chromium issue](https://issues.chromium.org/issues/40055619) that I had linked above, Google Chrome cannot convert a file of that size to an arrayBuffer because of it's memory allocation implementation.

So, to circumvent that, we might have to split a huge IFC file into chunks, and then create an arrayBuffer from each chunk, and then hand this "array of arrayBuffers" to the IfcGeometryTiler, right? Would that be the approach to get around this problem or am I missing something simpler?

**Comment by agviegas** [comment]
@vishal-eartheon you can use the stream converter to tiles in node.js (the core of the library is 100% node compatible), so the conversion can happen in a backend machine, where that issue shouldn't happen! We also have [this method](https://docs.thatopen.com/api/@thatopen/components/classes/IfcGeometryTiler#streamfromcallback) which allows you to read the file as the library gets to it. Something like this:

```ts
  const input = fs.openSync(`./path/to/your/file.ifc`);
  const callback = (offset, size) => {
    let data = new Uint8Array(size);
    let bytesRead = fs.readSync(input, data, 0, size, offset);
    if (bytesRead <= 0) return new Uint8Array(0);
    return data;
  };
  
  //... 
  
  await geometryTiler.streamFromCallBack(callback);
```

**Comment by vishal-eartheon** [comment]
Ah, makes sense. Thank you for the help. Closing the issue now.
