### ISSUE TITLE
The position of Marker is mistake.

### ISSUE THREAD

**Issue by cyling250** [ThatOpen/engine_components#446]
### Describe the bug 📝

I am using OBCF.Marker to add some marks in my BIM. However, they don't seem to be in their place. For example, part of my code is shown as follows:
```ts
// something
setLabel(){
  const marker = components.get(OBCF.Marker);
  // Here, I want to add a lable at position (0,0,0)
  marker.create(world, "🚀", new THREE.Vector3(0,0,0));
}
// something
```
However, the behavior is shown as the following picture:
![image](https://github.com/user-attachments/assets/35ed9d9c-e730-466e-a31b-829799b2f1de)

The labels are NOT at the right position.

However, I have fixed this.
https://github.com/ThatOpen/engine_components/blob/bb43eefbd5a178828944c6725451e88e9d46fb27/packages/front/src/core/Marker/index.ts#L168
In this line, Marker used "span", it may cause the position mistake. After I change it into "div", the bug is fixed. But I don't know why.

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400
    Memory: 6.93 GB / 15.81 GB
  Binaries:
    Node: 20.11.0 - D:\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - D:\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager 📦

pnpm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi, this is due to the HTML - CSS configuration of your app. The markers are displayed on a div that should be placed on top of the canvas that makes the scene. If you check out [the marker tutorial](https://docs.thatopen.com/Tutorials/Components/Front/Marker), you'll see that they are in place. [Here](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/core/Marker/example.html) you can find the HTML we use for that example. Cheers!
