### ISSUE TITLE
Loading several IFC files

### ISSUE THREAD

**Issue by matilde-mantoan-efm** [ThatOpen/engine_components#447]
### Describe the bug 📝

We are developing an Angular 14 application for managing multiple ifc files and we have an issue with the loading of several files
The application has an Observable that emit a list of ifc files one at a time, and sent it to the ifcLoader.load() function. 

```
zip(from(ifcFiles), interval(2000)).pipe(map(([file]) => file)).subscribe(res => {
      this.commonService.ifcFilesToLoad.next(res);
    })
```

```
    this.commonService.ifcFilesToLoad.subscribe({
      next: (file) => {
        this.loadData(file).then(res => {
          this.models.push(res);
        });
      }
    })
```

```
loadData(name?: string) {
    const file = await fetch(name);
    const data = await file.arrayBuffer();
    const buffer = new Uint8Array(data);
    const model: FragmentsGroup = await this.ifcLoader.load(buffer);
    return model;
  }
```

Up to 4/5 files everything is ok, but when we load 6 or more ifc files, randomly the app breaks in the OpenModule function of web-ifc-api.js, because wasmModule is undefined. 
Whe tried to avoid it using an interval of 2s between the ifc files but it didn't resolve the problem.

![image](https://github.com/user-attachments/assets/5ba22000-f698-4921-827b-f37b51c4bbfc)

Thank you

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.35 GB / 15.73 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @matilde-mantoan-efm is it possible that you are loading the models in parallel, instead of waiting for one to load before loading the next one?

**Comment by matilde-mantoan-efm** [comment]
Hi, we found out that the chain of the ifc emitted from ifcFilesToLoad was not perfectly synchronized with the chain of the models passed in the load method, so the biggest files were emitted before the 2s and broke the flow. It seems we resolved with a concatMap! Thank you!
