### ISSUE TITLE
Allow to define selectable/hoverable categories in the highlighter

### ISSUE THREAD

**Issue by HoyosJuan** [ThatOpen/engine_components#448]
### Description 📝

Right now, the highlighter allows to select or hover everything. However, some use cases may require to only select certain categories of elements.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Done. Available from @thatopen/components-front@2.1.23`. Now doing something like this:

```ts
const classifier = components.get(OBC.Classifier);
classifier.byEntity(model);
const windows = classifier.find({ entities: ["IFCWINDOW"] });
highlighter.selectable.hover = windows;
```

This is the result:

https://github.com/user-attachments/assets/7c094823-2666-4976-83ec-1d49f7e9f4e1

**Comment by pstowasser01** [comment]
I am not seeing the "selectable" parameter anywhere in the repo and while running on 2.1.24 my highlighter does not support this. Am i missing anything?

**Comment by agviegas** [comment]
My bad, try version `@thatopen/components-front@2.1.25`!

**Comment by pstowasser01** [comment]
Thanks for the fast reply :) 
But now I'm getting an error from npm that ui-obc requires web-ifc@0.0.56 but components and components-front require web-ifc@0.0.57 is there a way to fix that on my end?

**Comment by agviegas** [comment]
Hum, can you try the latest versions? I updated the dependency on both
