### ISSUE TITLE
Issue using "@thatopen/components" when using watchify

### ISSUE THREAD

**Issue by lxrp-gis** [ThatOpen/engine_components#451]
### Describe the bug 📝

I using vscode typescript to create a viewer as outlined in
https://docs.thatopen.com/Tutorials/Components/Core/Worlds
mt tsconfig is as follows
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES5",
        "lib": [ "ES2016", "dom" ],
        "sourceMap": true,
        "esModuleInterop": false,
    },
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": true
}
which compiles successfully
When watchify (https://www.npmjs.com/package/watchify) runs the following error returns

SyntaxError: Unexpected token (15224:11) while parsing 
C:\xxxxxx\src\node_modules\web-ifc\web-ifc-api-node.js while parsing file: C:\C:\xxxxxx\src\node_modules\web-ifc\web-ifc-api-node.js

I know there is web-ifc-api.js which is probably the one to load, but not sure how to configure to ensure it uses web-ifc-api.js rather than web-ifc-api-node.js

Regards

Marco

### Steps to reproduce 🔢

import * as THREE from "three";
import * as OBC from "@thatopen/components";

const container = document.getElementById("container")!;
// DON'T FORGET TO DISPOSE IT WHEN YOU ARE DONE!
// Once you are done with your application, you need to dispose the Components instance to free up the memory. This is a requirement of Three.js, which can't dispose the memory of 3D related elements automatically.
const components = new OBC.Components();
const worlds = components.get(OBC.Worlds);
const world = worlds.create<
  OBC.SimpleScene,
  OBC.SimpleCamera,
  OBC.SimpleRenderer
>();

world.scene = new OBC.SimpleScene(components);
world.renderer = new OBC.SimpleRenderer(components, container);
world.camera = new OBC.SimpleCamera(components);

components.init();

const material = new THREE.MeshLambertMaterial({ color: "#6528D7" });
const geometry = new THREE.BoxGeometry();
const cube = new THREE.Mesh(geometry, material);
world.scene.three.add(cube);

world.scene.setup();

world.camera.controls.setLookAt(3, 3, 3, 0, 0, 0)

### System Info 💻

```shell
Windows 10 Enterprise
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi, this doesn't seem a bug with the library, but a problem configuring watchify. Indeed, you will need to make sure that you are using `web-ifc-api.js`, which is the file for frontend. Have you tried opening an issue in their repo?

**Comment by lxrp-gis** [comment]
Hi agviegas no I haven't yet. Thank you for the advice

**Comment by agviegas** [comment]
Closing this for now. If you find out that this is indeed an issue of our library (e.g. how we configure our package.json), let us know and we'll solve it!
