### ISSUE TITLE
Config optional to unloadLostGeometries and toHide when using culler for IfcStreamer.

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#453]
### Description 📝

Normally with large models doing "unloadLostGeometries" and "toHide" when using [fcStreamer.culler.onViewUpdated](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/fragments/IfcStreamer/index.ts#L151-L154)  is very good. However, there are many questions on the forum about those small models, can users see the entire model? Even though I have set culler.thresHold=1.

### Suggested solution 💡

from  [fcStreamer.culler.onViewUpdated](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/fragments/IfcStreamer/index.ts#L151-L154) We can set a optionalBoolean like disabledUnloadLostGeometries:boolean 

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @RyugaRyuzaki can't you just set `maxLostTime` to a very high number like `1000 * 60 * 60 * 24 * 1000`? That way, the library should never unload geometries that were lost

**Comment by RyugaRyuzaki** [comment]
> Hey @RyugaRyuzaki can't you just set `maxLostTime` to a very high number like `1000 * 60 * 60 * 24 * 1000`? That way, the library should never unload geometries that were lost

ok, i got it, keep in mind.

**Comment by shahbaziparisa** [comment]
> Hey @RyugaRyuzaki can't you just set `maxLostTime` to a very high number like `1000 * 60 * 60 * 24 * 1000`? That way, the library should never unload geometries that were lost

I added this 

```
 customIfcStreamer = components.get(CustomIfcStreamer);
    customIfcStreamer.world = world;
    customIfcStreamer.culler.threshold = 5;
    customIfcStreamer.culler.maxHiddenTime = 3000;
    customIfcStreamer.culler.maxLostTime = 1000 * 60 * 60 * 24 * 1000;
world.camera.controls.restThreshold = 0.25;
const updateCulling = () => {
      customIfcStreamer.culler.needsUpdate = true;
    };
    world.camera.controls.addEventListener("rest", updateCulling);
    world.camera.controls.addEventListener("controlstart", updateCulling);
    world.camera.controls.addEventListener("controlend", updateCulling);
    world.camera.controls.addEventListener("wake", updateCulling);

```
but when I was testing my Chrome was freezer and not usable I had to restart my laptop

https://github.com/user-attachments/assets/f4156592-bbc4-45cb-9016-3b0f6509dd98
