### ISSUE TITLE
IfcStreamer load multiple json files

### ISSUE THREAD

**Issue by leuyvo** [ThatOpen/engine_components#454]
### Description 📝

After tiling geometry, when I use IfcStreamer to load tilers to viewer, it has a option:
_loader.url = "https://thatopen.github.io/engine_components/resources/streaming/";_
What I understood is it will automatically detect all the tiler json files' url,
but what if I do not put all the tiler json files into one directory?
I can not load all the tiler json files by this approach.

### Suggested solution 💡

I recommend to manually declare the tiler json file urls, similar like:
_loader.urls=[ "url of tiler json file 1", "url of tiler json file 2", ...];_

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
@leuyvo I've made the loading process from custom URLs more flexible. Before, it worked like this:

```ts
class IfcStreamer {
  url: string;
  
  fetch: async (fullURL: string) => {
    // fullURL = this.url + fileName
    return fetch(fullURL)
  }
}
```

Now it works like this. 

```ts
class IfcStreamer {
  url: string;
  
  fetch: async (fileName: string) => {
    return fetch(this.url + fileName)
  }
}
```

This means that you can override the `IfcStreamer.fetch` function easily and append whichever URL you want to get the files. You will also need to override `FragmentsGroup.fetch` if you want to customize the URLs from which you get the properties. 

Available from `@thatopen/components-front@2.3.0-alpha.4` and `@thatopen/fragments@2.3.0-alpha.1`. Let me know if it doesn't work.
