### ISSUE TITLE
Camera controls broken if the zoom distance is too high

### ISSUE THREAD

**Issue by monetamattia** [ThatOpen/engine_components#456]
### Describe the bug 📝

Instantiating a SimpleScene with an OrthoPerspectiveCamera, when I zoom out until the grid almost disappears, if I try to zoom in again the camera freezes and in fact I can no longer approach the object in any way (unless I use the fit function). 

Note that I also encountered the same problem in the example in your OrthoPerspectiveCamera documentation: https://docs.thatopen.com/Tutorials/Components/Core/OrthoPerspectiveCamera

Video: https://filebin.net/e098jzfq1kmno5gs

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 6.85 GB / 31.64 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @monetamattia for the camera we just use [yomotsu's camera controls](https://github.com/yomotsu/camera-controls) without changing anything. As the code causing the issue is not ours, can you please open the issue there? 

If there's anything we can do to make this better, please let us know. Thanks!
