### ISSUE TITLE
Fragment loading fails with large IFC file

### ISSUE THREAD

**Issue by armadinho** [ThatOpen/engine_components#458]
### Describe the bug 📝

I try to do a fragment load with an IFC file that is 33 MB.
The error is at the web browser and is "Out of memory" in Chrome. I also tried in Firefox and the loading does not complete and ram utilization of Firefox keeps growing until 15-16 GB and more.

I tried it in my project but also tried to load it from the example at [https://docs.thatopen.com/Tutorials/UserInterface/OBC/ClassificationsTree](url) with exactly the same results.

At the code level I see that the loading is stuck at my code:
await `this.fragmentIfcLoader.load(buffer);

I am able to open this IFC file with Solibri just fine and also able to load it from the demo page of the web-ifc component here [https://thatopen.github.io/engine_web-ifc/demo/](url)

Thank you for the help !!!

### System Info 💻

```shell
npx: installed 1 in 8.361s

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
    Memory: 16.63 GB / 31.89 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @armadinho can you please send the model to antonio@thatopen.com? Thanks!

**Comment by agviegas** [comment]
Using the [IFC Loader tutorial](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader), it works at my end:


https://github.com/user-attachments/assets/b5d9a37d-9408-4ded-b718-eefabf2ef27d

**Comment by armadinho** [comment]
Hello again, after your post I did further research and the problem occurs when I do:
`fragmentClassifier.byPredefinedType(model);`

If I omit this everything is ok although with a low framerate.

**Comment by agviegas** [comment]
@armadinho the low framerate is because you need to use the [culler](https://docs.thatopen.com/Tutorials/Components/Core/Cullers). As for the classifier, what do you want to do exactly? If you want to classify by category, you an use byEntity as shown [here](https://docs.thatopen.com/Tutorials/Components/Core/Classifier#%EF%B8%8F-classifiying-the-bim-model).
