### ISSUE TITLE
I generated tile json files using IfcGeometriyTiler, but I don't know how to use these files

### ISSUE THREAD

**Issue by lvfeijian** [ThatOpen/engine_components#472]

**Comment by lvfeijian** [comment]
I generated tile json files using IfcGeometriyTiler, but I don't know how to use these files. Can someone tell me?
My requirement is to render the BIM model in a browser with construction information

**Comment by agviegas** [comment]
Hi @lvfeijian did you see the [tutorial in the docs](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer)?

**Comment by HoyosJuan** [comment]
Hey @lvfeijian, I suggest you use [community](https://people.thatopen.com/home) when having questions rather than issues or feature proposals. 💪

**Comment by lvfeijian** [comment]
ok，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Juan ***@***.***&gt;; 
发送时间: 2024年8月17日(星期六) 晚上11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ThatOpen/engine_components] I generated tile json files using IfcGeometriyTiler, but I don&#39;t know how to use these files (Issue #472)














 
Hey @lvfeijian, I suggest you use community when having questions rather than issues or feature proposals. 💪
