### ISSUE TITLE
npm i @thatopen/fragments errors

### ISSUE THREAD

**Issue by felipecordero** [ThatOpen/engine_components#473]
### Describe the bug 📝

Hi everyone!

I'm trying to restart my coding with these libraries. I'm working in an isolated npm environment. But it is not working

### Installing @thatopen/components

`npm i @thatopen/components`

Working!

### Installing  three

`npm i three`

> npm warn ERESOLVE overriding peer dependency
> npm warn While resolving: undefined@undefined
> npm warn Found: three@0.160.1
> npm warn node_modules/three
> npm warn   peer three@"^0.160.1" from @thatopen/components@2.1.27
> npm warn   node_modules/@thatopen/components
> npm warn     @thatopen/components@"^2.1.27" from the root project
> npm warn   4 more (@thatopen/fragments, camera-controls, three-mesh-bvh, the root project)
> npm warn
> npm warn Could not resolve dependency:
> npm warn peer three@"^0.160.1" from @thatopen/components@2.1.27
> npm warn node_modules/@thatopen/components
> npm warn   @thatopen/components@"^2.1.27" from the root project
> npm warn ERESOLVE overriding peer dependency
> npm warn While resolving: undefined@undefined
> npm warn Found: three@0.160.1
> npm warn node_modules/three
> npm warn   peer three@"^0.160.1" from @thatopen/components@2.1.27
> npm warn   node_modules/@thatopen/components
> npm warn     @thatopen/components@"^2.1.27" from the root project
> npm warn   4 more (@thatopen/fragments, camera-controls, three-mesh-bvh, the root project)
> npm warn
> npm warn Could not resolve dependency:
> npm warn peer three@"^0.160.1" from @thatopen/fragments@2.1.6
> npm warn node_modules/@thatopen/fragments
> npm warn   peer @thatopen/fragments@"~2.1.0" from @thatopen/components@2.1.27
> npm warn   node_modules/@thatopen/components
> 
> changed 1 package, and audited 8 packages in 1s

And a lot of warnings...

## Installing fragments:

`npm i @thatopen/fragments`

> npm error code ERESOLVE
> npm error ERESOLVE unable to resolve dependency tree
> npm error
> npm error While resolving: undefined@undefined
> npm error Found: three@0.167.1
> npm error node_modules/three
> npm error   three@"^0.167.1" from the root project
> npm error
> npm error Could not resolve dependency:
> npm error peer three@"^0.160.1" from @thatopen/fragments@2.1.6
> npm error node_modules/@thatopen/fragments
> npm error   @thatopen/fragments@"*" from the root project
> npm error
> npm error Fix the upstream dependency conflict, or retry
> npm error this command with --force or --legacy-peer-deps
> npm error to accept an incorrect (and potentially broken) dependency resolution.
> npm error
> npm error
> npm error For a full report see:

### Steps to reproduce 🔢

`npm i @thatopen/fragments`

### System Info 💻

```shell
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: undefined@undefined
npm error Found: three@0.167.1
npm error node_modules/three
npm error   three@"^0.167.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer three@"^0.160.1" from @thatopen/fragments@2.1.6
npm error node_modules/@thatopen/fragments
npm error   @thatopen/fragments@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: undefined@undefined
npm error Found: three@0.167.1
npm error node_modules/three
npm error   three@"^0.167.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer three@"^0.160.1" from @thatopen/fragments@2.1.6
npm error node_modules/@thatopen/fragments
npm error   @thatopen/fragments@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @felipecordero you need to install the libraries specified by the peer dependency of the packages. That means running `npm i three@0.160.1` . Cheers!

**Comment by felipecordero** [comment]
Thank you @agviegas !
I'll give a new try
