### ISSUE TITLE
Resources consumption

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_components#478]
### Describe the bug 📝

I noticed that in the new versions of thatopen (2.1) the CPU resource consumption for the Chrome browser increased significantly, overall fluidity and performance decreased compared to the previous version - "web-ifc-viewer": "1.0.213" (screen 1and2) - even some larger models about 5%, now I use "@thatopen/components": "2.1.27" with culler - depends on model – even several dozen percent (screen 3,4,5,6), examples below. 
What is the cause of this, can I somehow improve it? 
I'm loading frag files, will switching to tiles affect CPU usage or only memory?

### Steps to reproduce 🔢

Load frag files to thatopenviewer with culler
![1](https://github.com/user-attachments/assets/9f68f528-eef2-4b97-ab53-82dd40698c2f)
![2- stara wersja](https://github.com/user-attachments/assets/2c1c69e5-dccd-49e0-a95c-fa592ea2a7eb)
![3](https://github.com/user-attachments/assets/091b170f-39d8-467a-ac6e-135d3bc5f897)
![4](https://github.com/user-attachments/assets/3af4055d-fd4a-4d0b-befa-fd9620d47ab6)
![5](https://github.com/user-attachments/assets/4d38c2a7-a197-4b79-bda0-4e47d1393d27)
![6](https://github.com/user-attachments/assets/853761df-f7bd-425f-9be1-1632ba7be3e5)

### System Info 💻

```shell
"@thatopen/components": "2.1.27"
"@thatopen/components-front": "2.1.27",
"@thatopen/fragments": "2.1.6",
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @robertbiskup,

In general terms, the use of fragments (with the culler) in the latest version should be better than the previous libraries. One reason behind the performance degradation that you describe is that the previous libraries merged some geometries (more memory consumed, better performance), whereas now we are just using pure instancedMeshes (less memory consumed, worse performance). If you are facing performance issues, I suggest you try out tiles. They will improve both memory and performance. 

To be honest, without pointing to a specific part of the library or proposing something specific to improve this, we don't know what to do, so I'm closing this for now. If you have any specific idea of what you'd like us to change in the future, please let us know and I'll reopen this again.
