### ISSUE TITLE
Culler interval is not set 

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#481]
### Describe the bug 📝

I realised in the MeshCullerRenderer class, the _intervalID property is defined, but never assigned when creating the interval
```
      window.setInterval(async () => {
        if (!this.isProcessing) {
          await this.updateVisibility();
        }
      }, this.updateInterval);
```
Thats why when disposing the culler, this interval is not cleared up properly and can cause issues. Is this a bug or am i missing something? Thanks 

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 56.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Edge: 127.0.2651.105
    Firefox: 123.0.1
    Safari: 17.6
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from `@thatopen/components@2.2.4`!
