### ISSUE TITLE
Export/Serialisation of classifier to avoid reprocessing

### ISSUE THREAD

**Issue by fazelmk** [ThatOpen/engine_components#482]
### Description 📝

I want to be able to export the classifier results to avoid re-processing them every time the client loads the model and improving performance. 

Especially due to `classifier.byPredefinedType` that takes a long time to process giving the website not responding Force Quit / Wait warning in the browser

### Suggested solution 💡

exporting the classifier after processing it once, and loading it on client use to improve user experience and usability.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by fazelmk** [comment]
@HoyosJuan

**Comment by agviegas** [comment]
Available from `@thatopen/components@2.4.0-alpha.7`. You can do it like this:

```ts
const exported = classifier.export();
console.log(exported);
classifier.list = {};
classifier.import(exported);
```

Let me know how it goes!

**Comment by fazelmk** [comment]
Hi @agviegas, I runned a couple of tests and got an error with big classifier.
The size of exported object is bigger then the limit of JSON.stringfy. 

`
Uncaught (in promise) RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at bn.export (index.mjs:6166:17)
    at _Classifier.export (index.mjs:24086:42)
`

I have this classifiers created, probably something redundant and all, As I lack knowledge of IFC to understand what this really does :)

`
await this._classifier.byModel( this._model.uuid, this._model );
await this._classifier.byEntity( this._model );
await this._classifier.bySpatialStructure( this._model, {
  isolate: new Set( [ WEBIFC.IFCBUILDINGSTOREY ] )
} );
await this._classifier.byPredefinedType( this._model );
`

**Comment by agviegas** [comment]
@fazelmk hm, I see. If instead of the string I give you the serializable object so that you handle / persist it however you see fit, would that work for you?

**Comment by fazelmk** [comment]
Yes, that would work. 
I can get the serialised object and write to file in chunks so it don't break the size limit from JSON.stringfy.

**Comment by fazelmk** [comment]
The Fragment library `@thatopen/Fragments` now throws the stringfy error on export.
After removing the `JSON.Stringfy` from the Fragments library locally I got the object.

But the result was a 2.33 GB file, and no I didn't made a mistake with the units.. It's a 2.33 Gigabyte file.
The original IFC file is 22MB.

I'm probably doing something really wrong with my classifier.

 
this [sample.zip](https://github.com/user-attachments/files/17497182/sample.zip) generated a 1GB file for the classifier export.

**Comment by agviegas** [comment]
I removed `JSON.stringify` from the fragments library (`@thatopen/fragments@2.4.0-alpha.9`). 

Using the classifier tutorial as a starting point I wrote this:

```ts
import * as WEBIFC from "web-ifc";
import * as OBC from "@thatopen/components";

const container = document.getElementById("container")!;
const components = new OBC.Components();
const worlds = components.get(OBC.Worlds);

const world = worlds.create<
  OBC.SimpleScene,
  OBC.SimpleCamera,
  OBC.SimpleRenderer
>();

world.scene = new OBC.SimpleScene(components);
world.renderer = new OBC.SimpleRenderer(components, container);
world.camera = new OBC.SimpleCamera(components);

components.init();

world.camera.controls.setLookAt(12, 6, 8, 0, 0, -10);

world.scene.setup();

const grids = components.get(OBC.Grids);
grids.create(world);

world.scene.three.background = null;

const ifcLoader = components.get(OBC.IfcLoader);
await ifcLoader.setup();
console.log(ifcLoader.settings.wasm);

const file = await fetch("../../../../../resources/asdf.ifc");
const buffer = await file.arrayBuffer();
const data = new Uint8Array(buffer);
const model = await ifcLoader.load(data);
world.scene.three.add(model);

const classifier = components.get(OBC.Classifier);

classifier.byEntity(model);
classifier.byIfcRel(model, WEBIFC.IFCRELCONTAINEDINSPATIALSTRUCTURE, "storeys");
classifier.byModel(model.uuid, model);

console.log(classifier);
const exported = classifier.export();

const a = document.createElement("a");
a.download = "example.json";
const exportedFile = new File([JSON.stringify(exported)], "example.json");
a.href = URL.createObjectURL(exportedFile);
a.click();
a.remove();
```

The result (creates a 250kb file):

https://github.com/user-attachments/assets/eea59957-e754-450b-8ae0-99667c4f9e4f

**Comment by fazelmk** [comment]
without adding `byPredefinedType` it's of acceptable size. 
Try adding it and tell me how it went =D. Mine went to GB of size after adding it.

**Comment by fazelmk** [comment]
@agviegas have you being able to test it with `byPredefinedType` in use?

**Comment by agviegas** [comment]
@fazelmk you are right! The size increases exponentially when including `byPredefinedType`. 

We know that persisting data is important, and we have left this topic on hold for some time. Now we are seriously working on a better way to serialize data. We think we can achieve a single `.frag` file that is compact, contains all the geometry, all the properties and all the classifications, indexations, etc. This should make it much easier to work with our libraries.

In the meantime, we'll see if we can make `byPredefinedType` smaller, and maybe you can avoid it in your export (if possible)

**Comment by fazelmk** [comment]
At the moment I'm exporting without it and avoiding running `byPredefinedType` as it's slow to run.
If there is a new better way being developed I think you can keep this old one as is.
