### ISSUE TITLE
Add isolate feature to IfcStreamer

### ISSUE THREAD

**Issue by MadsHolten** [ThatOpen/engine_components#484]
### Description 📝

As suggested [here](https://github.com/ThatOpen/engine_components/issues/434#issuecomment-2236908351) it would be useful if the `IfcStreamer` exposed an `isolate()`-function in addition to `setStatic()` and `setVisibility()`.

The `setVisibility()`-function could also be changed so it works more as the `Hider`. Which will apply the setting to everything if no `FragmentIdMap` is specified ([see here](https://github.com/ThatOpen/engine_components/blob/d702cd7683364e0678a24264816806f51c80a531/packages/core/src/fragments/Hider/index.ts#L35)). In that case, first executing `setVisibility(false)` followed by `setVisibility(true, fragmentIdMap)` would isolate the elements.

The current behaviour I am getting is this:
https://github.com/user-attachments/assets/4b5e7ef1-ba65-47ca-b001-91356ee96084

### Suggested solution 💡

No other elements than those specified will be visible in the viewer and they will also not be loaded by the culler.

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
This is now available from `@thatopen/components-front@2.4.0-alpha.6` using the `setVisibility` feature. If you don't provide a filter as second parameter, it will apply to all items in all models.

By doing this in the [streamer tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer):

```ts
  window.addEventListener("keydown", (e) => {
    if (e.code === "KeyP") {
      loader.setVisibility(false);
    }
    if (e.code === "KeyO") {
      loader.setVisibility(true);
    }
  });
```

This is the result:

https://github.com/user-attachments/assets/96f6ace8-cd3b-4c27-b7f4-e5289596c2c8

By the way, you can now also use `fragmentsGroup.getFragmentMap();` without providing an argument, and it will return the fragment map for the whole model. 

Let me know if you face any issues!
