### ISSUE TITLE
Issues with the IfcStremer (meshes not getting styled when creating plans / isolate partially working)

### ISSUE THREAD

**Issue by cimslab** [ThatOpen/engine_components#486]
### Describe the bug 📝

@agviegas 
Meshes not updating styles and isolate elements not working properly.

 Video
 https://www.youtube.com/watch?v=ZkFPRe8o1dM

In the example attached I am using an interval that styles the meshes every 100 milliseconds. In the video I commented that part to show you what happens when I don't do that:

        modelItems = classifier.find({ models: [currentModel.uuid] });
        if (planBtn.active) {
          classifier.setColor(modelItems, whiteColor);
        }
        culler.needsUpdate = true;
        tilesLoader.culler.needsUpdate = true;
       

### Reproduction ▶️

https://cdt.vercel.app/carleton/asset?assetId=on_ott_pat_89181640&id=on_ott_car_10583513&province=ON&municipality=Ottawa&postalCode=K1S5B7&place=Carleton_University&lat=45.38435&lng=-75.69435&zoom=14.5&altitude=15.5&pitch=42&mapStyle=default

### System Info 💻

```shell
yarn lock:

"@thatopen/components-front@~2.2.0":
  version "2.2.1"
  resolved "https://registry.yarnpkg.com/@thatopen/components-front/-/components-front-2.2.1.tgz#410aa0a3b9549e45cb006d4ce5bb46c954517c54"
  integrity sha512-UDQ5v8Twvb/XOpN9xxWHal6yE540+E31T4rTxW7rxjA3azn879kVjxqCxYceHxrrvjB33b0skMoa8rCNptI1nQ==
  dependencies:
    "@thatopen/components" "~2.2.0"
    camera-controls "2.7.3"
    dexie "^4.0.4"
    earcut "^2.2.4"
    n8ao "1.5.1"
    postprocessing "6.34.2"

"@thatopen/components@~2.2.0":
  version "2.2.4"
  resolved "https://registry.yarnpkg.com/@thatopen/components/-/components-2.2.4.tgz#c5998b22da0bfdb8f743cea72c78daf8a5ab7eaf"
  integrity sha512-9yyEj0ecqwPyiTBNXZgzcSoUIMSZWlgymDQQ7FDqvlE8AoEITQTuUWB8XIX7n+demGBAzrs1dRddEzAiv5SI7A==
  dependencies:
    camera-controls "2.7.3"
    fast-xml-parser "4.4.1"
    jszip "3.10.1"
    three-mesh-bvh "0.7.0"

"@thatopen/fragments@~2.2.0":
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/@thatopen/fragments/-/fragments-2.2.0.tgz#240069fc00561a1efd076f86bf1a895ab4aecb83"
  integrity sha512-s0m3CrKPKInWJZl5PiZ6Mova3siyDtM7FQGJgwcH9mM6lwe9L6aPTvu1G7NV2aI88eGHqiI79hPznxvz4+WkOQ==
  dependencies:
    flatbuffers "23.3.3"
    three-mesh-bvh "0.7.0"

"@thatopen/ui-obc@~2.2.0":
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/@thatopen/ui-obc/-/ui-obc-2.2.0.tgz#27cef15a3ec93deb5498bc22dda315a85377acaf"
  integrity sha512-AUgZaRMHsfSSf+wLLubRwKK2U0lOfInKMc878ITXvBWwKZX/Y+NsEewySPscC7H96+QHEsKfmBjye6xEwotyzA==
  dependencies:
    "@thatopen/ui" "~2.2.0"
    lit "3.1.2"

"@thatopen/ui@~2.2.0":
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/@thatopen/ui/-/ui-2.2.0.tgz#a22d249772d5b75f84b1dcfd492655f5722980e9"
  integrity sha512-vXBEG1vGNwRwlNj6MQC5J2qKpsG3Rkrpxyoctf7BhmAKzMCEA6GCWu9GbFWWfYHUNyT3OIAtM13z6+pk77LaWA==
  dependencies:
    "@floating-ui/dom" "1.6.3"
    iconify-icon "2.0.0"
    lit "3.1.2"
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @cimslab! For styling streamed objects it's easier to use the [highlighter](https://docs.thatopen.com/Tutorials/Components/Front/Highlighter). For instance, doing this in the [streamer tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer):

```ts

  const modelMap = model.getFragmentMap();
  const highlighter = components.get(OBCF.Highlighter);
  highlighter.add("white", new THREE.Color("white"));

  await highlighter.highlightByID("white", modelMap);
  loader.onFragmentsLoaded.add((frags) => {
    highlighter.updateFragments(frags);
  });
```

I get this:

https://github.com/user-attachments/assets/75710218-b818-4160-b8ae-7cb4b446849c

Of course, you can also add a new `MeshBasicMaterial` to the newly loaded fragments to make them look completely white. As for isolating, you can [check this out](https://github.com/ThatOpen/engine_components/issues/484).

Let me know how it goes. Cheers!

**Comment by cimslab** [comment]
Thank you so much, Antonio
That solution looks better that what I have.
I have one problem, model.getFragmentMap() gives me this error: An argument for 'expressIDs' was not provided. 
1. Is it possible to get the expressIDs of all the visible elements, or all the geometries when I am in a floorplan view and then clear it when I exit plan view?
2. to style the this elements (so they are also styled when I use the clipping plan) do I still use the the method that you show in the Floorplan tutorial (    const thickItems = this._classifier.find({
      entities: ['IFCWALLSTANDARDCASE', 'IFCWALL'],
    });)
It seems to work in the floorplans but not for the clipper for some reason.

**Comment by cimslab** [comment]
Based on your recommendations this is what I am doing:
![image](https://github.com/user-attachments/assets/987e86b9-6aa8-490f-8ad8-c9892f235127)
Error: An argument for 'expressIDs' was not provided.

**Comment by agviegas** [comment]
@cimslab can you try the latest alpha version of fragments and components? You can see them in [npm](https://www.npmjs.com/org/thatopen). We'll release them as non-alpha in the next release

**Comment by cimslab** [comment]
ouch, V2.3.15 resulted in a lot of drama!
![image](https://github.com/user-attachments/assets/2fa10ba2-abb3-4541-83d6-50725f25571d)
![image](https://github.com/user-attachments/assets/610bcdf7-5330-409c-b0d0-d2ed532c3e75)

Maybe I will wait for 2.4

thanks Antonio
