### ISSUE TITLE
IFCMAPCONVERSION property is null even though set on IFC model

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#488]
### Describe the bug 📝

I am trying to get IFCMAPCONVERSION entity properties of my IFC model, in order to set its location based on georeference data provided within the file. Even though I can see IFCMAPCONVERSION defined

>#97=IFCMAPCONVERSION(#91,#96,689679.3800000014,5335897.5899999989,0.,0.95229672180407676,-0.30517364506328015,$);

inside my IFC file, below log returns null. 
`console.log(await model.fragmentsGroup.getAllPropertiesOfType(3057273783));`
also `model.fragmentsGroup.getAllPropertiesTypes()` is not returning '3057273783' as one of types. 

This is blocking us to correctly position models that are georeferenced. Can you please help? 
Thanks in advance
here is a sample ifc file: https://drive.google.com/file/d/1R-mR17RH20AJ-2E6djFOUUxg9THLSPui/view?usp=sharing

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 136.36 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.122
    Edge: 128.0.2739.42
    Safari: 17.6
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @onderilkesever the properties that are related to geometric entities are excluded when generating the properties of the IFC. You can see the list of excluded types [here](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/ifc/IfcJsonExporter/src/ifc-geometry-types.ts), and the value of each constant [here](https://raw.githubusercontent.com/ThatOpen/engine_web-ifc/main/src/ts/ifc-schema.ts). Editing the `GeometryTypes` object should allow you to control which entities are exported. Let me know if it doesn't work!

**Comment by onderilkesever** [comment]
Thank you very much @agviegas, works very well.
