### ISSUE TITLE
IFC Models pointing an axis up different than Y

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#490]
### Describe the bug 📝

When loading a model pointing up any axis other than Y, its being shown as flipped to a side. 
I wonder could we the library somehow identify this axis information from IFC Model (maybe from IfcAxis2Placement3D) and create geometries accordingly? Or should we need to handle this on our side? 

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 54.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 128.0.6613.85
    Edge: 128.0.2739.42
    Safari: 17.6
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
@onderilkesever we just read and display what we find in the IFC. If you see that other IFC viewers automatically orientate this correctly, let us know and open an issue in the [web-ifc repo](https://github.com/ThatOpen/engine_web-ifc) so that we can address it! Otherwise, this is expected behavior, and in that case I think it's better if you handle this on your side.
