### ISSUE TITLE
Seems FragmentsManager dispose function not release memory

### ISSUE THREAD

**Issue by steven11329** [ThatOpen/engine_components#491]
### Describe the bug 📝

I create a simple 3D world by React.

I have call components.dispose() when 3D page unmount by useEffect.

But still found that stat memory continues to rise.

### Reproduction ▶️

https://github.com/steven11329/thatopen-fragment-no-release-memory-problem

### Steps to reproduce 🔢

1. Click "Other Page" button.
2. Click "3D" button.
3. Repeat 1 & 2.
4. You will see stats chart memory comsumption increase

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 2.88 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /usr/local/opt/node@20/bin/node
    pnpm: 9.7.1 - ~/Library/pnpm/pnpm
    Watchman: 2024.08.12.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
```

### Used Package Manager 📦

pnpm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by steven11329** [comment]
I noticed that after some time, memory is released,
but the timing is inconsistent.
Is there a more effective way to release memory?

**Comment by agviegas** [comment]
@steven11329 we can't force the immediate release of the memory. That's just how JS garbage collector works. If you find a way to make this automatic, please let us know!
