### ISSUE TITLE
Same model twice breaks highlighter

### ISSUE THREAD

**Issue by fwestling-ark** [ThatOpen/engine_components#492]
### Describe the bug 📝

I am adding the same fragment multiple times with different positions.  I expect that each `FragmentGroup` would have a unique ID and position, and the Highlighter could select each instance individually.   Instead, the Highlighter only works on one instance of the fragment, and the others are not highlightable.

For context, my use case requires individual components to be loaded as separate IFC files, with one or more instances of each located separately according to a third-party positioning scheme.  I do not have the option of composing the model into one IFC file.

### Reproduction ▶️

[Vite-React-TS.webm](https://github.com/user-attachments/assets/b7efa757-f78e-4513-917d-96d77f9ff6b8)

### Steps to reproduce 🔢

Follow the example https://docs.thatopen.com/Tutorials/Components/Front/Highlighter.
When adding the model, instead load the fragment twice (note: same results if you replicate `fetch` and `arrayBuffer` as well).
Move one of the fragment groups so that you can see them separately.
Run the sample;  you can highlight one model, but not the other.

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 9.56 GB / 31.87 GB
  Binaries:
    Node: 20.16.0 - ~\AppData\Local\fnm_multishells\28108_1725495973564\node.EXE
    Yarn: 1.22.22 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.8.1 - ~\AppData\Local\fnm_multishells\28108_1725495973564\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527


 "dependencies": {
    "@thatopen/components": "^2.2.9",
    "@thatopen/components-front": "^2.2.2",
    "@thatopen/fragments": "^2.2.0",
    "@thatopen/ui": "^2.2.0",
...
}
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
@fwestling-ark have you tried [cloning the model instead](https://docs.thatopen.com/api/@thatopen/components/classes/FragmentsManager#clone)? That should be much faster than loading the model twice, and it should work well. Otherwise, let us know!
