### ISSUE TITLE
BoundingBoxer.addFragmentIdMap() not works & FPS become very low when load complex IFC model 

### ISSUE THREAD

**Issue by steven11329** [ThatOpen/engine_components#499]
### Describe the bug 📝

I'm try to get every floors' bbox for filter floor model with clipping plane.

I could get properties by `IFCBUILDINGSTOREY`
```ts
getAllPropertiesOfType(WEBIFC.IFCBUILDINGSTOREY)
```
I could get bbox on simple IFC file by
```ts
for (const id in properties) {
          const property = properties[id];
          this._fragmentBbox.addFragmentIdMap(
            gp.getFragmentMap([parseInt(id)])
          );
          const floorBbox = this._fragmentBbox.get();
          const scale = 1.01;
          infoMap[gp.userData.buildingIndex].floors.push({
            name: property?.Name?.value,
            bbox: {
              maxX: scale * floorBbox.max.x,
              minX: scale * floorBbox.min.x,
              maxY: scale * floorBbox.max.y,
              minY: scale * floorBbox.min.y,
              maxZ: scale * floorBbox.max.z,
              minZ: scale * floorBbox.min.z,
            },
          });
          this._fragmentBbox.reset();
        }
```

But it not works on complex IFC file.

Another problem is FPS become very low when complex IFC file loaded

I know that could exclude categories which follow [link](https://docs.thatopen.com/Tutorials/Components/Core/IfcLoader).
But i'm not IFC expert. So I don't know what categories I could exclude.

### Reproduction ▶️

https://github.com/steven11329/thatopen-api-issue

### Steps to reproduce 🔢

1. Run `pnpm install`
2. Open browser [http://localhost:5173/](http://localhost:5173/)
3. Select Issue 2

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 512.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /usr/local/opt/node@20/bin/node
    pnpm: 9.7.1 - ~/Library/pnpm/pnpm
    Watchman: 2024.08.12.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 128.0.6613.138
```

### Used Package Manager 📦

pnpm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [ ] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @steven11329 please next time try to create an issue per problem instead of bringing multiple things in the same issue. 

Regarding performance: 

You can either use the [culler](https://docs.thatopen.com/Tutorials/Components/Core/Cullers) or [streaming](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer).

Regarding floor isolation:

If you want to isolate items by floor, I suggest you take a look at the `classifier.bySpatialStructure`, which will give you the `FragmentIdMap` of all items contained in a specific spatial structure. You can see it in action in the [exploder tutorial](https://docs.thatopen.com/Tutorials/Components/Core/Exploder#-boom).
