### ISSUE TITLE
Geometry differences between web-ifc demo page and OBC.IfcLoader 

### ISSUE THREAD

**Issue by robertbiskup** [ThatOpen/engine_components#504]
### Describe the bug 📝

Hi @agviegas  and @HoyosJuan, could you please take a look at the issue disscused at https://github.com/ThatOpen/engine_web-ifc/issues/1057 ? We got different results after uploading ifc files to web-ifc demo page(https://thatopen.github.io/engine_web-ifc/demo) and engine-components viewer using OBC.IfcLoader ( https://unpkg.com/web-ifc@0.0.59/58 and "@thatopen/components-front": "2.2.2",
"@thatopen/components": "2.2.11"). Web-ifc demo page all ifc files shows correctly - when using components - geometry errors appear. There are sample screenshots and ifc files. 

### Steps to reproduce 🔢

Load ifc in newer components

### System Info 💻

```shell
@thatopen/components-front": "2.2.2",
@thatopen/components": "2.2.11"
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @robertbiskup! That's beacuse we haven't update the web ifc dependency in components yet. Will be donee for release 2.3.0 coming this week.

**Comment by robertbiskup** [comment]
@HoyosJuan Thank you for the quick answer! This is crucial information, I thought that setting the "wasm" parameter was enough, so we are waiting for the update! ;)

**Comment by agviegas** [comment]
Hey @robertbiskup can you try with `1.3.0` and let us know how it goes?

**Comment by robertbiskup** [comment]
Hi @agviegas I have tried with 2.3.0 "@thatopen/components-front": "2.3.0",
 "@thatopen/components": "2.3.0") but there are still some diffrences with openings as the screenshots below show: 
web-ifc demo: 
![image](https://github.com/user-attachments/assets/126f8e34-a617-49df-b155-2ccbe2c0e2c7)
 components:  
![image](https://github.com/user-attachments/assets/3f813675-2d24-49a1-a717-9720426e952c)
I will send you this test file in the private message in openers chat. If you could check whether the problem also occurs in your version of components, I would be grateful.

**Comment by agviegas** [comment]
Hey @robertbiskup did you also update the web-ifc dependency in your project to be the latest?

**Comment by robertbiskup** [comment]
@agviegas, after "npm install" I have version 0.0.59 of web-ifc in the "node_modules" folder (and "@thatopen/components-front": "2.3.0", "@thatopen/components": "2.3.0"), I use the rollup to build the bundle.js file and there I have the code to load ifc: 
![image](https://github.com/user-attachments/assets/57723b7c-267e-4d4e-a02c-3fe3a0383a3b)

**Comment by agviegas** [comment]
Hey @robertbiskup you are right, I could reproduce this. It turns out there have been some very recent improvements in web-ifc that are not included in .59 (published 2 weeks ago). We'll publish them soon and update components :)

**Comment by agviegas** [comment]
Updated the latest changes of web-ifc in `@thatopen/components@2.4.0-alpha.11` and `@thatopen/components-front@2.4.0-alpha.7`!

**Comment by robertbiskup** [comment]
Hey @agviegas, I updated libraries to  "@thatopen/components-front": "2.4.2",
 "@thatopen/components": "2.4.2",
 "@thatopen/fragments" : "2.4.0",
 "web-ifc": "0.0.66", and there are still a few errors (lesst han before) on the components side that are not present on the web-ifc demo page, I'll send you fragment of this model in private message to check
![image](https://github.com/user-attachments/assets/e4b19a04-88de-4181-b73b-d667991da3ad)
![image](https://github.com/user-attachments/assets/7fc88f04-eb84-4c81-ad58-df856f780a36)
