### ISSUE TITLE
Can't renderer a point cloud using potree-core in the scene

### ISSUE THREAD

**Issue by matheus14maia** [ThatOpen/engine_components#505]
### Describe the bug 📝

I am doing a project that needs to renderer a point cloud in the BIM scene, don't show any error, but don't renderer the point cloud in the scene. The code I'm using in react, but work in vanilla to.
![LoadPointCloudPCR](https://github.com/user-attachments/assets/9971d5c6-ba13-4bad-bed9-458baf4a9ad6)
![PointCloudRenderer](https://github.com/user-attachments/assets/6e06772f-d669-4c23-a97a-0b3b8ccd73f1)

### System Info 💻

```shell
Nothing
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nicoarellano** [comment]
Hey @matheus14maia , interesting. I am curious, did the implementation work in Vanila JS or it didn't? Pleas keep me posted, I am very interested in this function as well

**Comment by matheus14maia** [comment]
Hi, if you try to create a project in Vanila JS this worked. The problem was using the thaopen library, because i tried to render the point cloud in their world.scene and didn't renderer, but if it was in normal threejs scene this work.

**Comment by agviegas** [comment]
@matheus14maia closing this for now! If you provide an example we can use, let us know and we'll open this again. Cheers!
