### ISSUE TITLE
Tiles stemming bottleneck

### ISSUE THREAD

**Issue by themodmin** [ThatOpen/engine_components#509]
### Describe the bug 📝

The streamer downloads files sequentially, waiting for each file to fully download before starting the next, even when the next file is cached or smaller. This behavior creates a bottleneck in the streaming process, slowing down overall performance.
here is a video to better show this [https://people.thatopen.com/c/ask-the-community/tiles-stemming-bottleneck](https://people.thatopen.com/c/ask-the-community/tiles-stemming-bottleneck)

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 17.47 GB / 31.85 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.79)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
This should be solved in `1.4.0-alpha.1`. I've introduced 2 improvements:
- Fragment files now download in parallel.
- Cached fragment files are given more priority.
Try it out and let me know if the issue persists or you face any problem!
