### ISSUE TITLE
Cast ray from any given point on screen, not just from the pointer position

### ISSUE THREAD

**Issue by CabeDigicorp** [ThatOpen/engine_components#511]
### Description 📝

Currently, the SimpleRaycaster.castRay() method casts a ray from the camera to the mouse or touch event point. There is no way to override the mouse/touch position and cast to a point defined by its (x,y) on-screen coordinates.

### Suggested solution 💡

In the Core module, modify the SimpleRaycaster.castRay() method so that it accepts an optional parameter of type Vector2. If that parameter has a value, use it as the raycasting point; otherwise, use the mouse/touch position as in the current implementation.

### Additional context ☝️

Discussed here: https://people.thatopen.com/c/ask-the-community/raycaster-problem

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Available from `@thatopen/components@2.4.0-alpha.9`!
