### ISSUE TITLE
Highlighter Clear Single Fragment

### ISSUE THREAD

**Issue by ManuzXo** [ThatOpen/engine_components#513]
Hi, I’m trying to find a way to clear the [Highlighter](https://docs.thatopen.com/api/@thatopen/components-front/classes/Highlighter) component for specific fragments. At the moment, I see that there is a [Clear](https://docs.thatopen.com/api/@thatopen/components-front/classes/Highlighter#clear) function which takes a category parameter (such as select, highlight, etc.), but it does not seem to work for individual fragments. Does anyone have a solution for this?

**Comment by agviegas** [comment]
@ManuzXo I understand you want to remove a specific ID from your selection. Is that right? If yes, do you want to do it by clicking on it or programmatically (by ID)?

**Comment by ManuzXo** [comment]
yes I want to clear a specific expressID or Fragment if possible, via TypeScript ofc.
I cant clear for the moment specific fragment or expressID.

![image](https://github.com/user-attachments/assets/29f8420d-ee6f-4813-bfc4-5b91aecff3ed)
![image](https://github.com/user-attachments/assets/43b6cafa-76c7-471d-b3c2-727d4c6742ea)

**Comment by agviegas** [comment]
This is already possible with the current API. You have 2 options: either re-select everything with the parameter `removePrevious=true`, or doing something like the following:

```ts
window.addEventListener("keydown", (e) => {
  if (e.code === "KeyP") {
    highlighter.add("example", new THREE.Color("red"));
    const walls = model.getFragmentMap([186, 294, 338]);
    highlighter.highlightByID("example", walls);
  }
  if (e.code === "KeyO") {
    highlighter.autoToggle.add("example");
    const wall = model.getFragmentMap([186]);
    highlighter.highlightByID(
      "example",
      wall,
      false,
      true,
      undefined,
      undefined,
      true,
    );
  }
```

This is the result in the [highlighter example](https://docs.thatopen.com/Tutorials/Components/Front/Highlighter):


https://github.com/user-attachments/assets/5b54b160-ed90-49af-9f05-95d63a3bc748

**Comment by ManuzXo** [comment]
Okay perfect thanks
