### ISSUE TITLE
Tool for isolating graphical elements and export to valid IFC

### ISSUE THREAD

**Issue by MarcusAndreasSvensson** [ThatOpen/engine_components#514]
### Description 📝

Currently there is a bug in the IFC parser which leaves some faces of some models unrendered.

To alleviate this issue I would like to share affected files for debugging purposes, but I am not allowed to share the files as is because it's considered a valuable asset.

### Suggested solution 💡

Create a tool where we could decimate an IFC and easily isolate the problematic areas exported as a separate IFC-file.

This file would be unrecognizable and thus sharable.

Preferably the tools would also strip off any metadata and properties and only leave the geometry to assure there is no sensitive information in the isolated file.

### Additional context ☝️

This feature would help solve ThatOpen/engine_web-ifc#927

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by superman90113** [comment]
@agviegas Hi. I think about this approach.
1. Load IFC file
2. Select elements to Isolate
3. Extract fragments from the selected elements
4. Remove all unnecessary information(properties) from the fragments.
5. Generate new temporary FragmentGroups with the extracted fragments
6. Save the FragmentGroups into a file
Let me know what you think about this.

**Comment by agviegas** [comment]
Hey @superman90113 here is that we need to output an IFC file, not a fragment file. So ideally the conversion should happen without generating the fragments for the IFC file, as they are not necessary and would consume resources. 

IMO we need something like: `const result = splitIfc(ifcFile, idsToExtract)`;

**Comment by superman90113** [comment]
Hi @agviegas 
I have managed to get time to implement the feature.
I have worked in a single file with web-ifc library imported. How can I add the function here, so that you can check?

**Comment by agviegas** [comment]
Hey @superman90113 that's great! You can create a new class in the IFC folder and do something similar to the [IFC to JSON exporter](https://github.com/ThatOpen/engine_components/tree/main/packages/core/src/ifc/IfcJsonExporter)

**Comment by superman90113** [comment]
Hi @agviegas I've created a new class IFCIsolator and implemented the feature on my local. How can I upload this class to send you"

**Comment by agviegas** [comment]
Hey, can you create a PR? Thanks!

**Comment by superman90113** [comment]
Hi, @agviegas 
Let me know the feedback if you reviewed the implementation.
Thank you!

**Comment by agviegas** [comment]
@superman90113 hi sorry I didn't have time to review it until now, I'll let you know asap. Thanks!

**Comment by superman90113** [comment]
Hi, @agviegas!
Good to see that my pull request is accepted.
I think you will need to add corresponding pages to the doc and examples?
Regards.
