### ISSUE TITLE
Loading big IFC model crashes application

### ISSUE THREAD

**Issue by onderilkesever** [ThatOpen/engine_components#515]
### Describe the bug 📝

I am trying to load a big IFC model with stats shown as below and my browser crashes when loading. 
![0783d9fe-825a-4348-920f-7ae5445047ad](https://github.com/user-attachments/assets/2a25fdc1-6cbd-467a-b021-b0071af11b36)
I can share my small application but it is simply creating a world and load model using IfcLoader. 
I have tried loading same model to demo of web-ifc repository, and it can be successfully loaded there. 
Unfortunately I cannot share IFC model due to privacy reasons, but I am hoping my shared stats might give you clue. I wonder is there hard limits what this repo can handle in terms of object count etc? Can you please help me here? 

### System Info 💻

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.101
    Edge: 130.0.2849.46
    Safari: 17.6
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @onderilkesever how big is the file? To load big models fast we have a [streaming system](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer) that we have tried successfully with files over 2GB

**Comment by agviegas** [comment]
@onderilkesever I see. Not big indeed, but maybe it has a lot of geometry. Have you tried streaming?

**Comment by onderilkesever** [comment]
@agviegas , I just tried streaming, and the application does not crash, but the displayed model is not complete(some pieces are missing). 
Nevertheless, I am afraid migrating to streaming is going to be quite challenging for us as we already have bunch of custom use cases integrated. And having culler in place, we actually didnt have any performance problems without streaming until now. And I feel if we could render, three will not have problem rendering thanks to culler. So I would really appreciate your help finding the bottleneck here that could potentially understand why the browser crashes in the first place.

**Comment by agviegas** [comment]
@onderilkesever I see. Are you trying to open the IFC file directly in the browser, or export it to fragment files and then open the .frag directly?

**Comment by onderilkesever** [comment]
@agviegas I tried both loading via `IfcLoader` and `FragmentsManager`, both are crashing the browser/tab.

**Comment by agviegas** [comment]
Hm, if just loading the .frag file (no IFC present whatsoever) crashes the memory, it means that it's too much for three.js to handle simultaneously with the current geometry system. I can come up with two options:

- Split down the file and load only parts of it when exporting to .frag
- Streaming (if you face any issues or have any problems, happy to guide you)

**Comment by onderilkesever** [comment]
Thanks for the support here @agviegas ! Can you please help me how can I split it down when converting to frag? The only option I know is by filtering entities, but unfortunately most of the entities seems to be coming from single category.

**Comment by agviegas** [comment]
@onderilkesever I guess you will need to customize our IFC-fragments converter a bit. In [this loop](https://github.com/ThatOpen/engine_components/blob/26313ebb90b6829345e62959416355d495fdc151/packages/core/src/fragments/IfcLoader/index.ts#L232) you can add a counter to just convert a certain number of geometries (e.g. 1000 geometries). If you have questions in the process, let me know!

**Comment by onderilkesever** [comment]
Thanks for your support here and offering your help for various solutions. I only have one thing that I cannot fully answer. How come demo of web ifc (https://thatopen.github.io/engine_web-ifc/demo/) can show the same model in the same pc but not when using "@thatopen/components" if that was only limitation on the three with the current geometry system?

**Comment by agviegas** [comment]
@onderilkesever because the demo of web-ifc has a different geometry system. It merges all the geometries into a single mesh with multiple materials. This works well for some models but it has several problems:

- The use of memory is proportional to the size of the model. So this means that depending on your machine, there are models that you will never be able to open with this.
- Buffers are hard to edit and work with. Things like highlighting, hiding, etc are hard.
- This system is impossible to manipulate (so we would never be able to build a modeller like clay)

In components we use instancedMeshes. They are way more flexible, easier to work with (highlighting, hiding, etc), allow us to load parts of the model (e.g. streaming), as well as opens the door for modelling in the future. Of course, there are models that benefit from the first system more, but in our experience the current system we have in fragments is the one that closes less doors.
