### ISSUE TITLE
Issue with Streaming Tiles in Viewer After Following Tutorial

### ISSUE THREAD

**Issue by andrelzsousa** [ThatOpen/engine_components#516]
### Describe the bug 📝

I’ve been following the tutorials on propertiesTiler and geometryTiler closely, and I’ve successfully created all the required files and structured them correctly in my bucket. Afterward, I followed the tutorial on streaming to use these stored files when executing the viewer.

However, I’m encountering an issue. The viewer loads correctly—the world appears as expected, and there are no errors in the console. In the network tab, it makes requests (which return 200 OK) for only 4 files:

• tiles.ifc-processed-properties.json

• tiles.ifc-processed.json

• tiles.ifc-processed-global

• tiles.ifc-processed-properties-indexes

But after that, no further requests are made for the properties and geometries files.

I’ll leave my testing code below (it’s very similar to what is shown in the streaming tutorial) and a print of how i'm storing my stream files.

Thank you in advance for any insights or help!

![image](https://github.com/user-attachments/assets/4647f2fc-e9fa-4f51-b080-85821f108804)

`"use client";
import { useEffect } from "react";

import * as OBC from "@thatopen/components";
import * as OBCF from "@thatopen/components-front";

const Test = () => {
  useEffect(() => {
    const asyncFunction = async () => {
      const container = document.getElementById("container")!;

      const components = new OBC.Components();

      const worlds = components.get(OBC.Worlds);

      const world = worlds.create<
        OBC.SimpleScene,
        OBC.SimpleCamera,
        OBC.SimpleRenderer
      >();

      world.scene = new OBC.SimpleScene(components);
      world.renderer = new OBC.SimpleRenderer(components, container);
      world.camera = new OBC.SimpleCamera(components);

      components.init();

      world.scene.setup();

      world.camera.controls.setLookAt(12, 6, 8, 0, 0, -10);

      const grids = components.get(OBC.Grids);
      grids.create(world);

      const loader = components.get(OBCF.IfcStreamer);
      loader.world = world;

      loader.url =
        "https://STORAGEURL/storage/v1/object/public/ifcs/tiles/";

      async function loadModel(geometryURL: string, propertiesURL?: string) {
        const rawGeometryData = await fetch(geometryURL);
        const geometryData = await rawGeometryData.json();
        let propertiesData;
        if (propertiesURL) {
          const rawPropertiesData = await fetch(propertiesURL);
          propertiesData = await rawPropertiesData.json();
        }

        const model = await loader.load(geometryData, true, propertiesData);
        console.log(model);
      }

      const propertiesURL =
        "https://STORAGEURL/storage/v1/object/public/ifcs/tiles/tiles.ifc-processed-properties.json";

      const geometryURL =
        "https://STORAGEURL/storage/v1/object/public/ifcs/tiles/tiles.ifc-processed.json";

      await loadModel(geometryURL, propertiesURL);

      world.camera.controls.addEventListener("sleep", () => {
        loader.culler.needsUpdate = true;
      });

      loader.useCache = true;
      loader.culler.threshold = 10;
      loader.culler.maxHiddenTime = 1000;
      loader.culler.maxLostTime = 3000;
    };

    asyncFunction();
  }, []);

  return <div id="container" className="h-screen w-screen"></div>;
};

export default Test;`

### System Info 💻

```shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M2
    Memory: 325.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.2.0 - /usr/local/bin/pnpm
    Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 18.0
  npmPackages:
    openbim-components: ^1.5.0 => 1.5.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi, it's a bit hard for us to debug without having the whole app to see what is happening, so we'll send you 2 fully working examples. 

-  [Tile consumer](https://github.com/ThatOpen/engine_components/blob/main/packages/front/src/fragments/IfcStreamer/example.ts). You clone can this repo, run `yarn install` and `yarn dev` and [open the example locally](http://localhost:5173/packages/front/src/fragments/IfcStreamer/example.html). 
- [Tiles converter](https://github.com/user-attachments/files/17488061/converter.zip) both for geometry and for properties.

I'm closing this issue as it doesn't seem a bug in the library, but feel free to ping me if any of the providen examples don't work. You can use them as reference to see what you are doing differently. Cheers!
