### ISSUE TITLE
Error loading multiple models

### ISSUE THREAD

**Issue by matilde-mantoan-efm** [ThatOpen/engine_components#517]
### Describe the bug 📝

Hi! We are developing an app with Angular 14 where we load all the models of a building, which correspond to the floors.
The problem is that it is placing all the models overlapping on the ground floor, instead on your modelsList of the tutorials I see that it loads them respecting the floors.

Tutorial:
![image](https://github.com/user-attachments/assets/f916ff2c-0839-481b-83fe-509fb1fc9b84)

Our project:
![image](https://github.com/user-attachments/assets/e76e6d28-7f7d-4f4d-a8b5-71bc2a0ddbd3)

On ngOnInit we call the onLoadFileList():

```
onLoadFileList(files: string[]) {
    zip(from(files)).pipe(map(([file]) => file), concatMap(file=>this.loadData(file).then(res=>{
      return res
    }))).subscribe(res => {
      this.model = res;
      this.models.push(res);
      console.log(this.models, "models");
    })
  }
```

loadData():

 ```
async loadData(name?: string) {
    const file = await this.downloadService.downloadFileInChunks(name);
    const data = await file.arrayBuffer();
    const buffer = new Uint8Array(data);
    const model: FragmentsGroup = await this.ifcLoader.load(buffer);
    model.name = name;
    this.world.scene.three.add(model);
    let progressIncrement = (100 / this.ifcFiles.length);
    this.progressValue += progressIncrement;
    this.downloadService.progressValue.next(this.progressValue);
    for (const child of model.children) {
      if (child instanceof THREE.Mesh) this.world.meshes.add(child);
    }
    await this.indexer.process(model);
    await this.plans.generate(model);
    this.onGenerate2D(model);
    this.onClassifyModel(model);
    return model;
  }
```

Definitions in ngOnInit():
 ```
 const container = document.getElementById('viewer-container') as HTMLDivElement;
    const components = new OBC.Components();
    this.viewer = components;
    const worlds = components.get(OBC.Worlds);
    const world = worlds.create<OBC.SimpleScene, OBC.OrthoPerspectiveCamera, OBCF.PostproductionRenderer>();
    world.scene = new OBC.SimpleScene(components);
    world.renderer = new OBCF.PostproductionRenderer(components, container);
    world.camera = new OBC.OrthoPerspectiveCamera(components);
    world.camera.controls.setLookAt(12, 6, 8, 0, 0, -10);
    world.renderer.postproduction.enabled = true;
    world.renderer.postproduction.customEffects.outlineEnabled = true;
    components.init();
    world.scene.setup();
    const grids = components.get(OBC.Grids);
    const grid = grids.create(world);
    grid.three.position.y -= 1;
    world.renderer.postproduction.customEffects.excludedMeshes.push(grid.three);
    this.world = world;

    const ifcLoader = components.get(OBC.IfcLoader);
    ifcLoader.setup();
    this.ifcLoader = ifcLoader;
    const fragments = components.get(OBC.FragmentsManager);
    this.fragments = fragments;
```

It seems loading the models correctly.
![image](https://github.com/user-attachments/assets/eac66acb-4dfb-445c-9057-bfb142324675)

 
I think the problem is this.world.scene.three.add(res);

### System Info 💻

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.66 GB / 15.73 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD

"@thatopen/components": "^2.2.5",
"@thatopen/components-front": "^2.2.1",
"@thatopen/fragments": "^2.2.0",
"@thatopen/ui": "^2.2.0",
"@thatopen/ui-obc": "^2.2.1",
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hi @matilde-mantoan-efm are you awaiting for a model to load before loading the next one? Models can't be loaded in parallel

**Comment by matilde-mantoan-efm** [comment]
Hi Antonio, yes we manage them asynchronously, we have a list of filenames, we pass each element to an api that returns the file object that then we pass to ifcLoader.load(). 
Everything seems to work, even rendering in the Plans and Classifier components works fine. The only problem is with the model coordinates that seem to "reset" for each model.

**Comment by superman90113** [comment]
Hi, @matilde-mantoan-efm. Could you create a new Angular 14 project which involves the issue and send me? I will try to fix the issue.

**Comment by agviegas** [comment]
@matilde-mantoan-efm I see. Just curious, can you try loading them one by one instead of batch loading them all and see if anything changes? Also, are you initializing the components (e.g. IFCLoader) just once, or every time a new model is loaded?

**Comment by matilde-mantoan-efm** [comment]
Hi Antonio, we have resolved, we found out that the problem was in the service that returns the files and not in the modelsList. Thank you!!
