### ISSUE TITLE
Unable to Dispose when OBC.Clippers are used

### ISSUE THREAD

**Issue by aka-blackboots** [ThatOpen/engine_components#518]
### Components.dispose() throws error 📝

1. `Clipper.dispose()` works as expected.
2. But when Clipper is added to the app and if you call `components.dispose()` there is an error thrown from inside the `SimplePlanes`

![Screenshot 2024-10-24 at 2 52 51 PM](https://github.com/user-attachments/assets/fad6d7a2-6b3a-4591-97a3-774966bec5be)

### System Info 💻

```shell
System:
    OS: macOS 15.0.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.84 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 4.5.0 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.69
    Safari: 18.0.1
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
@aka-blackboots closing this as this is solved from `@thatopen/components@2.3.12`
