### ISSUE TITLE
IfcFinder specifying the property name in IfcPropertyRule doesn't yield results

### ISSUE THREAD

**Issue by atefMck** [ThatOpen/engine_components#519]
### Describe the bug 📝

I'm using the IfcFinder to get the Reference property with value starting with Por on the small.ifc example file as shows the image below.

![Screenshot 2024-10-14 174000](https://github.com/user-attachments/assets/61ef099d-1b21-4d2e-9f4a-14a24f11e12b)

When specifying the property name, IfcFinder returns an empty result which shouldn't be correct as there are elements with property Reference starting with Por.

![Screenshot 2024-10-14 174058](https://github.com/user-attachments/assets/cbe8bdb3-9aed-4858-bc96-edfb961bd7bc)

However whenever I don't specify the property name, IfcFinder returns the correct results.

![Screenshot 2024-10-14 174027](https://github.com/user-attachments/assets/c25a9633-a98e-4dcf-b9c4-01c9aa447b15)

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
    Memory: 8.91 GB / 23.86 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @atefMck that happens because “name” refers to the name of the attribute of the [IfcPropertySingleValue](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcpropertyresource/lexical/ifcpropertysinglevalue.htm). In other words, that property single value looks like this:

```ts
{
  Name: "Referencia",
  NominalValue: "Por defecto - 30cm",
  ...
}
```

So as you can see, `Referencia` is actually not a name, but a value whose name is `Name`. You probably want something like this:

```ts
    const propertyRule2: TOC.IfcPropertyRule = {
      type: "property",
      name: /Name/gm,
      value: /Referencia/gm
    };

    const propertyRule1: TOC.IfcPropertyRule = {
      type: "property",
      name: /NominalValue/gm,
      value: /Por.*/gm
    };
```
