### ISSUE TITLE
Classifier bySpacialStructure with custom name

### ISSUE THREAD

**Issue by fazelmk** [ThatOpen/engine_components#520]
### Description 📝

Allow to add a custom system name for `classifier.bySpacialStructure` execution.
This would allow for the creation of different classifier results when using the isolate method.
At the present moment all runs of classifier.bySpacialStructure will be added under the same system name "spacialStructure". 

@juan

### Suggested solution 💡

Use a name optional parameter in the config to allow for custom names, with a default value of the current system name
to not add a braking change

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey @fazelmk! This has been already implemented by [this commit](https://github.com/ThatOpen/engine_components/commit/a5d806a1503850a3a5f370c53137cb861cbff325) and available in version @thatopen/components@2.3.16.
