### ISSUE TITLE
IDS check TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by Can-Gr** [ThatOpen/engine_components#524]
### Describe the bug 📝

I have an IDS with many specifications and every specification is working except one. But this one specification, instead of counting elements as fail, is throwing error at this line:

**const result = await specification.test(model)**

Error:
**_index.mjs:20315 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at ch.evalValue (index.mjs:20315:1)
    at ch.test (index.mjs:20237:1)
    at async lh.test (index.mjs:20402:1)_**
    
The specification:

        **<specification name="Pset_ManufacturerTypeInformation" ifcVersion="IFC2X3 IFC4">
            <applicability minOccurs="0" maxOccurs="unbounded">
                <entity>
                    <name>
                        <simpleValue>IFCBEAM</simpleValue>
                    </name>
                </entity>
            </applicability>
            <requirements>
                <property dataType="IFCLABEL" cardinality="required">
                    <propertySet>
                        <simpleValue>Pset_Manufacturer</simpleValue>
                    </propertySet>
                    <baseName>
                        <simpleValue>Manufacturer</simpleValue>
                    </baseName>
                    <value>
                         <restriction base="string">
				<enumeration value="TESTA" />
				<enumeration value="TESTB" />
			</restriction>
                    </value>
                </property>
            </requirements>
        </specification>**

This IDS is checking IFCBEAMs, so I have manually checked these elements and found that in some elements, in the required pset(Pset_Manufacturer) Manufacturer property is null.

In other words, NominalValue of this property is null. Shouldn't be this element counted as fail instead of throwing error ? 

### System Info 💻

```shell
components: "^2.3.14",
components-front: "^2.3.9",
ui: "^2.3.0",
ui-obc: "^2.3.2",
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @Can-Gr! This has been already solved by [this commit](https://github.com/ThatOpen/engine_components/commit/d8d2cdc9d598533867e64c55401e930f1dc5c1ab) and available at @thatopen/components@2.3.16.

Let me know to close the issue!

**Comment by Can-Gr** [comment]
Hey @HoyosJuan! Yes it's working now! The elements are shown as failed as expected. Thank you!

**Comment by HoyosJuan** [comment]
Awesome! Closing this.
