### ISSUE TITLE
IfcPropertyTiler missing ignore  IFCTRIANGULATEDFACESET

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#535]
### Describe the bug 📝

When we IfcPropertyTiler , we ignore types in [GeometryTypes](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/ifc/IfcJsonExporter/src/ifc-geometry-types.ts),  but with  IFCTRIANGULATEDFACESET is not in GeometryTypes.
In this [line](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/fragments/IfcPropertiesTiler/index.ts#L144) .
And [GeometryTypes](https://github.com/ThatOpen/engine_components/blob/main/packages/core/src/ifc/IfcJsonExporter/src/ifc-geometry-types.ts) has to include 
```
2916149573: 'IFCTRIANGULATEDFACESET'
```

### Steps to reproduce 🔢

//

### System Info 💻

```shell
//
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by superman90113** [comment]
Hi, @RyugaRyuzaki.
How can I reproduce this bug?
Do we simply add 2916149573 to GeometryTypes to fix this bug?

**Comment by RyugaRyuzaki** [comment]
> Hi, @RyugaRyuzaki. How can I reproduce this bug? Do we simply add 2916149573 to GeometryTypes to fix this bug?

yes, i think they will fix this soon, just add 2916149573 to GeometryTypes

**Comment by agviegas** [comment]
Solved thanks to @superman90113 !

**Comment by superman90113** [comment]
You are welcome. It's thanks to @RyugaRyuzaki.
