### ISSUE TITLE
Incorrect geometries of the window openings

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#66]
### Describe the bug 📝

window openings of the model is incorrect.
the geometry is not correct in comparison to the other ifc viewer
![20230614_incorrect_geometries_of_the_window_openings](https://github.com/IFCjs/components/assets/137836321/bfa9bdda-755a-4c76-8187-458a7c0d1fee)

### System Info 💻

```shell
..
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect  I think we have solved this. Can you please resend the link for this models to my mail to make sure this is already solved? Thanks!

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
Great!! we checked that it works!!
