### ISSUE TITLE
Custom model tree for the multiple IFC files

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#69]
### Description 📝

![2023-05-04 10_09_14_ModelTreeForTheMultipleModels](https://github.com/IFCjs/components/assets/137836321/647a5981-9b2b-4fce-a986-84a6319884ae)

Custom model tree – to show both federated Ifc Model structure and individual Ifc model structure
Can we also have option to move the model or orient the model origin as well as the orientation of the building?

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect I'm going to create a new issue for orientating the building and leave this just to make the entity tree support multiple models. I'm adding this to the roadmap system!

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect can you please also resend this model? Thanks!

**Comment by agviegas** [comment]
FIxed! The library now provides features to code your own tree according to your needs, as well as federation tools to make sure your models are aligned.

**Comment by ThatMetaverseArchitect** [comment]
@agviegas  federation works... do you know how we can export the ferderated models as a MERGED IFC?

**Comment by agviegas** [comment]
IFC merging is possible with [the core library](https://github.com/ThatOpen/engine_web-ifc), but we haven't created any specific component for it yet. But we plan to do it, hopefully in the next milestone, so the [template](https://github.com/ThatOpen/engine_templates) already has a built-in merge function. If you create a feature issue in this repo, I'll make sure to keep you posted once we do it

**Comment by ThatMetaverseArchitect** [comment]
@agviegas ,

we had a look at the current template. We were not able to find or understand a built-in merge function. 
Did you mean that built-in merge as a federation feature from the model tree like the image below? 
![image](https://github.com/user-attachments/assets/175caa9e-a3ac-4b5f-a0af-305bd0a2a5a4)

we understood merge IFCs as one IFC model so that we can export as a merged IFC model from the app.

Once you clarify this, I will create a feature issue in this repo so that we can keep tracking on the updates.
Thanks.

**Comment by agviegas** [comment]
Currently there's no built-in merge function to export a new merged IFC, but we can add it as a feature. Feel free to create a new feature issue and I'll take care.
