### ISSUE TITLE
Selected_Item_Display

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#70]
### Description 📝

Selected item graphic display - could we isolate the selected item(s).. perhaps, we can make unselected items in transparent mode or wire framed mode.
![2023-05-04 10_42_33_SelectedItemDisplay](https://github.com/IFCjs/components/assets/137836321/efa362c8-694e-4b8b-9344-808220a1b1cb)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Fixed! We have implemented an `isolate` function that can be called from the code. Now you also have control over the colors and appearance of the rest of the elements through the API.

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
awesome! where can we add isolate function in the code? can you perhaps provide the tutorial?? Thanks heaps!

**Comment by agviegas** [comment]
The hider tutorial is [here](https://docs.thatopen.com/Tutorials/Components/Core/Hider) and the API docs are [here](https://docs.thatopen.com/api/@thatopen/components/classes/Hider#isolate). If you have any troubles using it, let us know. The [template](https://github.com/ThatOpen/engine_templates) app already includes an "isolate" button. We'll publish it in the app URL in the next milestone

**Comment by ThatMetaverseArchitect** [comment]
@agviegas ,

Awesome!! Thanks!! we can close this feature request.
