### ISSUE TITLE
ViewCube Display And Zoom

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#71]
### Description 📝

when model is far, tooeen does not show the model, or perhaps it loads the model but we cannot find it or zoom to the model.
![2023-05-04 10_47_06_DisplayAndZoom](https://github.com/IFCjs/components/assets/137836321/3d372f0a-f3a6-437d-a25f-9602c4eabedc)

### Suggested solution 💡

perhaps, view cube will help us to find the element like most of 3D software does... when we select item from the model tree, we could click on the viewCube for allowing to zoom it to the selected item(s)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
@ThatMetaverseArchitect can you please also resend this one? Thanks!

**Comment by agviegas** [comment]
We now have features to zoom to specific model or models. You can check a tutorial [here](https://docs.thatopen.com/Tutorials/Components/Core/BoundingBoxer). We also now have a [navigation cube](https://docs.thatopen.com/api/@thatopen/ui-obc/classes/ViewCube) in the UI library.

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
Thanks!! great work!
