### ISSUE TITLE
Model_View_UI (orthographic mode & perspective)_and_ColourOverride

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#72]
### Description 📝

Orthographic & perspective view mode, as well as shaded colour options
![2023-05-04 11_04_38_ModelViewUIandColourOverride](https://github.com/IFCjs/components/assets/137836321/66004c1b-1724-42b8-b729-359da539a568)

### Suggested solution 💡

can we override the colour of each IfcEntity?
this will give us to display multiple ifc models from the different platform in consistent graphics.
I like this feature in Solibri for example.

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect can you please also resend this model? Thanks!

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
Great! thanks!!! the classifier library looks amayzing!!!
