### ISSUE TITLE
IfcPresentationLayerAssignment

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#73]
### Description 📝

we would like to show the information of <IfcPresentationLayerAssignment> in the model tree, like in Solibri. 
This is important because some of our clients use their CAD layer structure for their FM system. Ifc model could contain IfcPresentationLayerAssignment, therefore, it would be nice to filter the elements based on this information from the model tree.

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @ThatMetaverseArchitect sounds good! Can we get an example of an IFC model with IfcPresentationLayerAssignment, so we can work over something specific? Thanks in advance!

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
can you give me the link where I can test to see IfcPresentationLayerAssignment?
can I test it https://platform.thatopen.com/app from this app link?

**Comment by agviegas** [comment]
I'll add it to the [template app](https://github.com/ThatOpen/engine_templates) (which will be deployed to that URL in the next milestone

**Comment by ThatMetaverseArchitect** [comment]
@agviegas ,

with the current template, we were not able to find IfcPresentatoinLayerAssignment. 
![image](https://github.com/user-attachments/assets/0edd0108-840d-4d8e-81c4-3ffbba00e727)

Therefore, I would keep opening this request when it is  done. 
I cannot find reopening the issue in this post. 

can we reopen the issue and close it when it is done?

Thank you.

**Comment by HoyosJuan** [comment]
Hey,

We have inspected it thoroughly and indeed the direct access in the menus to the IFCPRESENTATIONLAYERASSIGNMENT is not possible in the current version of the library. This would require a considerable effort (weeks of total dedication), and as no one else in the community has asked for it, we believe that it does not provide enough value to invest that time in this particular functionality. Of course, that doesn't mean that you can't implement it on your side using our APIs as a starting point.

If in the future we see a need for this functionality in the library, we will reopen this issue.

Take care!
