### ISSUE TITLE
IFC 2x3 TC1_Structural Analysis View (MVD)

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#74]
### Description 📝

can we enable to show the MVD of the Structural Analysis View?
This will help the structural engineers to collaborate the analytical model in IFC format.
There are no commercial IFC viewers offers this MVD to display... In fact, it will help a lot for the collaboration between the structural engineers.
![2023-05-04 12_00_57_ IFC 2x3 TC1_Structural Analysis View_notSupporting](https://github.com/IFCjs/components/assets/137836321/3645090e-d336-48f8-969e-ff2a1ed7946c)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
This is already possible! The library now exposes all the information of the IFC, so creating custom filters to just show a specific MVD is already possible using the [visibility API](https://docs.thatopen.com/Tutorials/Components/Core/Hider).

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
we have still problem to load Structural Analysis View. Please check the model I have shared today.

**Comment by agviegas** [comment]
Will do

**Comment by ThatMetaverseArchitect** [comment]
@agviegas 
Thanks. This is not an urgent issue. 
Structural Analysis View is one of many MVDs. We would like to verify that the current template is not able to open any MVDs.

**Comment by agviegas** [comment]
This issue belongs to the core, so I've created a related issue [here](https://github.com/ThatOpen/engine_web-ifc/issues/984).
