### ISSUE TITLE
IfcSpace Information in plan view

### ISSUE THREAD

**Issue by ThatMetaverseArchitect** [ThatOpen/engine_components#77]
### Description 📝

can we display also the room information in 2d plan view?
![2023-06-27 00_58_50-Tooeen weekly - 16_roomName](https://github.com/IFCjs/components/assets/137836321/7d201771-a677-4616-814d-43526e896c28)

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
This is already possible with the current API! The library allows to select rooms in floor plans, get it's information and create labels to display it in your apps. If you do it and have any questions along the way, let me know

**Comment by agviegas** [comment]
I'll prepare a small example using the current API and send it here asap

**Comment by ThatMetaverseArchitect** [comment]
@agviegas,

can we automate to create lables in the plan views? instead of selecting the rooms? or can we select bulk rooms from the filter and assign the lables to be appear in the plan views?

Do you know why my request is closed? I did not closed the issue.. Somehow it appeared as closed. 

Thanks heaps.. we will wait for the example and tutorial from you.

**Comment by HoyosJuan** [comment]
Here you have a simple example that annotates floorplans surface using our libraries and some basic Three.js knowledge. 

https://github.com/user-attachments/assets/2c5d2299-2382-4654-bee5-75241360fc95

Here is the working example: [example.zip](https://github.com/user-attachments/files/16551229/example.zip)

We can't cover all use cases with our libraries, but we can provide APIs that allow users to make them easily like this. This is using the [plans tutorial](https://docs.thatopen.com/Tutorials/Components/Front/Plans) as a starting point.

Cheers!

**Comment by T-pavel** [comment]
Good afternoon, after updating to version 2.2.0, plan.point.y, from where we received the offset for displaying areas and their calculation, stopped coming, I hope that I’m right about this. Now it is not entirely clear how to calculate the area, and what the condition y < -0.9 means. For my small model, this check does not pass, tell me what this means?

**Comment by agviegas** [comment]
@T-pavel can you open an issue? We'll take a look
