### ISSUE TITLE
Sort levels by height for exploding tool

### ISSUE THREAD

**Issue by RASRC** [ThatOpen/engine_components#93]
### Describe the bug 📝

I'm having some problems with the explode tool.

It appears to don't work well with levels that have negative elevation (I mean that this levels are positioned below the IFC origin). The elements are displayed in an incorrect position above the origin  when you explode the model like in the screen captures.
There is something I can do to fix it? Thanks!
![Cap02](https://github.com/IFCjs/components/assets/117295504/86235eea-a064-418d-9e2d-3c528a47facb)
![Cap03](https://github.com/IFCjs/components/assets/117295504/9592c08b-cf2c-40ca-b7e2-1d176e211764)

### Reproduction ▶️

https://github.com/RASRC/FrontEnd_Course.git

### Steps to reproduce 🔢

Activating the explode tool in the bottom menu of the app

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RASRC** [comment]
Hi @agviegas 

I write to ask you if there is a chance to solve this issue for the official release.

Thanks!

**Comment by agviegas** [comment]
We'll try! Otherwise, we'll fix it after September 20. Cheers!

**Comment by RASRC** [comment]
Hi @agviegas.

I send you the IFC file. It could be useful if you want to do some tests.

Thanks!

[25052023-896-WTC.zip](https://github.com/IFCjs/components/files/13259803/25052023-896-WTC.zip)

**Comment by HoyosJuan** [comment]
Hi @RASRC! I'm just following up this issue. Are still experiencing the same problems when updating to openbim-components@1.1.5?

**Comment by RASRC** [comment]
Hi @HoyosJuan! Yes I have that version running and the issue is still there. I left the ifc file in a previous message if you want to do some tests.
Thanks!

**Comment by RASRC** [comment]
Hi @HoyosJuan! I'm using the 1.2.0 version of the library now and still have the same issue

**Comment by RASRC** [comment]
Hi @HoyosJuan! 
Did you can test the FragmentExploder with the model I attached to the issue?
Thanks.

**Comment by agviegas** [comment]
Hey! After the big refactor of the library, this milestone we are checking and solving issues. We have also updated [the exploder](https://docs.thatopen.com/Tutorials/Components/Core/Exploder). Now, you can classify the model like this:

```ts
const classifier = components.get(OBC.Classifier);
await classifier.bySpatialStructure(model);
```

That won't sort the storeys by default because it's generic to any kind of relationship, but you can easily sort them by getting all the storeys and using its elevation information. Good thing about this approach is that even in those files where the elevation information is somewhere else, a custom sort method can be established for the exploder:

```ts
const storeys = await model.getAllPropertiesOfType(WEBIFC.IFCBUILDINGSTOREY);

if (storeys) {
  const storeyList = Object.values(storeys);
  storeyList.sort((a, b) => a.Elevation.value - b.Elevation.value);
  const sortedIds = storeyList.map((item) => item.Name.value);
  const newClassifiedStories: typeof classifier.list.spatialStructures = {};
  for (const id of sortedIds) {
    const classifiedStories = classifier.list.spatialStructures;
    newClassifiedStories[id] = classifiedStories[id];
  }
  classifier.list.spatialStructures = newClassifiedStories;
}
```

This should be possible from `@thatopen/components@2.0.14`, which I'm publishing right now. I'm also going to update the docs right away. Let me know if you face any issues with this. Cheers!
