### ISSUE TITLE
SimpleDimensionLine - looks like Autodesk Forge

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_components#98]
### Description 📝

I want to integrate this tool looks like Autodesk Forge Measurement .
![image](https://github.com/IFCjs/components/assets/89787521/c2306193-6f4c-4b9f-a820-5461a8ba7ec9)

### Suggested solution 💡

I can handle that, but i can not fork branch "big -restructure". And i want to access this function https://github.com/IFCjs/components/blob/big-restructure/src/core/Components/index.ts#L131 to make the width of line dimension none- change when we zoom out/in

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by agviegas** [comment]
Hey @RyugaRyuzaki great idea! If you want to make it yourself, you should already be able to fork the main branch and start working on it 🙂 Will you start working on this? Otherwise, don't worry, we can do this ourselves. I agree that dimensions can be greatly improved.

**Comment by agviegas** [comment]
We already have endpoints in our measurements! You can check them out [in the tutorial](https://docs.thatopen.com/Tutorials/Components/Front/LengthMeasurement). If you want to customize them, you can also create your own custom dimension components. Cheers
