### ISSUE TITLE
IFC Viewer: Not showing the same view, Missing some fragments/objects.

### ISSUE THREAD

**Issue by shailendra26-siso** [ThatOpen/engine_components#99]
### Describe the bug 📝

I found another issue with IFC Viewer. Same file I checked in in our code as well I checked in different portal (first and second images), It is not showing same.
And in Our Viewer, it is different, some Fragments/Objects are not visible (third and fourth images).

![MicrosoftTeams-image (2)](https://github.com/IFCjs/components/assets/119593005/7108350b-9395-4d5e-b41e-5e73012b96ad)

<img width="685" alt="BV-2" src="https://github.com/IFCjs/components/assets/119593005/c5c1a9c7-9fe9-4840-a425-caa0180b469d">

<img width="881" alt="1" src="https://github.com/IFCjs/components/assets/119593005/f8d389ed-4bc0-43e4-b416-04fa9df383ab">

<img width="445" alt="2" src="https://github.com/IFCjs/components/assets/119593005/1f1bf8d8-5c95-44c7-8868-f0b1658403d2">

### System Info 💻

```shell
openbim-components
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js components issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @shailendra26-siso any chance we can get access to this IFC file privately to implement the missing objects? Happy to sign an NDA if needed.

**Comment by shailendra26-siso** [comment]
Hi,

 

I will let you know regarding the IFC file as soon.

Thanks for considering my issue.

 

Shailendra Singh

 



SISO Software’s India Pvt. Ltd.

B-3/61, Safdarjung Enclave, IN-110029 Delhi, India.

Contact: +91-9911682739

 <http://www.siso.net/> www.siso.net

**Comment by shailendra26-siso** [comment]
Hi,

 

I discussed with team and decide that we can provide the that IFC file but need to surety that it is confidential and will not to public or transfer to anyone.

I will provide you the that IFC file.

 

Shailendra Singh

 



SISO Software’s India Pvt. Ltd.

B-3/61, Safdarjung Enclave, IN-110029 Delhi, India.

Contact: +91-9911682739

 <http://www.siso.net/> www.siso.net

**Comment by shailendra26-siso** [comment]
Hi Antonio,

 

I will provide you the IFC file privately. Please let me know How I can provide you the IFC file?

 

 

Shailendra Singh

 



SISO Software’s India Pvt. Ltd.

B-3/61, Safdarjung Enclave, IN-110029 Delhi, India.

Contact: +91-9911682739

 <http://www.siso.net/> www.siso.net

**Comment by agviegas** [comment]
@shailendra26-siso you can share it in a google drive folder and give access to antonio@thatopen.com. Thanks a ton!

**Comment by shailendra26-siso** [comment]
Hi Antonio,

I have another file which is uploading, gives the error. Please look into this also.
<img width="828" alt="image" src="https://github.com/IFCjs/components/assets/119593005/c1bb0c49-74e9-47d6-84ef-405db5653aa2">
<img width="307" alt="image" src="https://github.com/IFCjs/components/assets/119593005/f9a30033-f950-4761-804e-e5d5e33c7eff">

Whereas other tools is showing this IFC file.
<img width="777" alt="image" src="https://github.com/IFCjs/components/assets/119593005/74f32110-68d4-4463-a534-29b51d2ed324">

**Comment by agviegas** [comment]
Hey, all these issues should be solved. If there's any specific element still missing in those files, feel free to open an issue in our [core library](https://github.com/ThatOpen/engine_web-ifc). Cheers!
